### ISSUE TITLE
SDK and engine separation 

### ISSUE THREAD

**Issue by davie504** [nillerusr/source-engine#101]
Can you separate the engine and sdk? I want to fork your SDK and make a mod on it, but while it is in the engine, it is very inconvenient to do this.

**Comment by halotroop2288** [comment]
I would really like to see this as well. This engine has a lot of improvements I would like to see in the regular Source SDK, but it's probably never going to happen like that. I find it more likely that we'll get an SDK out of this and I would be excited to use it.

Obviously a lot of things are unforeseeable, but how much work do you think it might be to do this? Is it something you could get done in a week or a month, or would it take longer?

**Comment by ItzVladik** [comment]
./waf build --target=client,server

**Comment by SanyaSho** [comment]
@davie504 https://github.com/nillerusr/source-sdk-2022

**Comment by halotroop2288** [comment]
And... it's gone.

**Comment by nillerusr** [comment]
@halotroop2288 its gone,but will return
