### ISSUE TITLE
About Android port displaying Chinese

### ISSUE THREAD

**Issue by magisk666** [nillerusr/source-engine#104]
Hi nill, I want to give feedback on a problem that has existed since version 1.05, that is, the Android source engine port can display the Chinese fonts in the game normally in versions before 1.05, but in versions 1.05 and later, it can no longer display the original Chinese fonts in the game, unless you use some special methods, such as Chinese netizens have come up with a method to replace the fonts. But this method does not work completely, some times there are still problems, so please fix this long-standing problem quickly 😄
Nevertheless, I don't know whether the PC version will also have this problem.
![243016596218592](https://user-images.githubusercontent.com/77914162/182867741-981b157c-eb3a-428f-b7a4-ab501d3232c7.png)

**Comment by magisk666** [comment]
Not only the Chinese font can't be displayed, but after my test, the sea includes Japanese, Korean, etc., which makes people who can't understand English very uncomfortable.😂😂😂

**Comment by nillerusr** [comment]
Strange

**Comment by nillerusr** [comment]
![Screenshot_20220805-211430840](https://user-images.githubusercontent.com/42746659/183137084-01d2c8e1-4f76-447a-9207-b2742a23db1e.jpg)

Fixed:)
