### ISSUE TITLE
Android, switch to the background task interface, and the game is black

### ISSUE THREAD

**Issue by magisk666** [nillerusr/source-engine#109]
When you are loading the game or loading the map and you switch to the background task screen and then switch back to the game, the game will face a black screen and there is no counter.
device
Android 11
CPU mtk p90

**Comment by main-thing** [comment]
Its still loading. The game screen is just black.

**Comment by magisk666** [comment]
> 它仍在加载。游戏画面就是黑的。

Can I switch back to normal as xash3d?

**Comment by main-thing** [comment]
Not yet. Just wait awhile and it would come back.
