### ISSUE TITLE
(Help) waf configuration; gcc, clang not found (Android, Termux)

### ISSUE THREAD

**Issue by MrMeugh** [nillerusr/source-engine#113]
I'm trying to compile for Android via Termux, but when trying to configure waf I get the following:
```
Checking for 'gcc' (C compiler)
: not found
Checking for 'clang' (C  compiler)
: not found
Checking for 'icc' (C compiler)
: not found
could not configure a C compiler!
(complete log in /data/data/com.termux/files/home/source
-engine/build.config.log)
```

Command used was `./waf configure -T release --android=aarch64,4.9,21`

and here's [config.log](https://github.com/nillerusr/source-engine/files/9355317/config.log)

I'm pretty much clueless as to what to do now, and have no idea how to interpret the relevant bits of config.log

**Comment by nillerusr** [comment]
Same as #99  , wontfix

**Comment by stephen-cusi** [comment]
> 我正在尝试通过 Termux 为 Android 编译，但是在尝试配置 waf 时我得到以下信息：
> 
> ```
> Checking for 'gcc' (C compiler)
> : not found
> Checking for 'clang' (C  compiler)
> : not found
> Checking for 'icc' (C compiler)
> : not found
> could not configure a C compiler!
> (complete log in /data/data/com.termux/files/home/source
> -engine/build.config.log)
> ```
> 
> 使用的命令是`./waf configure -T release --android=aarch64,4.9,21`
> 
> 这是[config.log](https://github.com/nillerusr/source-engine/files/9355317/config.log)
> 
> 我对现在该做什么一无所知，也不知道如何解释 config.log 的相关位
Termux does not support android ndk, and you have not imported environment variables
