### ISSUE TITLE
Some textures on PowerVR Rogue GE8322 has broken transperency

### ISSUE THREAD

**Issue by SanyaSho** [nillerusr/source-engine#119]
![Screenshot_20220907-173946](https://user-images.githubusercontent.com/68691958/188908366-5c6182d9-f2ae-4f7a-854f-bc622289265f.png)
![Screenshot_20220907-173244](https://user-images.githubusercontent.com/68691958/188908376-d4c3ebef-7e57-4ecc-b614-d2327fa0bd3b.png)

**Comment by nillerusr** [comment]
Bruh that's hl1dm problem

**Comment by SanyaSho** [comment]
> Bruh that's hl1dm problem, not powervr. Or maybe togles

ну скорее да, проблемa togles. но никак не хл1мп, в хл2 вылазит тоже самое
![Screenshot_20220908-080209](https://user-images.githubusercontent.com/68691958/189038589-8fdf5412-9d8e-4d29-adcb-db172a1883c2.png)

**Comment by nillerusr** [comment]
@SanyaSho обновись блять

**Comment by SanyaSho** [comment]
> @SanyaSho обновись блять заебал

![IMG_20220908_135352](https://user-images.githubusercontent.com/68691958/189104859-e5ee3169-2dc1-4a9b-a2c0-a466ac5afec8.jpg)
