### ISSUE TITLE
Help needed, build fails using instricrions latest arch linux machine (vm)

### ISSUE THREAD

**Issue by hipocentrum** [nillerusr/source-engine#12]
Hello, I install git, run the commands from instruction readme but it fails. I pastet the commandline output below, hope it helps:
[epicer223@desktopvm]: ~>$ git clone https://github.com/nillerusr/source-engine
Cloning into 'source-engine'...
remote: Enumerating objects: 27353, done.
remote: Counting objects: 100% (415/415), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 27353 (delta 207), reused 299 (delta 203), pack-reused 26938
Receiving objects: 100% (27353/27353), 171.46 MiB | 2.08 MiB/s, done.
Resolving deltas: 100% (8173/8173), done.
Updating files: 100% (14430/14430), done.
[epicer223@desktopvm]: ~>$ git submodule init && git submodule update
fatal: not a git repository (or any of the parent directories): .git
[epicer223@desktopvm]: ~>$ ./waf configure -T debug
bash: ./waf: No such file or directory
[epicer223@desktop]: ~>$ ./waf build
bash: ./waf: No such file or directory
[epicer223@desktopvm]: ~>$

**Comment by HugoShady** [comment]
you're not in the source directory

**Comment by HugoShady** [comment]
cd source-engine

**Comment by hipocentrum** [comment]
> cd source-engine

but it says not in instructions...

**Comment by kkw070504** [comment]
you should use git submodule init && git submodule update after you chang directory to source-engine by using cd source-engine

**Comment by hipocentrum** [comment]
> you should use git submodule init && git submodule update after you chang directory to source-engine by using cd source-engine

Sorry, thank you, but it should be added to readme I think, very important missing step there :sweat_smile:
