### ISSUE TITLE
Windows compilation issue: vtex_dll.lib really does not want to exist.

### ISSUE THREAD

**Issue by GordonFreakman** [nillerusr/source-engine#125]
Creating library utils\vtex\vtex_dll.lib and object utils\vtex\vtex_dll.exp
imageutils.cpp.46.o : error LNK2019: unresolved external symbol __imp__CreateCompatibleDC@4 referenced in function "unsigned char * __cdecl ImgUtl_ReadBMPAsRGBA(char const *,int &,int &,enum ConversionErrorType &)" (?ImgUtl_ReadBMPAsRGBA@@YAPAEPBDAAH1AAW4ConversionErrorType@@@Z)
imageutils.cpp.46.o : error LNK2019: unresolved external symbol __imp__DeleteDC@4 referenced in function "unsigned char * __cdecl ImgUtl_ReadBMPAsRGBA(char const *,int &,int &,enum ConversionErrorType &)" (?ImgUtl_ReadBMPAsRGBA@@YAPAEPBDAAH1AAW4ConversionErrorType@@@Z)
imageutils.cpp.46.o : error LNK2019: unresolved external symbol __imp__DeleteObject@4 referenced in function "unsigned char * __cdecl ImgUtl_ReadBMPAsRGBA(char const *,int &,int &,enum ConversionErrorType &)" (?ImgUtl_ReadBMPAsRGBA@@YAPAEPBDAAH1AAW4ConversionErrorType@@@Z)
imageutils.cpp.46.o : error LNK2019: unresolved external symbol __imp__GetDIBits@28 referenced in function "unsigned char * __cdecl ImgUtl_ReadBMPAsRGBA(char const *,int &,int &,enum ConversionErrorType &)" (?ImgUtl_ReadBMPAsRGBA@@YAPAEPBDAAH1AAW4ConversionErrorType@@@Z)
imageutils.cpp.46.o : error LNK2019: unresolved external symbol __imp__GetObjectA@12 referenced in function "unsigned char * __cdecl ImgUtl_ReadBMPAsRGBA(char const *,int &,int &,enum ConversionErrorType &)" (?ImgUtl_ReadBMPAsRGBA@@YAPAEPBDAAH1AAW4ConversionErrorType@@@Z)
imageutils.cpp.46.o : error LNK2019: unresolved external symbol __imp__LoadImageA@24 referenced in function "unsigned char * __cdecl ImgUtl_ReadBMPAsRGBA(char const *,int &,int &,enum ConversionErrorType &)" (?ImgUtl_ReadBMPAsRGBA@@YAPAEPBDAAH1AAW4ConversionErrorType@@@Z)
libpng.lib(png.obj) : error LNK2019: unresolved external symbol _inflateReset referenced in function _png_reset_zstream
libpng.lib(pngrutil.obj) : error LNK2001: unresolved external symbol _inflateReset
libpng.lib(png.obj) : error LNK2019: unresolved external symbol _crc32 referenced in function _png_calculate_crc
libpng.lib(pngread.obj) : error LNK2019: unresolved external symbol _inflate referenced in function _png_read_row
libpng.lib(pngrutil.obj) : error LNK2001: unresolved external symbol _inflate
libpng.lib(pngread.obj) : error LNK2019: unresolved external symbol _inflateEnd referenced in function _png_read_destroy
libpng.lib(pngread.obj) : error LNK2019: unresolved external symbol _inflateInit_ referenced in function _png_create_read_struct_2
libpng.lib(pngwrite.obj) : error LNK2019: unresolved external symbol _deflate referenced in function _png_write_flush
libpng.lib(pngwutil.obj) : error LNK2001: unresolved external symbol _deflate
libpng.lib(pngwrite.obj) : error LNK2019: unresolved external symbol _deflateEnd referenced in function _png_write_destroy
libpng.lib(pngwutil.obj) : error LNK2001: unresolved external symbol _deflateEnd
libpng.lib(pngwutil.obj) : error LNK2019: unresolved external symbol _deflateReset referenced in function _png_zlib_release
libpng.lib(pngwutil.obj) : error LNK2019: unresolved external symbol _deflateInit2_ referenced in function _png_zlib_claim
G:\source-engine\build\utils\vtex\vtex_dll.dll : fatal error LNK1120: 15 unresolved externals

Waf: Leaving directory `G:\source-engine\build'
Build failed
 -> task in 'vtex_dll' failed with exit status 1120 (run with -v to display more information)

**Comment by nillerusr** [comment]
I think u forget to clone submodules

**Comment by EnderZip** [comment]
64bit for tools are not yet supported

**Comment by WitherOrNot** [comment]
looks like zlib is not being linked....

**Comment by EnderZip** [comment]
You need the 64bit version of those libraries

**Comment by GordonFreakman** [comment]
Can I exclude it because they don't seem to be effecting the rest of the engine

**Comment by EnderZip** [comment]
Yes, edit the waf scripts and remove all of the tools

**Comment by EnderZip** [comment]
Well the dude is asking how to compile, not how to make it to work ;)

**Comment by bdbd789** [comment]
I'm having the same problem.

**Comment by LegendaryGuard** [comment]
> @EnderZip man on windows 64bit is not supported. Because long on windows - 32bit. Vtex_dll - library for converting sprays inside the game and it works on 64bit

Now that I remember... HappyDOGE mentioned this: https://github.com/nillerusr/source-engine/pull/85#issue-1320958091
Windows 64 bits build would be available if physics were fixed, right?
