### ISSUE TITLE
Telling WAF what version of MSVC/Visual studio to use for configure

### ISSUE THREAD

**Issue by EpicSentry** [nillerusr/source-engine#127]
OS: Windows 10 64 bit
I have 3 versions of VS installed in order:
2013
2019
2015
VS 2015 is not supported in the compile guide but because it was installed last WAF is using it as the compiler which just causes errors like:
"Checking for 'msvc' (C++ compiler)                      : Resource compiler not found. Compiling resource file is disabled"
and
"Compiler can't create 32-bit code!
(complete log in G:\source-engine\build\config.log)"
Any ideas how to change this?

**Comment by EnderZip** [comment]
Download the compiler from VS installer or try `waf help`

**Comment by nillerusr** [comment]
use VS environment to build. Also 2015 is supported well

**Comment by EpicSentry** [comment]
> use VS environment to build. Also 2015 is supported well

**Comment by EpicSentry** [comment]
Sorry miss click on mobile. Anyways when I tried waf help it listed a few things that didn’t help. How do I use createallprojects.bat to make the solution for vs2019?

**Comment by LegendaryGuard** [comment]
I've created a solution using `waf.bat msvs` on Windows. 
AFAIK, works for VS2015, as I mentioned when source engine project was first successfully compiled, building all the stuff: https://github.com/nillerusr/source-engine/issues/62#issuecomment-1198672935

**Comment by EpicSentry** [comment]
> 

Thank you that fixed all the issues and i was able  to compile what i needed
