### ISSUE TITLE
Unknown Shaders issue.

### ISSUE THREAD

**Issue by JoeMama54** [nillerusr/source-engine#128]
I downloaded HL2 from steam and copied the HL2 folder over without the bin folder and I'm having issues launching.
Compiled with VS 2022 on Windows 11 
![image](https://user-images.githubusercontent.com/32758963/195785121-9553a28d-f569-4947-a641-bc7e19692917.png)

**Comment by nillerusr** [comment]
Uf, run with -dxlevel 90
I should set it by default...

**Comment by JoeMama54** [comment]
Nice! That fixed it.
