### ISSUE TITLE
WAF Not Working in Windows Server 2019

### ISSUE THREAD

**Issue by qLoganAniversity** [nillerusr/source-engine#134]
#im qLogan
#Im Find you and see source engine
#im git clone this on vps 
##so im try to compiling on windows server 2019 
#waf has Configure error
##im need this for PicAxe Engine 
(sorry for my bad english)

**Comment by nillerusr** [comment]
config.log please

**Comment by qLoganAniversity** [comment]
im working into a russian vps

The islamic Republic of iran has closed all ports and cant connect to vps
Thanks for waiting
