### ISSUE TITLE
Colorcorrection is broken at all with togl/togles.

### ISSUE THREAD

**Issue by klaxons1** [nillerusr/source-engine#137]
In my opinion, colorcorrection is a very important thing of level design. It gives the level a certain tone.
So it really needs to be fixed. 
![Screenshot_2022-11-03-01-13-37-020_com valvesoftware source](https://user-images.githubusercontent.com/59658354/200203478-a730dd5a-0d39-4635-85af-90f51ea64eb3.jpg)
I can build a simple level for testing, if you want to.

**Comment by qLoganAniversity** [comment]
Your env_light entity has incorrect configuration
Check this

**Comment by davie504** [comment]
> Your env_light entity has incorrect configuration Check this

It's not. This problem caused by togles.

**Comment by tifasoftware** [comment]
could there be a possible reason why this issue is happening with color correction.

**Comment by MaddTheSane** [comment]
It could be an alignment issue.
Or an assumption that `long`s are always 32-bit (this isn't true on LP64 systems, which include macOS and Linux, but doesn't include Windows).

**Comment by tifasoftware** [comment]
Perhaps we can get someone to find the differences in RGB values and add some sort of math to correct this?
