### ISSUE TITLE
Cannot compile 64-bit (windows)

### ISSUE THREAD

**Issue by conneath** [nillerusr/source-engine#149]
```
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(6): error C4235: nonstandard extension used: '__asm' keyword not supported on this architecture
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(7): error C2065: 'mov': undeclared identifier
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(7): error C2146: syntax error: missing ';' before identifier 'edi'
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(7): error C2065: 'edi': undeclared identifier
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(8): error C2146: syntax error: missing ';' before identifier 'rdtsc'
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(8): error C2065: 'rdtsc': undeclared identifier
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(9): error C2146: syntax error: missing ';' before identifier 'mov'
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(9): error C2065: 'mov': undeclared identifier
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(9): error C2065: 'edi': undeclared identifier
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(9): error C2065: 'eax': undeclared identifier
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(10): error C2146: syntax error: missing ';' before identifier 'mov'
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(10): error C2065: 'mov': undeclared identifier
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(10): error C2065: 'edi': undeclared identifier
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(10): error C2065: 'edx': undeclared identifier
source-engine\ivp\havana\havok\hk_base\stopwatch\stopwatch_qpt.inl(11): error C2143: syntax error: missing ';' before '}'```

**Comment by nillerusr** [comment]
64bit for windows unsupported, lol.
windows must die.

**Comment by conneath** [comment]
i dont think thats going to happen

**Comment by LegendaryGuard** [comment]
Windows is widely used in the world. There are a lot of people using this engine in this OS (even without using this source code, but playing some source games) in this OS. 

I think it's worth having 64-bit support for Windows, if it's being cross platform, gives more usefulness and can get more adaptation to such devices.

I understand there are some people like the owner of this repository who don't use it, but I consider it would be nice to have that support. People would be proud, that's my advice.

**Comment by EnderZip** [comment]
if you want win64, do it yourself. most of the x64 stuff on linux is the same on windows anyway.
this repo is about porting source engine to arm not windows

**Comment by EnderZip** [comment]
Fr my previous post did not aged well 💀

**Comment by MakeSureDudeDies** [comment]
> Windows is widely used in the world. There are a lot of people using this engine in this OS (even without using this source code, but playing some source games).
> 
> I think it's worth having 64-bit support for Windows, if it's being cross platform, gives more usefulness and can get more adaptation to such devices.
> 
> I understand there are some people like the owner of this repository who don't use it, but I consider it would be nice to have that support. People would be proud, that's my advice.

ik its been 3 weeks since this comment, but real men usd Linux or BSD, all the other one's are trash.

**Comment by conneath** [comment]
fixed after recent commits
