### ISSUE TITLE
create .sln file

### ISSUE THREAD

**Issue by sadfi2259x** [nillerusr/source-engine#161]
how to create a .sln file ?
is it possible to support back sln for visual studio

**Comment by SanyaSho** [comment]
no, use qtcreator or other IDE

**Comment by nillerusr** [comment]
@sadfi2259x waf.bat msvc

**Comment by tmob03** [comment]
> @sadfi2259x waf.bat msvc

I just get this: 
![image](https://github.com/nillerusr/source-engine/assets/33987871/080ec8ae-629f-4d05-91c1-7557300dc684)
