### ISSUE TITLE
waf.bat doesn't works. 

### ISSUE THREAD

**Issue by AlreadyInTheGame** [nillerusr/source-engine#164]
I'm try installing python 3.11 x64, 3.11 x86, 3.7 x86. But there is a error:

![error](https://user-images.githubusercontent.com/121860812/210334951-12e4b2cd-a05a-4802-9b07-287241428077.png)
I'm use Visual Studio 2019.
And I don't know why this error happens.

**Comment by AlreadyInTheGame** [comment]
I don't know why this error happens.

**Comment by AlreadyInTheGame** [comment]
I'm using Microsoft Visual Studio 2019 Professional

**Comment by nillerusr** [comment]
Bruh don't download repo as zip archive. Use `git clone --recursive` for that
