### ISSUE TITLE
Android 64-bit build

### ISSUE THREAD

**Issue by dust2stairs** [nillerusr/source-engine#169]
Android will soon end support for 32-bit apps. This has already happened with the Google Pixel 7 and similar phones. Therefore, I think it is good to add support for 64 bit Android because there will not be 32 bit support in the future,

**Comment by stephen-cusi** [comment]
> Android will soon end support for 32-bit apps. This has already happened with the Google Pixel 7 and similar phones. So I think it's good to add support for 64-bit Android, because there will be no 32-bit support in the future.

There are already 64 bits

**Comment by stephen-cusi** [comment]
![IMG_20230109_192951](https://user-images.githubusercontent.com/111830109/211298532-8226f464-6cea-45cf-8f18-55d8703a0e53.png)

**Comment by dust2stairs** [comment]
Really ? I thought the waf command generates for arm 32 bit (arm v7)

**Comment by nillerusr** [comment]
`Really ? I thought the waf command generates for arm 32 bit (arm v7)`

It can generate aarch64 builds. But i should rewrite build-guide for android builds.
