### ISSUE TITLE
[Linux] Build problem

### ISSUE THREAD

**Issue by minktusk** [nillerusr/source-engine#173]
Can someone help me with this problem?

Log:

> gabriel@gabriel-22V240-L-BJ34P1:~/Downloads/source-engine$ ./waf configure -T release --prefix=/path/to/directory/with/hl2 
Setting top to                                          : /home/gabriel/Downloads/source-engine 
Setting out to                                          : /home/gabriel/Downloads/source-engine/build 
Build type                                              : release 
LTO build                                               : no 
PolyOpt build                                           : no 
Checking for 'gcc' (C compiler)                         : /usr/bin/gcc 
Target OS                                               : linux 
Target CPU                                              : x86_64 
Target binfmt                                           : elf 
Checking for 'g++' (C++ compiler)                       : /usr/bin/g++ 
Target OS                                               : linux 
Target CPU                                              : x86_64 
Target binfmt                                           : elf 
Checking for program 'git'                              : /usr/bin/git 
Checking git hash                                       : 3458c36 
Checking for program 'strip'                            : /usr/bin/strip 
Checking for program 'objcopy'                          : /usr/bin/objcopy 
WARNING: will build engine for 32-bit target
Checking if 'gcc' can target 32-bit                     : no 
...trying with additional flags                         : yes 
Checking for required C flags                           : yes 
Checking for required C++ flags                         : no 
The configuration failed
(complete log in /home/gabriel/Downloads/source-engine/build/config.log)

Linux Distro:

> Kubuntu 22.10

**Comment by stephen-cusi** [comment]
-8

**Comment by nillerusr** [comment]
1. You should replace prefix directory with YOUR directory.
2. pass `--64bits` or `-8` to configure

**Comment by minktusk** [comment]
Thanks
