### ISSUE TITLE
Building on macOS Arm

### ISSUE THREAD

**Issue by kotleni** [nillerusr/source-engine#179]
Building on macOS Arm works? How to?

**Comment by stephen-cusi** [comment]
Yes, he can build on arm64-based Mac OS, but the Wiki for this repository doesn't contain a build guide for Mac OS, so you'll have to check out sanyasho's build guide
[Perfect construction guide](https://github.com/SanyaSho/junk-engine/wiki/J.U.N.K.-Engine-(EN))

**Comment by kotleni** [comment]
@stephen-cusi 
<img width="617" alt="Screenshot 2023-01-21 at 16 33 20" src="https://user-images.githubusercontent.com/38311102/213871565-29e5a7cb-a22f-443e-b7f9-4dcd21c9504c.png">

**Comment by kotleni** [comment]
I tried to build it before but it can't find sdl2. (it's definitely installed)

**Comment by kotleni** [comment]
I fixed it.
I just added custom config file to pkg-config path.
<br>File content:
```
prefix=/opt/homebrew/Cellar/sdl2/2.24.1
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Name: sdl2
Description: The sdl2 library
Version: 2
Cflags: -I${includedir}/SDL2
Libs: -L${libdir} -lSDL2
```

**Comment by kotleni** [comment]
<img width="696" alt="Screenshot 2023-01-21 at 22 13 38" src="https://user-images.githubusercontent.com/38311102/213885472-27660ebe-1b8f-4769-917c-ad6662cd79d7.png">
How, i have this error.

**Comment by kotleni** [comment]
<img width="696" alt="Screenshot 2023-01-21 at 22 13 38" src="https://user-images.githubusercontent.com/38311102/213885472-27660ebe-1b8f-4769-917c-ad6662cd79d7.png">
How, i have this error.

**Comment by kotleni** [comment]
Okay, i have success compiled binaries. Thanks.
I just added this to wscript file to 322 line.
```
if conf.env.DEST_OS == 'darwin':
	flags += ['-I/opt/homebrew/opt/libiconv/include', '-L/opt/homebrew/opt/libiconv/lib', '-liconv']
```
