### ISSUE TITLE
[Build] Build without DirectX on Windows

### ISSUE THREAD

**Issue by LakoMoor** [nillerusr/source-engine#184]
Is it possible to build a game without Directx using OpenGL?

**Comment by stephen-cusi** [comment]
Use togl?

**Comment by stephen-cusi** [comment]
Use togl instead of es

**Comment by LakoMoor** [comment]
> Togl is linux only, and you need directx for togl to work (its a translation layer from dx to gl, not a full graphics api implementation)

oh... sad :(
