### ISSUE TITLE
Win32: CStrike Source can't launch - Cannot find procedure entry point ThreadSleep in dynamic link library video_quicktime.dll

### ISSUE THREAD

**Issue by LegendaryGuard** [nillerusr/source-engine#189]
I compiled the 32 bits release for CSS. Like I did:
```ps
.\waf.bat configure -T release --build-games=cstrike --prefix=../build_source-engine_CSTRIKE_32-bit
.\waf.bat install
```

That pop-ups when trying to launch the game.
![image](https://user-images.githubusercontent.com/49716252/215600084-a40cc204-fe92-442e-a4e1-f804e0da3d2e.png)
After pop-ups again (2nd time) and same window and when you press Accept, window closes and game doesn't launch.

The window says:
```
Cannot find procedure entry point ThreadSleep in dynamic link library C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Source\bin\video_quicktime.dll
```

**Comment by nillerusr** [comment]
another invalid issue, delete steam binaries before installing ones compiled from this repo
