### ISSUE TITLE
dedicated build failed

### ISSUE THREAD

**Issue by 0x00000ED** [nillerusr/source-engine#190]
OS: Windows 10
My actions:
```
git clone https://github.com/nillerusr/source-engine.git
git submodule init
git submodule update
```

Configure: .\waf configure -T release -d
Build: .\waf build
What am I doing wrong, or maybe I haven't downloaded any libraries?
[configure.txt](https://github.com/nillerusr/source-engine/files/10569278/configure.txt)
[build.txt](https://github.com/nillerusr/source-engine/files/10569281/build.txt)

**Comment by SanyaSho** [comment]
serverbrowser branch?

**Comment by 0x00000ED** [comment]
master

**Comment by stephen-cusi** [comment]
I also encountered the problem, despite using master

**Comment by nillerusr** [comment]
@0x00000ED не используй `-d` параметр. Для него нужны зависимости с дебагом. Ох уж эта шинда....

**Comment by nillerusr** [comment]
Надо где-то написать что Issue принимаются и на русском, так все же проще
