### ISSUE TITLE
P2CE VTF 7.6 support

### ISSUE THREAD

**Issue by SanyaSho** [nillerusr/source-engine#194]
About VTF 7.6 (from VDC):
- Adds support for [deflate](http://en.wikipedia.org/wiki/Deflate) compression of image data, allowing for reduced storage size.
- Fixes support for ATI1N and ATI2N, and adds support for BC7

It can be ripped from VTFLib fork created by P2CE developers
https://github.com/ChaosInitiative/VTFLib

**Comment by nillerusr** [comment]
@SanyaSho  ati1n and ati2n is useless, wtf. Are any mods still using it?

**Comment by SanyaSho** [comment]
> @SanyaSho ati1n and ati2n is useless, wtf. Are any mods still using it?

i think no, but compression might be helpful
