### ISSUE TITLE
64 bit failed compiling

### ISSUE THREAD

**Issue by David770725** [nillerusr/source-engine#195]
what version of clang that fix "cast from pointer to smaller type 'unsigned int' loses information" ???

**Comment by nillerusr** [comment]
Please, send full build log

**Comment by David770725** [comment]
waf configure was fine but the compiler says  :
game/shared/physics_main_shared.cpp:14:
../game/shared/entitydatainstantiator.h:118:10: error: cast from pointer to smaller type 'unsigned int' loses information
                return (unsigned int)src.key;

**Comment by David770725** [comment]
![Screenshot from 2023-02-17 16-55-05](https://user-images.githubusercontent.com/73972464/219612459-895e2003-1eb2-4179-820d-12a3cce90384.png)

**Comment by nillerusr** [comment]
@David770725 that was fixed in latest master branch.
Do `git pull` and rerun configure with build

**Comment by nillerusr** [comment]
nice
