### ISSUE TITLE
missing libraries

### ISSUE THREAD

**Issue by RjGunner111** [nillerusr/source-engine#197]
when i attempted to build the solution, i get this log:
Active code page: 1252
Using python
Setting top to                                          : C:\Users\rjkum\Downloads\source-engine-master\source-engine-master
Setting out to                                          : C:\Users\rjkum\Downloads\source-engine-master\source-engine-master\build
Build type                                              : debug
LTO build                                               : no
PolyOpt build                                           : no
Checking for 'msvc' (C compiler)                        : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX86\x86\CL.exe
Target OS                                               : win32
Target CPU                                              : x86
Target binfmt                                           : pe
Checking for 'msvc' (C++ compiler)                      : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX86\x86\CL.exe
Target OS                                               : win32
Target CPU                                              : x86
Target binfmt                                           : pe
Checking for program 'git'                              : C:\Program Files\Git\cmd\git.exe
Checking git hash                                       : no
WARNING: will build engine for 32-bit target
Checking if 'msvc' can target 32-bit                    : yes
Checking for library libz                               : not found
The configuration failed

i tried to build debug application

**Comment by RjGunner111** [comment]
fixed it actually closing it

**Comment by ipluxteamx** [comment]
> fixed it actually closing it

how did you fix it

**Comment by GreMirid** [comment]
git clone --recursive --depth 1
