### ISSUE TITLE
Build Configure is failed

### ISSUE THREAD

**Issue by L0w1y** [nillerusr/source-engine#20]
➜  source-engine git:(master) ./waf configure -T debug
Setting top to                                          : /home/desktop/Рабочий стол/source/srceng-android/source-engine 
Setting out to                                          : /home/desktop/Рабочий стол/source/srceng-android/source-engine/build 
Checking for 'gcc' (C compiler)                         : /usr/bin/gcc 
Target OS                                               : linux 
Target CPU                                              : x86_64 
Target binfmt                                           : elf 
Checking for 'g++' (C++ compiler)                       : /usr/bin/g++ 
Target OS                                               : linux 
Target CPU                                              : x86_64 
Target binfmt                                           : elf 
Checking for program 'git'                              : /usr/bin/git 
Checking git hash                                       : 2c6669f5 
Checking for program 'strip'                            : /usr/bin/strip 
Checking for program 'objcopy'                          : /usr/bin/objcopy 
WARNING: will build engine for 32-bit target
Checking if 'gcc' can target 32-bit                     : no 
...trying with additional flags                         : no 
Compiler can't create 32-bit code!
(complete log in /home/desktop/Рабочий стол/source/srceng-android/source-engine/build/config.log)
➜  source-engine git:(master)

**Comment by kkw070504** [comment]
You should use gcc:i386
