### ISSUE TITLE
[Android] How build apk ? 

### ISSUE THREAD

**Issue by LakoMoor** [nillerusr/source-engine#204]
i need [srceng-android](https://github.com/nillerusr/srceng-android) ? 

I use:
`python waf configure -T release --togles --android=armeabi-v7a-hard,4.9,21 --prefix=../out`
and
`python waf build`

This build folder (it's not ../out)
![image](https://user-images.githubusercontent.com/44299427/221057508-55a5deda-fe58-4e85-8f62-f32c789a53d7.png)

Linux distro: [Manjaro](https://manjaro.org/)

**Comment by steadyfield** [comment]
It seems that the source engine Android laucher is non-public closed-source proprietary. However the binary libs are open-source. 
For Android, this repo can only build the binary libs (.so files). You need to build the Android launcher apk yourself?

**Comment by LakoMoor** [comment]
> It seems that the source engine Android laucher is non-public closed-source proprietary. However the binary libs are open-source which is the main game content and is this repo. For Android, this repo can only build the binary libs (.so files). You need to write and build the Android launcher apk yourself? The old port Android launcher seems open source, and you can write the new port Android launcher based on it?

I think about this. But [srceng-android](https://github.com/nillerusr/srceng-android) don't have any docs for build (about version android SDK and other)...

**Comment by DionKill** [comment]
i would love to know this myself, as there are no builds on the release page, and the only ones u can find are on weird discord servers... not installing that.

**Comment by GuestSneezeOSDev** [comment]
> > It seems that the source engine Android laucher is non-public closed-source proprietary. However the binary libs are open-source which is the main game content and is this repo. For Android, this repo can only build the binary libs (.so files). You need to write and build the Android launcher apk yourself? The old port Android launcher seems open source, and you can write the new port Android launcher based on it?
> 
> I think about this. But [srceng-android](https://github.com/nillerusr/srceng-android) don't have any docs for build (about version android SDK and other)...

Please Do some reaserch before creating issues: https://arumoon.github.io/source-engine-docs/

**Comment by ItzVladik** [comment]
> > It seems that the source engine Android laucher is non-public closed-source proprietary. However the binary libs are open-source which is the main game content and is this repo. For Android, this repo can only build the binary libs (.so files). You need to write and build the Android launcher apk yourself? The old port Android launcher seems open source, and you can write the new port Android launcher based on it?
> 
> I think about this. But [srceng-android](https://github.com/nillerusr/srceng-android) don't have any docs for build (about version android SDK and other)...

this launcher is outdated, so if you want to build mod, you can use https://github.com/nillerusr/srceng-mod-launcher, and also you need build engine with clang-11 as mentioned in wiki
