### ISSUE TITLE
32bit build font problem 

### ISSUE THREAD

**Issue by David770725** [nillerusr/source-engine#207]
![Screenshot_2023-03-01-23-30-14-411_com valvesoftware source](https://user-images.githubusercontent.com/73972464/222201877-3bb77bea-cf3d-4349-82be-34fc34b752ae.jpg)
![Screenshot_2023-03-01-23-30-09-160_com valvesoftware source](https://user-images.githubusercontent.com/73972464/222201924-87efec19-d1cd-48ee-8db9-a5558332d0e4.jpg)

**Comment by David770725** [comment]
Only happened on armeabi-v7a

**Comment by nillerusr** [comment]
@David770725 why do you need your own engine build?

**Comment by David770725** [comment]
> @David770725 why do you need your own engine build?

I didn't, i only rebuild and turns out the fonts are messed up, how can I fix it?

**Comment by David770725** [comment]
I guess it's from the client that i use, if that so what things do i need to change?

**Comment by David770725** [comment]
I fixed it
