### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by L0w1y** [nillerusr/source-engine#21]
Waf: Leaving directory `/home/desktop/Рабочий стол/source/srceng-android/source-engine/build'
Build failed
 -> task in 'vstdlib' failed with exit status 1 (run with -v to display more information)
➜  source-engine git:(master) 

//config log file is here
https://github.com/L0w1y/src-engine-build/blob/main/config.log

**Comment by JusicP** [comment]
Leave here compilation log
`./waf build > output`

**Comment by L0w1y** [comment]
output is here:
https://github.com/L0w1y/src-build-output/blob/main/output

**Comment by L0w1y** [comment]
> Leave here compilation log `./waf build > output
[output.txt](https://github.com/nillerusr/source-engine/files/7270936/output.txt)

**Comment by ItzVladik** [comment]
I have similar problem

**Comment by nillerusr** [comment]
/home/desktop/рабочий стол

Лаадно
