### ISSUE TITLE
Portal 2 support

### ISSUE THREAD

**Issue by ezamelczyk** [nillerusr/source-engine#213]
Hi. Is this engine going to support Portal 2 as well in the future?

**Comment by aem111607** [comment]
Portal 2 uses a modified version of the source engine, which this isn't iirc

**Comment by Er2ch** [comment]
Portal 2 have some code which isn't leaked as for now and requires so many work such as Valve's VScript, scripted main menu from Alien Swarm, monitors (such as in lobby in co-op), personality core and so many other things
