### ISSUE TITLE
Build Failed (macOS Arm / AArch64)

### ISSUE THREAD

**Issue by isametry** [nillerusr/source-engine#214]
Running

`python3 ./waf configure --64bits -T release`

fails with 

[log 2023-03-14.txt](https://github.com/nillerusr/source-engine/files/10974099/log.2023-03-14.txt)

Am I doing something wrong? Do I need a different waf config for Apple Silicon than what I used?

**Comment by MaddTheSane** [comment]
You need to link to libiconv.

**Comment by isametry** [comment]
Sorry, could you elaborate a bit? I’m kinda new to a lot of this… Thanks!

**Comment by ege-del** [comment]
Looks like you are missing the library "libiconv" you have to install it with a package manager.
notice error message starts with "ld:" meaning it comes from command responsible for linking object files

**Comment by isametry** [comment]
@ege-del Thanks! Okay so with the help of #179, I managed to get a successful build. 

Now if I may have another, even more rookie question: How do I actually _run this_? This was my config: `python3 ./waf configure --64bits -T release  --build-games=hl2 --prefix=SteamLibrary/steamapps/common/Half-Life\ 2
`

I see `source-engine-master/build/launcher_main/hl2_launcher`, is that what I need to run? What is the next step?

**Comment by isametry** [comment]
Nevermind, got it to work. That question was probably off-topic for this repo anyway… Thanks again!
