### ISSUE TITLE
build issue (MacOS ARM)

### ISSUE THREAD

**Issue by yungmilky** [nillerusr/source-engine#217]
i followed all the steps and when i try and do _python3 ./waf configure --64bits -T release_ it returns an error _can't open file '/Users/yungmilky/./waf': [Errno 2] No such file or directory_ and i cant figure out what i did wrong

**Comment by JRiess7** [comment]
i reinstalled both xcode and homebrew and im still having this issue

**Comment by shinra-electric** [comment]
try without the `./` in front of waf: 

`python3 waf configure -T release --64bits —build-game=[whatever game you are building]`
