### ISSUE TITLE
Build issues on Raspberry Pi OS

### ISSUE THREAD

**Issue by CreeperCrafter979** [nillerusr/source-engine#22]
After installing SDL2 and the dev versions of some other programs, I was able to successfully run the './waf configure -T debug' terminal command on my Raspberry Pi 400 running Raspberry Pi OS, giving the following config.log file that can be found [here](https://github.com/CreeperCrafter979/source-engine-debug/blob/main/config.log). However, subsequently running 'sudo ./waf build > output.txt' would result in the line "Build failed
 -> task in 'tier2' failed with exit status 1 (run with -v to display more information)" repeated four times and [this file](https://github.com/CreeperCrafter979/source-engine-debug/blob/main/output.txt), or [these errors](https://github.com/CreeperCrafter979/source-engine-debug/blob/main/errorWithDashV.txt) if running the command with the -v parameter.

How would I fix this build error and ones I'll inevitably run into after?

**Comment by CreeperCrafter979** [comment]
Is there any way to configure and build without waf? I'd like to experiment with some of the compiler flags, but the waf configuration will often detect anything I try to edit in the root wscript file and'll cease progress.

**Comment by nn15** [comment]
所以可以在rpi上运行吗？

**Comment by CreeperCrafter979** [comment]
@nn15 No, it's not compiling everything and therefore not running on the raspberry pi.

**Comment by CreeperCrafter979** [comment]
I decided to try compiling again with the newest version of Raspberry Pi OS and found that the build process will no longer exit with an error code, but will instead just freeze (the first one being 100/2188 tier2/tier2.cpp). I learned a little about g++ and figured I might be able to manually compile all of the files that would end up freezing the build process, but g++ would always complain about a header file missing. I searched everything with the key *.h and sure enough, not a single header file came up. Is there any way to either ignore or recreate the header files needed?

**Comment by Nealsbo** [comment]
@CreeperCrafter979 It is not a freeze, it is building or trying to build, actually. After about 15 min of that I got note message with thousands of lines that contain "sse2neon.h" code. Seems like the problem here is related to sse2neon and old gcc, not sure, take a look at this [https://github.com/DLTcollab/sse2neon/issues/524](https://github.com/DLTcollab/sse2neon/issues/524)

**Comment by nillerusr** [comment]
Outdated

**Comment by coderamen666** [comment]
I'm facing this exact issue and need help in building this repository on a raspberry pi
