### ISSUE TITLE
[macOS] Broken menu UI

### ISSUE THREAD

**Issue by fluorescentkosherperson** [nillerusr/source-engine#226]
I built HL2 and replaced the compiled binaries of the game in the game files, downloaded from Steam, and the menu got broken, while the gameplay and HEV UI is completely fine. If I replace only the hl2_launcher in files downloaded from Steam (without client and server dylibs) the menu UI is working perfectly.

macOS 13.0 Ventura, MacBook Pro 2015 13"

<img width="1280" alt="зламаний інтерфейс" src="https://user-images.githubusercontent.com/128886078/229295434-9fbc099e-f3a4-47ca-b57d-afa5495046e6.png">

**Comment by SanyaSho** [comment]
YouForgetToCopyOrCopyAndPastePlatformFolder

**Comment by fluorescentkosherperson** [comment]
God bless you ❤️
