### ISSUE TITLE
[Question] how would i build an ARM64 SRCDS tf2 dedicated server?

### ISSUE THREAD

**Issue by yaktoma2007** [nillerusr/source-engine#229]
how would i build an ARM64 SRCDS tf2 dedicated server? Thanks in advance!

**Comment by SanyaSho** [comment]
![tbh_grunt](https://user-images.githubusercontent.com/68691958/230639460-f4f259c7-acc5-4207-a377-ec811d3fd820.png)

**Comment by stephen-cusi** [comment]
```python
print "Bruh"
```

**Comment by yaktoma2007** [comment]
i meant dependency and build-argument wise. there's no documentation for building for and on arm platforms.

**Comment by stephen-cusi** [comment]
> i meant dependency and build-argument wise. there's no documentation for building for and on arm platforms.

Similar to x86
