### ISSUE TITLE
[Wiki] Add documentation for building on and for ARM(64) Linux/BSD platforms.

### ISSUE THREAD

**Issue by yaktoma2007** [nillerusr/source-engine#231]
Dependency and build-argument wise. there's no documentation for building for and on arm platforms.

**Comment by yaktoma2007** [comment]
extra context: you cannot run $PACKAGE_NAME:i386 on arm/arm64 linux platforms, let alone use it for build dependencies. even installing these on arm(64) is a nightmare. the package names of their repective architecture counterparts need to be added.

**Comment by AruMoon** [comment]
On 64 arm machine you can install $PACKAGE_NAME:armhf for 32 bit package
