### ISSUE TITLE
Something with libraries

### ISSUE THREAD

**Issue by qveezzx** [nillerusr/source-engine#233]
PS C:\...\...\...\source-engine-master> ./waf configure -T release
Active code page: 1252
Using python
Setting top to                                          : C:\Users\Oliwier\Desktop\mw2\source-engine-master
Setting out to                                          : C:\Users\Oliwier\Desktop\mw2\source-engine-master\build
Build type                                              : release
LTO build                                               : no
PolyOpt build                                           : no
Checking for 'msvc' (C compiler)                        : C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX86\x86\CL.exe
Target OS                                               : win32
Target CPU                                              : x86
Target binfmt                                           : pe
Checking for 'msvc' (C++ compiler)                      : C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX86\x86\CL.exe
Target OS                                               : win32
Target CPU                                              : x86
Target binfmt                                           : pe
Checking for program 'git'                              : C:\Program Files\Git\cmd\git.exe
Checking git hash                                       : v1.2.13-dirty
WARNING: will build engine for 32-bit target
Checking if 'msvc' can target 32-bit                    : yes
Checking for library libz                               : not found
The configuration failed
(complete log in C:\...\...\...\source-engine-master\build\config.log)

**Comment by stephen-cusi** [comment]
git submodule init&&git submodule update
