### ISSUE TITLE
[macOS] waflib.Errors.WafError: Could not install the file '/bin/libdatacache.dylib'

### ISSUE THREAD

**Issue by CrimsonSquadron** [nillerusr/source-engine#236]
How do I fix this error while running ./waf install for macos.
waflib.Errors.WafError: Could not install the file '/bin/libdatacache.dylib'

Screenshot attached below
![Screenshot 2023-04-14 at 17 38 07](https://user-images.githubusercontent.com/42253757/232166115-04ba18ac-14be-49cd-b9c8-cb7f83769b64.png)

**Comment by stephen-cusi** [comment]
sudo ./waf install

**Comment by CrimsonSquadron** [comment]
Still failed

**Comment by CrimsonSquadron** [comment]
Same error

**Comment by stephen-cusi** [comment]
> Same error

Copy out all the finished builds and install them manually

**Comment by CrimsonSquadron** [comment]
> > Same error
> 
> Copy out all the finished builds and install them manually

I'll try

**Comment by CrimsonSquadron** [comment]
Where do I paste the files?

**Comment by stephen-cusi** [comment]
>

You can paste it to any folder, copy *.dylib to the bin folder, and the launcher to the directory where the bin folder is located

**Comment by CrimsonSquadron** [comment]
Ok It's done. How do I run the game?

**Comment by CrimsonSquadron** [comment]
I'm going to recompile the Engine and try from step 1

**Comment by stephen-cusi** [comment]
> I will recompile the engine and try from step 1.

Are you using a Mac with an arm chip?

**Comment by kenyerman** [comment]
what was the solution?
