### ISSUE TITLE
[macOS] Can't run the game after building it 

### ISSUE THREAD

**Issue by CrimsonSquadron** [nillerusr/source-engine#237]
I'm on a Apple M1 Macbook Pro 13"

After I went through the installation process and I dragged and dropped the hl2 folder that was built from the repository. I dragged and dropped the hl2_launcher in the terminal I got this error.

dlopen(bin/liblauncher.dylib, 0x0002): tried: 'bin/liblauncher.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSbin/liblauncher.dylib' (no such file), '/usr/lib/bin/liblauncher.dylib' (no such file, not in dyld cache), 'bin/liblauncher.dylib' (no such file)
Failed to load the launcher
dlopen(bin/launcher.dylib, 0x0002): tried: 'bin/launcher.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSbin/launcher.dylib' (no such file), '/usr/lib/bin/launcher.dylib' (no such file, not in dyld cache), 'bin/launcher.dylib' (no such file)
Failed to load the launcher

**Comment by CrimsonSquadron** [comment]
> Did you use: python3 waf install --destdir='' ?

No I will try reinstalling it and see if that helps

**Comment by CrimsonSquadron** [comment]
no dice

**Comment by nillerusr** [comment]
@CrimsonSquadron try run with DYLD_LIBRARY_PATH=bin/

**Comment by Spritzerland** [comment]
This worked for me: https://jameshug.notion.site/Guide-to-Installing-Half-Life-2-Using-Source-Engine-on-macOS-9fa5ffc910f5454ab0f0e5da2a9e5b9f

**Comment by CrimsonSquadron** [comment]
Nothing. I do better with a video tutorial. Can someone redirect me there?

**Comment by CrimsonSquadron** [comment]
Success I got the games running! I followed a guide on reddit. https://www.reddit.com/r/macgaming/comments/11qrqil/halflife_2_source_engine_running_natively_on/
