### ISSUE TITLE
Possible to build for Lost Coast?

### ISSUE THREAD

**Issue by palmerj** [nillerusr/source-engine#245]
Is it possible to build this engine to play Lost Coast?

**Comment by stephen-cusi** [comment]
/

> Is it possible to build this engine to play Lost Coast?

Is it okay to default to hl2?

**Comment by TheKingFireS** [comment]
Nope, you don't need to build libs for this game. Lost Coast use vanilla HL2 libs. just run it with "./hl2_launcher -game lostcoast" or  ".\hl2_launcher.exe -game lostcoast"

**Comment by stephen-cusi** [comment]
> 当我在 MacOS Apple Silicon 上运行时，`./hl2_launcher -game lostcoast`我得到：引擎错误：“无法加载库客户端。尝试重新启动。如果这不起作用，请验证缓存。”
> 
> 但是，如果我复制`hl2/bin/libclient.dylib`并`hl2/bin/libserver.dylib`进入`lostcoast/bin/`游戏，现在就可以了。



> When I run `./hl2_launcher -game lostcoast` on MacOS Apple Silicon I get: Engine Error: "Could not load library client. Try restarting. If that doesn't work, verify the cache."
> 
> However if I copy `hl2/bin/libclient.dylib` and `hl2/bin/libserver.dylib` into `lostcoast/bin/` the game now works.

Because the original DLL was intended for 86

**Comment by stephen-cusi** [comment]
no












Baby’s&nbsp;Q
***@***.***

北京同仁堂
抓药
1000000000
.122&nbsp;turlnap

---Original---
From: "Jeremy ***@***.***&gt;
Date: Mon, May 1, 2023 17:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nillerusr/source-engine] Possible to build for Lost Coast?(Issue #245)




 
Do you mean the install only works on x86, and the ARM64/Apple Silicon install progress needs to be improved?

**Comment by TheKingFireS** [comment]
Did you compiled hl2 libs for arm?

**Comment by TheKingFireS** [comment]
And no, I didn't use Macos or Mac arm.

**Comment by SanyaSho** [comment]
if u really need to build lostcoast, use that VPCs and add it into wscrips

[lostcoast_vpc.zip](https://github.com/nillerusr/source-engine/files/11370499/lostcoast_vpc.zip)
