### ISSUE TITLE
Can't run hl2_launcher.exe

### ISSUE THREAD

**Issue by Searchstars** [nillerusr/source-engine#261]
I ran the following commands:
`.\waf.bat configure -T debug --64bits`
`.\waf.bat build`
`.\waf.bat install --destdir="/ins_dest"`

Then I try to run `hl2_launcher.exe`, it reports an error: "Assertion Failed: ctx.m_eAction == k_ECatchAndWriteMiniDumpAbort"
![图片](https://github.com/nillerusr/source-engine/assets/47274115/34dac974-8a82-40da-bdf7-9fb52530158e)
If I try to close the window directly, it pops up again: "CTSListBase: Misaligned list"
![图片](https://github.com/nillerusr/source-engine/assets/47274115/c195a56c-9ad6-482a-a145-7d49d0fc4477)

**Comment by Er2ch** [comment]
try release instead of debug, there is just so many funny asserts that aren't fixed yet
