### ISSUE TITLE
libraries not working

### ISSUE THREAD

**Issue by Siomek101** [nillerusr/source-engine#262]
I tried to configure but it didnt work

> PS S:\source\source-engine> .\waf.bat configure -T debug --64bits --prefix "S:\source\jbmod"
> Active code page: 1252
> Using python
> Setting top to                                          : S:\source\source-engine
> Setting out to                                          : S:\source\source-engine\build
> Build type                                              : debug
> LTO build                                               : no
> PolyOpt build                                           : no
> Checking for 'msvc' (C compiler)                        : C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\CL.exe
> Target OS                                               : win32
> Target CPU                                              : amd64
> Target binfmt                                           : pe
> Checking for 'msvc' (C++ compiler)                      : C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\CL.exe
> Target OS                                               : win32
> Target CPU                                              : amd64
> Target binfmt                                           : pe
> Checking for program 'git'                              : D:\Aplikacje\Git\cmd\git.exe
> Checking git hash                                       : 0235b1e
> Checking for library libz                               : not found
> The configuration failed
> (complete log in S:\source\source-engine\build\config.log)

and i checked and i have all libraries

**Comment by Siomek101** [comment]
-_-
please if you know what to do message me, not spam random questions

**Comment by nillerusr** [comment]
send S:\source\source-engine\build\config.log

**Comment by Siomek101** [comment]
[config.log](https://github.com/nillerusr/source-engine/files/11789591/config.log)

**Comment by Siomek101** [comment]
> See: #233

did you read what i said? 
> and i checked and i have all libraries
thats not the fix.

**Comment by nillerusr** [comment]
stale
