### ISSUE TITLE
Pink and Green Lighting Bug (Episode 2 RPI400 64-Bit Build)

### ISSUE THREAD

**Issue by MrPikachu-The-Madman** [nillerusr/source-engine#263]
Found on my Raspberry Pi 400 that some maps in episode 2 have a bug causing the lightning to turn Pink and Green.
![2023-06-12-212741_1280x720_scrot](https://github.com/nillerusr/source-engine/assets/103082659/6b676090-bd86-4f2e-ad1b-8a5e04cb0064)

Not exactly sure why this might be occurring, but I have a screenshot, logs from the terminal and console, and the customized autoexe.cfg file I use at startup.
(this is just loading the main menu and an affected background map.)

[console_log.txt](https://github.com/nillerusr/source-engine/files/11730098/console_log.txt)

[terminal_log.txt](https://github.com/nillerusr/source-engine/files/11730110/terminal_log.txt)

[autoexec.cfg.txt](https://github.com/nillerusr/source-engine/files/11730111/autoexec.cfg.txt)

**Comment by SanyaSho** [comment]
**Fix:** `mat_colorcorrection** 0`

**Comment by nillerusr** [comment]
Same as #137
