### ISSUE TITLE
[macos] Build failed vstdlib

### ISSUE THREAD

**Issue by mSapik** [nillerusr/source-engine#264]
MacOS 13.4, XCode 14.3.1

python3 ./waf configure -8 -T release

```
Build failed
 -> task in 'vstdlib' failed with exit status 1: 
	{task 4717586000: cxxshlib coroutine.cpp.43.o,cvar.cpp.43.o,jobthread.cpp.43.o,KeyValuesSystem.cpp.43.o,random.cpp.43.o,vcover.cpp.43.o,
memoverride.cpp.43.o -> libvstdlib.dylib}
['/usr/bin/clang++', '-fvisibility=hidden', '-pipe', '-fPIC', '-L/Users/sapik/Code/source-engine-master/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-framework', 'CoreServices', '-dynamiclib', 'vstdlib/coroutine.cpp.43.o', 'vstdlib/cvar.cpp.43.o', 'vstdlib/jobthread.cpp.43.o', 'vstdlib/KeyValuesSystem.cpp.43.o', 'vstdlib/random.cpp.43.o', 'vstdlib/vcover.cpp.43.o', 'public/tier0/memoverride.cpp.43.o', '-o/Users/sapik/Code/source-engine-master/build/vstdlib/libvstdlib.dylib', '-Ltier1', '-ltier1', '-Ltier0', '-ltier0', '-ldl', '-lm', '-liconv']
```

**Comment by TheBrainScrambler** [comment]
Maybe try `python3 ./waf configure -8 -T release --disable-warns` ?

**Comment by stephen-cusi** [comment]
Add --disable-warns only alerts during build time and does not resolve build errors












Baby’s&nbsp;Q
***@***.***

白金小米&nbsp;inc.
打卡
1000000000
.122&nbsp;turlnap

---Original---
From: ***@***.***&gt;
Date: Mon, Jun 19, 2023 15:22 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [nillerusr/source-engine] [macos] Build failed vstdlib (Issue#264)




  
Maybe try python3 ./waf configure -8 -T release --disable-warns ?
  
Same error

**Comment by nillerusr** [comment]
@mSapik that's not compiler error, that's build status. Send full build log

**Comment by mSapik** [comment]
> @mSapik that's not compiler error, that's build status. Send full build log

`<waflib.extras.clang_compilation_database.ClangDbContext object at 0x105292d40>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x105292d40>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x105292d40>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x105292d40>
Build commands will be stored in build/compile_commands.json
Waf: Entering directory `/Users/sapik/Code/source-engine-1.16/build'
<waflib.Build.BuildContext object at 0x1052934c0>
<waflib.Build.BuildContext object at 0x1052934c0>
<waflib.Build.BuildContext object at 0x1052934c0>
<waflib.Build.BuildContext object at 0x1052934c0>
[  82/2206] Linking build/vstdlib/libvstdlib.dylib
09:00:52 runner ['/usr/bin/clang++', '-fvisibility=hidden', '-pipe', '-fPIC', '-L/Users/sapik/Code/source-engine-1.16/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-framework', 'CoreServices', '-dynamiclib', 'vstdlib/coroutine.cpp.43.o', 'vstdlib/cvar.cpp.43.o', 'vstdlib/jobthread.cpp.43.o', 'vstdlib/KeyValuesSystem.cpp.43.o', 'vstdlib/random.cpp.43.o', 'vstdlib/vcover.cpp.43.o', 'public/tier0/memoverride.cpp.43.o', '-o/Users/sapik/Code/source-engine-1.16/build/vstdlib/libvstdlib.dylib', '-Ltier1', '-ltier1', '-Ltier0', '-ltier0', '-ldl', '-lm', '-liconv']
[ 101/2206] Linking build/tier2/libtier2.a
[ 102/2206] Compiling mathlib/vmatrix.cpp
09:00:52 runner ['/usr/bin/clang++', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/sapik/Code/source-engine-1.16/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-std=c++11', '-fpermissive', '-w', '-Imathlib', '-I../mathlib', '-Icommon', '-I../common', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/mathlib', '-I../public/mathlib', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '-DMATHLIB_LIB=1', '../mathlib/vmatrix.cpp', '-c', '-o/Users/sapik/Code/source-engine-1.16/build/mathlib/vmatrix.cpp.24.o']
09:00:52 runner ['/opt/homebrew/opt/binutils/bin/ar', 'rcs', 'tier2/libtier2.a', 'tier2/beamsegdraw.cpp.33.o', 'tier2/defaultfilesystem.cpp.33.o', 'tier2/dmconnect.cpp.33.o', 'tier2/fileutils.cpp.33.o', 'tier2/keybindings.cpp.33.o', 'public/map_utils.cpp.33.o', 'public/materialsystem/MaterialSystemUtil.cpp.33.o', 'tier2/camerautils.cpp.33.o', 'tier2/meshutils.cpp.33.o', 'tier2/p4helpers.cpp.33.o', 'tier2/renderutils.cpp.33.o', 'tier2/riff.cpp.33.o', 'tier2/soundutils.cpp.33.o', 'tier2/tier2.cpp.33.o', 'tier2/util_init.cpp.33.o', 'tier2/utlstreambuffer.cpp.33.o', 'tier2/vconfig.cpp.33.o', 'tier2/keyvaluesmacros.cpp.33.o']
[ 103/2206] Compiling mathlib/vector.cpp
09:00:52 runner ['/usr/bin/clang++', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/sapik/Code/source-engine-1.16/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-std=c++11', '-fpermissive', '-w', '-Imathlib', '-I../mathlib', '-Icommon', '-I../common', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/mathlib', '-I../public/mathlib', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '-DMATHLIB_LIB=1', '../mathlib/vector.cpp', '-c', '-o/Users/sapik/Code/source-engine-1.16/build/mathlib/vector.cpp.24.o']
[ 104/2206] Compiling mathlib/simdvectormatrix.cpp
09:00:52 runner ['/usr/bin/clang++', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/sapik/Code/source-engine-1.16/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-std=c++11', '-fpermissive', '-w', '-Imathlib', '-I../mathlib', '-Icommon', '-I../common', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/mathlib', '-I../public/mathlib', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '-DMATHLIB_LIB=1', '../mathlib/simdvectormatrix.cpp', '-c', '-o/Users/sapik/Code/source-engine-1.16/build/mathlib/simdvectormatrix.cpp.24.o']
[ 105/2206] Compiling mathlib/spherical.cpp
09:00:52 runner ['/usr/bin/clang++', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/sapik/Code/source-engine-1.16/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-std=c++11', '-fpermissive', '-w', '-Imathlib', '-I../mathlib', '-Icommon', '-I../common', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/mathlib', '-I../public/mathlib', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '-DMATHLIB_LIB=1', '../mathlib/spherical.cpp', '-c', '-o/Users/sapik/Code/source-engine-1.16/build/mathlib/spherical.cpp.24.o']
[ 106/2206] Compiling mathlib/randsse.cpp
09:00:52 runner ['/usr/bin/clang++', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/sapik/Code/source-engine-1.16/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-std=c++11', '-fpermissive', '-w', '-Imathlib', '-I../mathlib', '-Icommon', '-I../common', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/mathlib', '-I../public/mathlib', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '-DMATHLIB_LIB=1', '../mathlib/randsse.cpp', '-c', '-o/Users/sapik/Code/source-engine-1.16/build/mathlib/randsse.cpp.24.o']
[ 107/2206] Compiling mathlib/quantize.cpp
09:00:52 runner ['/usr/bin/clang++', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/sapik/Code/source-engine-1.16/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-std=c++11', '-fpermissive', '-w', '-Imathlib', '-I../mathlib', '-Icommon', '-I../common', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/mathlib', '-I../public/mathlib', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '-DMATHLIB_LIB=1', '../mathlib/quantize.cpp', '-c', '-o/Users/sapik/Code/source-engine-1.16/build/mathlib/quantize.cpp.24.o']
[ 108/2206] Compiling mathlib/polyhedron.cpp
09:00:52 runner ['/usr/bin/clang++', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/sapik/Code/source-engine-1.16/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-std=c++11', '-fpermissive', '-w', '-Imathlib', '-I../mathlib', '-Icommon', '-I../common', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/mathlib', '-I../public/mathlib', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '-DMATHLIB_LIB=1', '../mathlib/polyhedron.cpp', '-c', '-o/Users/sapik/Code/source-engine-1.16/build/mathlib/polyhedron.cpp.24.o']
[ 109/2206] Compiling mathlib/imagequant.cpp
09:00:53 runner ['/usr/bin/clang++', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/sapik/Code/source-engine-1.16/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-std=c++11', '-fpermissive', '-w', '-Imathlib', '-I../mathlib', '-Icommon', '-I../common', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/mathlib', '-I../public/mathlib', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '-DMATHLIB_LIB=1', '../mathlib/imagequant.cpp', '-c', '-o/Users/sapik/Code/source-engine-1.16/build/mathlib/imagequant.cpp.24.o']
ld: warning: directory not found for option '-L/Users/sapik/Code/source-engine-1.16/lib/darwin/aarch64/'
ld: warning: ignoring file tier1/libtier1.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture arm64:
  "V_vsnprintfRet(char*, int, char const*, char*, bool*)", referenced from:
      CFmtStrN<256, false>::CFmtStrN(char const*, ...) in jobthread.cpp.43.o
      CFmtStrN<256, false>::CFmtStrN(char const*, ...) in KeyValuesSystem.cpp.43.o
  "ConVar_Register(int, IConCommandBaseAccessor*)", referenced from:
      CCvar::Connect(void* (*)(char const*, int*)) in cvar.cpp.43.o
  "ConVar_Unregister()", referenced from:
      CCvar::Disconnect() in cvar.cpp.43.o
  "Sys_GetFactoryThis()", referenced from:
      _VStdLib_GetICVarFactory in cvar.cpp.43.o
  "ConnectTier1Libraries(void* (**)(char const*, int*), int)", referenced from:
      CCvar::Connect(void* (*)(char const*, int*)) in cvar.cpp.43.o
  "ConVar_PrintDescription(ConCommandBase const*)", referenced from:
      CCvar::Find(CCommand const&) in cvar.cpp.43.o
  "DisconnectTier1Libraries()", referenced from:
      CCvar::Disconnect() in cvar.cpp.43.o
  "HashBlock(void const*, unsigned int)", referenced from:
      ThreadPoolTest::CCountJob::DoExecute() in jobthread.cpp.43.o
      ThreadPoolTest::CExecuteTestJob::DoExecute() in jobthread.cpp.43.o
  "V_stricmp(char const*, char const*)", referenced from:
      CCvar::RegisterConCommand(ConCommandBase*) in cvar.cpp.43.o
      CCvar::FindCommandBase(char const*) const in cvar.cpp.43.o
      CCvar::FindCommandBase(char const*) in cvar.cpp.43.o
      CCvar::RevertFlaggedConVars(int) in cvar.cpp.43.o
      CDefaultCvarQuery::QueryInterface(char const*) in cvar.cpp.43.o
  "V_stristr(char const*, char const*)", referenced from:
      CCvar::Find(CCommand const&) in cvar.cpp.43.o
  "V_strncpy(char*, char const*, int)", referenced from:
      CoroutineTestFunc(void*) in coroutine.cpp.43.o
      CFunctorJob::CFunctorJob(CFunctor*, char const*) in jobthread.cpp.43.o
      CJob::SetDescription(char const*) in jobthread.cpp.43.o
  "CUtlBuffer::PeekStringLength()", referenced from:
      CCvar::DisplayQueuedMessages() in cvar.cpp.43.o
  "CUtlBuffer::AddNullTermination(int)", referenced from:
      CCvar::ConsoleColorPrintf(Color const&, char const*, ...) const in cvar.cpp.43.o
      CUtlBuffer::PutChar(char) in cvar.cpp.43.o
  "CUtlBuffer::CheckArbitraryPeekGet(int, int&)", referenced from:
      void CUtlBuffer::GetType<int>(int&) in cvar.cpp.43.o
  "CUtlBuffer::Printf(char const*, ...)", referenced from:
      CCvar::ConsoleColorPrintf(Color const&, char const*, ...) const in cvar.cpp.43.o
  "CUtlBuffer::CheckGet(int)", referenced from:
      CCvar::DisplayQueuedMessages() in cvar.cpp.43.o
      void CUtlBuffer::GetType<int>(int&) in cvar.cpp.43.o
  "CUtlBuffer::CheckPut(int)", referenced from:
      CCvar::ConsoleColorPrintf(Color const&, char const*, ...) const in cvar.cpp.43.o
      CUtlBuffer::PutChar(char) in cvar.cpp.43.o
  "CUtlBuffer::GetString(char*, int)", referenced from:
      CCvar::DisplayQueuedMessages() in cvar.cpp.43.o
  "CUtlBuffer::PutString(char const*)", referenced from:
      CCvar::ConsoleColorPrintf(Color const&, char const*, ...) const in cvar.cpp.43.o
      CCvar::ConsolePrintf(char const*, ...) const in cvar.cpp.43.o
      CCvar::ConsoleDPrintf(char const*, ...) const in cvar.cpp.43.o
  "CUtlBuffer::CUtlBuffer(int, int, int)", referenced from:
      CCvar::CCvar() in cvar.cpp.43.o
  "CUtlString::Set(char const*)", referenced from:
      CKeyValuesSystem::InvalidateCacheForFile(char const*, char const*) in KeyValuesSystem.cpp.43.o
      CKeyValuesSystem::AddFileKeyValuesToCache(KeyValues const*, char const*, char const*) in KeyValuesSystem.cpp.43.o
      CUtlMap<CUtlString, KeyValues*, unsigned short>::Insert(CUtlString const&, KeyValues* const&) in KeyValuesSystem.cpp.43.o
      CKeyValuesSystem::LoadFileKeyValuesFromCache(KeyValues*, char const*, char const*, IBaseFileSystem*) const in KeyValuesSystem.cpp.43.o
  "CUtlString::Purge()", referenced from:
      CUtlVector<CCvar::QueuedConVarSet_t, CUtlMemory<CCvar::QueuedConVarSet_t, int>>::~CUtlVector() in cvar.cpp.43.o
      CCvar::ProcessQueuedMaterialThreadConVarSets() in cvar.cpp.43.o
      CCvar::~CCvar() in cvar.cpp.43.o
      CKeyValuesSystem::InvalidateCacheForFile(char const*, char const*) in KeyValuesSystem.cpp.43.o
      CKeyValuesSystem::AddFileKeyValuesToCache(KeyValues const*, char const*, char const*) in KeyValuesSystem.cpp.43.o
      CUtlMap<CUtlString, KeyValues*, unsigned short>::Insert(CUtlString const&, KeyValues* const&) in KeyValuesSystem.cpp.43.o
      CKeyValuesSystem::LoadFileKeyValuesFromCache(KeyValues*, char const*, char const*, IBaseFileSystem*) const in KeyValuesSystem.cpp.43.o
      ...
  "CUtlString::operator=(char const*)", referenced from:
      CCvar::QueueMaterialThreadSetValue(ConVar*, char const*) in cvar.cpp.43.o
  "CUtlString::operator=(CUtlString const&)", referenced from:
      CKeyValuesSystem::InvalidateCacheForFile(char const*, char const*) in KeyValuesSystem.cpp.43.o
      CUtlMap<CUtlString, KeyValues*, unsigned short>::Insert(CUtlString const&, KeyValues* const&) in KeyValuesSystem.cpp.43.o
      CKeyValuesSystem::LoadFileKeyValuesFromCache(KeyValues*, char const*, char const*, IBaseFileSystem*) const in KeyValuesSystem.cpp.43.o
  "ConCommand::CanAutoComplete()", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConCommand::AutoCompleteSuggest(char const*, CUtlVector<CUtlString, CUtlMemory<CUtlString, int>>&)", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConCommand::Dispatch(CCommand const&)", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConCommand::ConCommand(char const*, ICommandCallback*, char const*, int, ICommandCompletionCallback*)", referenced from:
      CCvar::CCvar() in cvar.cpp.43.o
  "ConCommand::~ConCommand()", referenced from:
      CCvar::~CCvar() in cvar.cpp.43.o
      CConCommandMemberAccessor<CCvar>::~CConCommandMemberAccessor() in cvar.cpp.43.o
      CConCommandMemberAccessor<CCvar>::~CConCommandMemberAccessor() in cvar.cpp.43.o
  "CMemoryStack::Init(unsigned int, unsigned int, unsigned int, unsigned int)", referenced from:
      CKeyValuesSystem::CKeyValuesSystem() in KeyValuesSystem.cpp.43.o
  "CMemoryStack::CommitTo(unsigned char*)", referenced from:
      CKeyValuesSystem::CKeyValuesSystem() in KeyValuesSystem.cpp.43.o
      CKeyValuesSystem::GetSymbolForString(char const*, bool) in KeyValuesSystem.cpp.43.o
  "CMemoryStack::CMemoryStack()", referenced from:
      CKeyValuesSystem::CKeyValuesSystem() in KeyValuesSystem.cpp.43.o
  "CMemoryStack::~CMemoryStack()", referenced from:
      CKeyValuesSystem::CKeyValuesSystem() in KeyValuesSystem.cpp.43.o
      CKeyValuesSystem::~CKeyValuesSystem() in KeyValuesSystem.cpp.43.o
  "InterfaceReg::InterfaceReg(void* (*)(), char const*)", referenced from:
      __GLOBAL__sub_I_cvar.cpp in cvar.cpp.43.o
  "CUtlMemoryPool::Alloc(unsigned long)", referenced from:
      CKeyValuesSystem::GetSymbolForString(char const*, bool) in KeyValuesSystem.cpp.43.o
  "CUtlMemoryPool::CUtlMemoryPool(int, int, int, char const*, int)", referenced from:
      CKeyValuesSystem::CKeyValuesSystem() in KeyValuesSystem.cpp.43.o
  "CUtlMemoryPool::~CUtlMemoryPool()", referenced from:
      CKeyValuesSystem::CKeyValuesSystem() in KeyValuesSystem.cpp.43.o
      CKeyValuesSystem::~CKeyValuesSystem() in KeyValuesSystem.cpp.43.o
  "ConCommandBase::CreateBase(char const*, char const*, int)", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConCommandBase::Init()", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConCommandBase::GetNext()", referenced from:
      CCvar::CCVarIteratorInternal::Next() in cvar.cpp.43.o
      CCvar::FindCommandBase(char const*) in cvar.cpp.43.o
  "ConCommandBase::AddFlags(int)", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConCommandBase::Shutdown()", referenced from:
      CCvar::~CCvar() in cvar.cpp.43.o
      CConCommandMemberAccessor<CCvar>::~CConCommandMemberAccessor() in cvar.cpp.43.o
      CConCommandMemberAccessor<CCvar>::~CConCommandMemberAccessor() in cvar.cpp.43.o
  "ConVar::Revert()", referenced from:
      CCvar::RevertFlaggedConVars(int) in cvar.cpp.43.o
  "KeyValues::deleteThis()", referenced from:
      CKeyValuesSystem::DoInvalidateCache() in KeyValuesSystem.cpp.43.o
      CKeyValuesSystem::InvalidateCacheForFile(char const*, char const*) in KeyValuesSystem.cpp.43.o
  "KeyValues::operator=(KeyValues const&)", referenced from:
      CKeyValuesSystem::LoadFileKeyValuesFromCache(KeyValues*, char const*, char const*, IBaseFileSystem*) const in KeyValuesSystem.cpp.43.o
  "CUtlString::Get() const", referenced from:
      CCvar::ProcessQueuedMaterialThreadConVarSets() in cvar.cpp.43.o
      UtlStringLessFunc(CUtlString const&, CUtlString const&) in KeyValuesSystem.cpp.43.o
      CUtlMap<CUtlString, KeyValues*, unsigned short>::Insert(CUtlString const&, KeyValues* const&) in KeyValuesSystem.cpp.43.o
  "ConCommand::IsCommand() const", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConCommandBase::GetHelpText() const", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConCommandBase::IsRegistered() const", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConCommandBase::GetDLLIdentifier() const", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConCommandBase::GetName() const", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConCommandBase::GetNext() const", referenced from:
      CCvar::FindCommandBase(char const*) const in cvar.cpp.43.o
      CCvar::RevertFlaggedConVars(int) in cvar.cpp.43.o
      CCvar::Find(CCommand const&) in cvar.cpp.43.o
  "ConCommandBase::IsFlagSet(int) const", referenced from:
      vtable for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
  "ConVar::GetDefault() const", referenced from:
      CCvar::RevertFlaggedConVars(int) in cvar.cpp.43.o
  "KeyValues::MakeCopy(bool) const", referenced from:
      CKeyValuesSystem::AddFileKeyValuesToCache(KeyValues const*, char const*, char const*) in KeyValuesSystem.cpp.43.o
  "typeinfo for ConCommand", referenced from:
      typeinfo for CConCommandMemberAccessor<CCvar> in cvar.cpp.43.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `/Users/sapik/Code/source-engine-1.16/build'
Build failed
 -> task in 'vstdlib' failed with exit status 1: 
	{task 4570892320: cxxshlib coroutine.cpp.43.o,cvar.cpp.43.o,jobthread.cpp.43.o,KeyValuesSystem.cpp.43.o,random.cpp.43.o,vcover.cpp.43.o,memoverride.cpp.43.o -> libvstdlib.dylib}
['/usr/bin/clang++', '-fvisibility=hidden', '-pipe', '-fPIC', '-L/Users/sapik/Code/source-engine-1.16/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-framework', 'CoreServices', '-dynamiclib', 'vstdlib/coroutine.cpp.43.o', 'vstdlib/cvar.cpp.43.o', 'vstdlib/jobthread.cpp.43.o', 'vstdlib/KeyValuesSystem.cpp.43.o', 'vstdlib/random.cpp.43.o', 'vstdlib/vcover.cpp.43.o', 'public/tier0/memoverride.cpp.43.o', '-o/Users/sapik/Code/source-engine-1.16/build/vstdlib/libvstdlib.dylib', '-Ltier1', '-ltier1', '-Ltier0', '-ltier0', '-ldl', '-lm', '-liconv']`

**Comment by stryaponoff** [comment]
Just remove `binutils` package (`brew rm binutils`) and reconfigure the project.

**Comment by mSapik** [comment]
> Just remove `binutils` package (`brew rm binutils`) and reconfigure the project.

Thank you, now build successfully!
