### ISSUE TITLE
failed to build on macos for aarch64

### ISSUE THREAD

**Issue by M00N-MAN** [nillerusr/source-engine#265]
Hello,

where to get source-engine/lib/darwin/aarch64/ files

```./waf configure -8 -T release 
Setting top to                                          : /Users/user/gits/source-engine 
Setting out to                                          : /Users/user/gits/source-engine/build 
Build type                                              : release 
LTO build                                               : no 
PolyOpt build                                           : no 
Checking for 'clang' (C compiler)                       : /opt/homebrew/opt/llvm/bin/clang 
Target OS                                               : darwin 
Target CPU                                              : aarch64 
Target binfmt                                           : mac-o 
Checking for 'clang++' (C++ compiler)                   : /opt/homebrew/opt/llvm/bin/clang++ 
Target OS                                               : darwin 
Target CPU                                              : aarch64 
Target binfmt                                           : mac-o 
Checking for program 'git'                              : /opt/homebrew/bin/git 
Checking git hash                                       : 0235b1ed-dirty 
Checking for program 'strip'                            : /usr/bin/strip 
Checking for required C flags                           : no ```


```
[1/2] Compiling build/.conf_check_39975d976bd9e351f9183af6113cabc7/test.c
['/opt/homebrew/opt/llvm/bin/clang', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/user/gits/source-engine/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNDEBUG', '-DGIT_COMMIT_HASH="0235b1ed-dirty"', '../test.c', '-c', '-o/Users/user/gits/source-engine/build/.conf_check_39975d976bd9e351f9183af6113cabc7/testbuild/test.c.1.o', '-I/opt/homebrew/opt/llvm/include/c++/v1/', '-I/opt/homebrew/opt/llvm/include', '-I/opt/homebrew/opt/libedit/include', '-I/opt/homebrew/opt/jpeg/include', '-I/opt/homebrew/opt/qt@5/include', '-I/opt/homebrew/opt/openal-soft/include', '-I/opt/homebrew/opt/curl/include']
err: clang-16: warning: argument unused during compilation: '-L/Users/user/gits/source-engine/lib/darwin/aarch64/' [-Wunused-command-line-argument]
[2/2] Linking build/.conf_check_39975d976bd9e351f9183af6113cabc7/testbuild/testprog
['/opt/homebrew/opt/llvm/bin/clang', '-fvisibility=hidden', '-pipe', '-fPIC', '-L/Users/user/gits/source-engine/lib/darwin/aarch64/', '-pthread', '-fsigned-char', 'test.c.1.o', '-o/Users/user/gits/source-engine/build/.conf_check_39975d976bd9e351f9183af6113cabc7/testbuild/testprog', '-L/Users/user/VulkanSDK/1.3.243.0//macOS/lib', '-L/opt/homebrew/opt/llvm/lib', '-L/Users/user/VulkanSDK/1.3.243.0//macOS/lib', '-L/opt/homebrew/opt/libedit/lib', '-L/opt/homebrew/opt/jpeg/lib', '-L/Users/user/VulkanSDK/1.3.243.0//macOS/lib', '-L/Users/user/VulkanSDK/1.3.243.0//macOS/lib', '-L/Users/user/VulkanSDK/1.3.243.0//macOS/lib', '-L/opt/homebrew/Cellar/python-tabulate/0.9.0/lib', '-L/opt/homebrew/opt/qt@5/lib', '-L/opt/homebrew/opt/openal-soft/lib', '-L/opt/homebrew/opt/bison/lib', '-L/opt/homebrew/opt/curl/lib']
err: ld: warning: directory not found for option '-L/Users/user/gits/source-engine/lib/darwin/aarch64/'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
    raise Errors.BuildError(self.producer.error)
```

this video says that current engine can be built for apple silicone
https://www.youtube.com/watch?v=mMuSXs0SF_g&ab_channel=JamesHughes

it points to https://jameshug.notion.site/Guide-to-Installing-Half-Life-2-Using-Source-Engine-on-macOS-9fa5ffc910f5454ab0f0e5da2a9e5b9f

which routes to this repo

**Comment by M00N-MAN** [comment]
@nillerusr could you please share which version of clang is not weird and should be used?)

**Comment by nillerusr** [comment]
no longer actual, fixed
