### ISSUE TITLE
When trying to run HL2 Deathmatch on m1, this error pops up 

### ISSUE THREAD

**Issue by 4193883-eng** [nillerusr/source-engine#270]
<img width="2560" alt="error" src="https://github.com/nillerusr/source-engine/assets/83756034/6499ddfc-2291-41fb-ba8e-7cca4d271f38">
So firstly i used this command: `python3 waf configure -T release --64bits --prefix='' --build-games=hl2mp`, then this: `python3 waf build`, and after this: `python3 waf install --destdir='/Volumes/Hello/hl1-source'`. After this i did this replaced bin folder that was already there with one that i built, replaced hl2_osx with hl2_launcher and renamed it to hl2_osx, and deleted everything from hl2mp/bin and copied the new files to hl2mp/bin

**Comment by usernameunavalible0** [comment]
you have to run the .sh file in your game dir instead of just running hl2_osx. Or else it wont correctly detect the dynamic libraries and you will get the error you posted here.
