### ISSUE TITLE
Counter-Strike: Source on Mac Pro M1 - Unable to Select Server and STEAM Certificate Length Error

### ISSUE THREAD

**Issue by cmer81** [nillerusr/source-engine#271]
Hello :) 

### Description:

I followed the procedure to play Counter-Strike: Source on my Mac Pro M1. The compilation process was successful using the following commands:

```
python3 waf configure -T release -8 --build-games=cstrike
python3 waf build
python3 waf install --destdir='~/Documents/Build folder/cstrike'
```
Afterward, I copied all the files to the correct locations and launched the game through Steam. The game launches successfully, but I am unable to select my favorite server on the main menu. Additionally, when I try to access a server from the console, I receive the following error message: "STEAM certificate length error!"

it's as if counter-strike wasn't authenticated with steam.

<img width="441" alt="error" src="https://github.com/nillerusr/source-engine/assets/5068536/416dadc4-d211-4da0-8d0d-880c50801245">

<img width="796" alt="Sans titre" src="https://github.com/nillerusr/source-engine/assets/5068536/acc3655f-bdc8-4b89-bff1-97329def33d1">

### Steps to Reproduce:

1. Install Counter-Strike: Source on a Mac Pro M1.
2. Compile the game using the commands mentioned above.
3. Copy the compiled files to their respective locations.
4. Launch the game through Steam.
5. Attempt to select a server from the main menu.
6. Try to access a favorite server from the console.

### Attachments:

[engine.log](https://github.com/nillerusr/source-engine/files/12099790/engine.log)

Regards,

**Comment by cmer81** [comment]
Without a resolution to this problem, I'm afraid I might have to give up on playing Counter-Strike Source. This would be really unfortunate, as this game represents a significant part of my leisure time and social engagement. I'm worried I might fall into a mundane routine and develop harmful habits, such as excessive drinking. :trollface:

So, I'm seeking your help to solve this issue. Any suggestion, advice, or direction would be greatly appreciated.

**Comment by TheKingFireS** [comment]
Pro tip: turn off your laptop.

**Comment by stephen-cusi** [comment]
[porting kit](https://www.portingkit.com/)

**Comment by nillerusr** [comment]
stale
