### ISSUE TITLE
No main menu GUI on cstrike OSX

### ISSUE THREAD

**Issue by PEPSIMANTR** [nillerusr/source-engine#289]
I just compiled for cstrike game on OSX, copied the output binaries to retail game but when I launch, there's no main menu GUI at all, only the background picture and the click sounds when I press buttons on the keyboard.
<img width="2048" alt="image" src="https://github.com/nillerusr/source-engine/assets/69170454/c770ebce-feea-4403-808e-d9c19a4ac8c1">

**Comment by TheKingFireS** [comment]
Pro tip: play it in your phone.

**Comment by denz8028** [comment]
copy vpk files mist_*.vpk from halflife 2 hl2 folder to css hl2 folder
