### ISSUE TITLE
build for linux questions

### ISSUE THREAD

**Issue by rox4d** [nillerusr/source-engine#300]
1. Is it possible to build (linux) engine for work via opengles api? adding  --togles  to WAF args, seems does`t make it use libGLESv2.so
2. currently trying to build with x86 (in a future want to try compare panfork with vendor`s rk3588 driver), and note that linux cpu level requirement looks too high - amd phenom2 unable to run release binaries:
~~~
diff -urN a/wscript b/wscript
--- a/wscript	2023-10-07 07:53:46.219680807 +0300
+++ b/wscript	2023-10-06 21:05:47.779029516 +0300
@@ -485,7 +485,10 @@
 
 		flags += ['-funwind-tables', '-g']
 	elif conf.env.COMPILER_CC != 'msvc' and conf.env.DEST_OS != 'darwin' and conf.env.DEST_CPU in ['x86', 'x86_64']:
-		flags += ['-march=core2']
+		if conf.env.DEST_CPU in ['x86_64']:
+			flags += ['-mcx16']
+		else :
+			flags += ['-msse2']
 
 	if conf.env.DEST_CPU in ['x86', 'x86_64']:
 		flags += ['-mfpmath=sse']
~~~
seems enough

**Comment by nillerusr** [comment]
1. `--togles´ option works on linux, of course. SDL2 should load libGLES
2. Okay, i will commit changes later

**Comment by rox4d** [comment]
> of course. SDL2 should load libGLES

Спасибо, пересобрал sdl - вроде заработало, по крайней мере, вывод поменялся:
~~~
OpenGL: AMD Radeon R9 M360 (verde, LLVM 14.0.6, DRM 3.27, 4.19.239) 4.6 (Compatibility Profile) Mesa 23.2.0-devel (git-171d316402) (4.6.0)
~~~
--togles :
~~~
GL_RENDERER="AMD Radeon R9 M360 (verde, LLVM 14.0.6, DRM 3.27, 4.19.239)" GL_VERSION="OpenGL ES 3.2 Mesa 23.2.0-devel (git-171d316402)" GL_VENDOR="AMD" (3.2.0)
~~~
А из голой консоли должно работать? (с EGL_PLATFORM=drm и SDL_VIDEODRIVER=kmsdrm) - у меня звук есть а в консоли только лог запуска и по ctrl+c прервать можно.

**Comment by nillerusr** [comment]
Насчет голой консоли не разбирался ни разу, не знаю.
