### ISSUE TITLE
MP games don't work on FreeBSD

### ISSUE THREAD

**Issue by alexax66** [nillerusr/source-engine#302]
I built this engine on FreeBSD 13.2 
All single games  works fine.
MP games  such as CS, DOD has error when connect to server:  
![image_2023-10-07_19-08-12](https://github.com/nillerusr/source-engine/assets/12674883/23b58181-7b34-4872-b763-4b45af0d63ce)

**Comment by nillerusr** [comment]
That's look like you loaded library client/server from singleplayer game in css.

**Comment by alexax66** [comment]
Yes, that's right, thank you!

**Comment by alexax66** [comment]
How can i build engine with mp games support ?

**Comment by alexax66** [comment]
I found solition:

```
./waf configure -T release -8 --build-games=cstrike
./waf build
```

**Comment by DJs3000** [comment]
hl2mp - Half-Life 2 Multiplayer
cstrike - CSS
Ещё можно указать префикс в корень папки с игрой --prefix="/path-to-root_hl2"

**Comment by alexax66** [comment]
Спсибо!!!

**Comment by DJs3000** [comment]
единственное не нужно ./waf build, делай так ./waf install
скрипт сам распараллелить компиляцию на все ядра и проинсталит по указанному префиксу.
