### ISSUE TITLE
проблема с css/css render problem

### ISSUE THREAD

**Issue by denz8028** [nillerusr/source-engine#304]
не отображается ничего в меню и артефакты на карте

![изображение](https://github.com/nillerusr/source-engine/assets/125301239/cf2a9aec-0a04-4e54-86ee-9be53e914973)
это главное меню.

![изображение](https://github.com/nillerusr/source-engine/assets/125301239/3d7ad62f-753f-4c10-9c4d-516ec60a4e53)
это выбор фракции.

![изображение](https://github.com/nillerusr/source-engine/assets/125301239/a78c43cb-363a-48b9-a9e9-1822f6f07c5e)
а вот так игра в целом.

пересборка в разные рендеры не помогает, не знаю что делать

[engine.log](https://github.com/nillerusr/source-engine/files/12885510/engine.log)
лог если надо, буду благодарен любой помощи

**Comment by DJs3000** [comment]
Сталкивался с такой же проблемой. Оказалось, что нужно вот это файлы взять от HL2
hl2_misc_000.vpk
hl2_misc_001.vpk
hl2_misc_002.vpk
hl2_misc_003.vpk
hl2_misc_dir.vpk
там 2 шейдера отличающихся и в будущем возможно это поправят. Вот вам ресурсы уже готовые для CSS:
https://disk.yandex.ru/d/DXnpvyOgRokZsA

**Comment by denz8028** [comment]
> Сталкивался с такой же проблемой. Оказалось, что нужно вот это файлы взять от HL2
> hl2_misc_000.vpk
> hl2_misc_001.vpk
> hl2_misc_002.vpk
> hl2_misc_003.vpk
> hl2_misc_dir.vpk
> там 2 шейдера отличающихся и в будущем возможно это поправят. 

Спасибо
