### ISSUE TITLE
не могу сделать кросс компиляцию для винды. mingw/cannot cross-compile for windows. mingw

### ISSUE THREAD

**Issue by denz8028** [nillerusr/source-engine#306]
Винды под рукой нет, а надо скомпилировать для друга что бы с ним играть.

Ошибка на стадии checking for required C flags
нет флагов, на общем компе с виндой без прав админа та же ситуация, visual studio поставить никак нельзя, с clang'ом та же проблема.

**Comment by DJs3000** [comment]
У меня есть архив, где скомпилены уже несколько игр на этом движке под винду и линь, может так будет проще, чтоб не мучить друга. CSS конечно же там есть и сразу ресурсы под все игры.
https://disk.yandex.ru/d/NqszEAO8lVfitQ

**Comment by denz8028** [comment]
> У меня есть архив, где скомпилены уже несколько игр на этом движке под винду и линь, может так будет проще, чтоб не мучить друга. CSS конечно же там есть и сразу ресурсы под все игры. https://disk.yandex.ru/d/NqszEAO8lVfitQ

спасииибо

**Comment by DJs3000** [comment]
Единственное призываю купить все эти игры в стиме, как это сделал я. Стоят они копейки, но это будет по честному.

**Comment by denz8028** [comment]
> У меня есть архив, где скомпилены уже несколько игр на этом движке под винду и линь, может так будет проще, чтоб не мучить друга. CSS конечно же там есть и сразу ресурсы под все игры. https://disk.yandex.ru/d/NqszEAO8lVfitQ

![photo_2023-10-15_21-24-51](https://github.com/nillerusr/source-engine/assets/125301239/9ef571f2-030f-4503-8f2b-a761b7305b24)

Ошибка с лаунчером по неизвестной причине

**Comment by denz8028** [comment]
> Единственное призываю купить все эти игры в стиме, как это сделал я. Стоят они копейки, но это будет по честному.

они у меня купленны ;) а в россии никак другу не купить, да и мне ему тоже

**Comment by DJs3000** [comment]
> > Единственное призываю купить все эти игры в стиме, как это сделал я. Стоят они копейки, но это будет по честному.
> 
> они у меня куплены ;) а в россии никак другу не купить, да и мне ему тоже

Я так же в РФ прекрасно покупаю пополняя стим через Qiwi. По поводу ошибки, может у него 32 битная система?

**Comment by denz8028** [comment]
> > > Единственное призываю купить все эти игры в стиме, как это сделал я. Стоят они копейки, но это будет по честному.
> > 
> > они у меня куплены ;) а в россии никак другу не купить, да и мне ему тоже
> 
> Я так же в РФ прекрасно покупаю пополняя стим через Qiwi. По поводу ошибки, может у него 32 битная система?

Он говорит что у него 64 бита

**Comment by DJs3000** [comment]
А он старовер? Почему 7ка)) я на 7ке не тестировал даже, собиралось на 10ке.

**Comment by denz8028** [comment]
> А он старовер? Почему 7ка)) я на 7ке не тестировал даже, собиралось на 10ке.

Он очень базовой юзает комп, максимум екзэшник открыть, жалуется на то что не может установить 10ку то что media creation tool не работает

**Comment by er2off** [comment]
хоть я и не пишу обычно в issue по-русски, но для mingw (в т.ч. llvm-mingw) нужны дополнительные патчи, я собрал движок им, но он падает

**Comment by denz8028** [comment]
> хоть я и не пишу обычно в issue по-русски, но для mingw (в т.ч. llvm-mingw) нужны дополнительные патчи, я собрал движок им, но он падает

Можешь пожалуйста поподробнее про патчи? Я хочу хотя бы просто скомпилировать не имея прав админа

**Comment by GreMirid** [comment]
> Можешь пожалуйста поподробнее про патчи? Я хочу хотя бы просто скомпилировать не имея прав админа

Каким образом не имея прав админа на системе (7ке тем более) в принципе подходить к теме программирования?

Тебе в любом случае придётся поставить компилятор (MSVC, GCC, MINGW, LCC и т.д.) и в любом случае это не будет поддерживаться на 7ке. 
Либо ставь VS 2013 и качай оригинальный лик, ведь компилируется он как раз таки под Win7 с MSVS 2013.

Лично сам использую компилятор MSVC 16.11 (19 студия) на 11й винде.
Пока что из мажорных багов - слегка поломанная физика, но не жалуюсь.

**Comment by denz8028** [comment]
> > Можешь пожалуйста поподробнее про патчи? Я хочу хотя бы просто скомпилировать не имея прав админа
> 
> Каким образом не имея прав админа на системе (7ке тем более) в принципе подходить к теме программирования?
> 
> Тебе в любом случае придётся поставить компилятор (MSVC, GCC, MINGW, LCC и т.д.) и в любом случае это не будет поддерживаться на 7ке. 
> Либо ставь VS 2013 и качай оригинальный лик, ведь компилируется он как раз таки под Win7 с MSVS 2013.
> 
> Лично сам использую компилятор MSVC 16.11 (19 студия) на 11й винде.
> Пока что из мажорных багов - слегка поломанная физика, но не жалуюсь.
> 

Msys2 и mingw ставятся без прав админа, msvc да - проблема, на 7ке mingw и msys2 работали вроде, ну есть вариант с общим ПК на 10ке, но нет прав админа, да, у меня есть ПК дома, но в том проблема что мне надо для друга, а у него 7ка.

**Comment by nillerusr** [comment]
Поддержку для MinGW делать не буду. Когда-нибудь попробую собрать с windows sdk и clang.
Если так хочется - жду pull request
