### ISSUE TITLE
How to launch built "game" ? (new here pls help)

### ISSUE THREAD

**Issue by marcikaa78** [nillerusr/source-engine#311]

**Comment by GreMirid** [comment]
What do you mean? 
If you want to start HL2 you need resources of HL2.

**Comment by AruMoon** [comment]
Add installation path via `--prefix=/path/to/half-life-2-root-folder` in waf configure
And use `./waf install` to build and install built binaries

**Comment by marcikaa78** [comment]
can is ask why u need the HL2 root folder? cannot you build a standalone game from this?

**Comment by AruMoon** [comment]
> can is ask why u need the HL2 root folder? cannot you build a standalone game from this?

No. Game resources are available only in Steam
Source Engine code doesn't contain any resources

**Comment by marcikaa78** [comment]
A

**Comment by marcikaa78** [comment]
Hi, installed successfully, but when I start hl2.exe the game starts, but basically nothing changes. Do I need to move the launcher (.exe file in "launcher_main" or "launcher" folder after build) to the HL2 root folder or Just leave anything as it is (and it will reflect changes i made in the code)?

P.S: im new to the source scene, sorry in im annoying :)

**Comment by stephen-cusi** [comment]
> Hi, installed successfully, but when I start hl2.exe the game starts, but basically nothing changes. Do I need to move the launcher (.exe file in "launcher_main" or "launcher" folder after build) to the HL2 root folder or Just leave anything as it is (and it will reflect changes i made in the code)?
> 
> P.S: im new to the source scene, sorry if im annoying :)

#304
This may help you

**Comment by marcikaa78** [comment]
Hi, installed successfully, but when I start hl2_launcher.exe I get video_quicktime.dll ThreadSleep error. One of this issues nillerusr commented "another invalid issue, delete steam binaries before installing ones compiled from this repo" I don't know what binaries to delete. I'm new btw.

**Comment by marcikaa78** [comment]
Hi, installed successfully, but when I start hl2_launcher.exe I get video_quicktime.dll ThreadSleep error. One of this issues nillerusr commented "another invalid issue, delete steam binaries before installing ones compiled from this repo" I don't know what binaries to delete. I'm new btw.

**Comment by stephen-cusi** [comment]
> Hi, installed successfully, but when I start hl2_launcher.exe I get video_quicktime.dll ThreadSleep error. One of this issues nillerusr commented "another invalid issue, delete steam binaries before installing ones compiled from this repo" I don't know what binaries to delete. I'm new btw.

delete bin/
rerun ./waf.bat install

**Comment by marcikaa78** [comment]
hi, thank you for writing this. the game is now running w/ modified source. but how to run hammer cause its missing from bin folder

**Comment by AruMoon** [comment]
> hi, thank you for writing this. the game is now running w/ modified source. but how to run/build hammer cause its missing from bin folder Edit: how to modify the hammer icon and splash?

There is no hammer in nillerusr's engine
