### ISSUE TITLE
[macOS] All games fail to launch after commit 90e2937 updating waf

### ISSUE THREAD

**Issue by shinra-electric** [nillerusr/source-engine#315]
Games won't launch after commit 90e2937: 
`update waf, enable gccdeps and msvcdeps`

The error message from terminal says:
```
Can't find module - engine.dylib
AppFramework : Unable to load module engine.dylib!
Unable to load interface VCvarQuery001 from engine.dylib
```

[HL2 Terminal Output.txt](https://github.com/nillerusr/source-engine/files/13464673/HL2.Terminal.Output.txt)

**Comment by shinra-electric** [comment]
It seems libengine.dylib is no longer built

**Comment by Elc3r** [comment]
I have the same problem before everything worked but now I have the same error, at least I know I'm not alone.

**Comment by er2off** [comment]
> It seems libengine.dylib is no longer built

lmao, cool waf upgrade

**Comment by Kizoky** [comment]
engine was commented out in wscript, just re-enable it
