### ISSUE TITLE
Build issues on Raspberry Pi

### ISSUE THREAD

**Issue by coderamen666** [nillerusr/source-engine#320]
Basically issue #22 is giving me problems and I don't know how people have resolved it. This repo is known to work on a raspberry pi. I just don't know how to achieve this.

**Comment by nillerusr** [comment]
Are you sure? Please, provide build log

**Comment by coderamen666** [comment]
I am sure but Ive got to fire up my pi to get the logs

**Comment by coderamen666** [comment]
The build is stuck on tier2/renderutils.cpp as of now. I am on 32-bit as well, which might be playing a role.

**Comment by nillerusr** [comment]
Well, that compiler version is used? Looks like compiler issue. Provide build/config.log

**Comment by coderamen666** [comment]
[config.log](https://github.com/nillerusr/source-engine/files/13663526/config.log)

**Comment by nillerusr** [comment]
Hmm
Try `CXXFLAGS='-march=armv7-a'` before ./waf configure
Like that: `CXXFLAGS='-march=armv7-a'  ./waf configure -T release

**Comment by coderamen666** [comment]
It's currently compiling rn. It didn't error out yet
