### ISSUE TITLE
[macOS] fails to build

### ISSUE THREAD

**Issue by Kurtjwest** [nillerusr/source-engine#326]
receiving the following error when trying to build on macOS Sonoma:

Build failed
 -> task in 'bitmap' failed with exit status 1: 
	{task 4408516672: cxx colorconversion.cpp -> colorconversion.cpp.1.o}
['/usr/bin/clang++', '-MMD', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/xxx/source-engine/lib/darwin/aarch64/', '-pthread', '-fsigned-char', '-std=c++11', '-fpermissive', '-Ibitmap', '-I../bitmap', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/tier1', '-I../public/tier1', '-Ithirdparty/stb', '-I../thirdparty/stb', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNO_MEMOVERRIDE_NEW_DELETE=1', '-DNDEBUG', '-DGIT_COMMIT_HASH="87150cc0"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '../bitmap/colorconversion.cpp', '-c', '-o/Users/xxx/source-engine/build/bitmap/colorconversion.cpp.1.o']

**Comment by nillerusr** [comment]
That's build status message, not compilation error.
Please provide a full build log.

**Comment by Yura97orel** [comment]
same thing
mainuser@Mains-MacBook-Pro source-engine % python3 waf build -v
Build commands will be stored in build/compile_commands.json
Waf: Entering directory `/Users/mainuser/source-engine/build'
[ 131/2274] Compiling bitmap/colorconversion.cpp
10:41:17 runner ['/usr/bin/clang++', '-MMD', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/mainuser/source-engine/lib/darwin/x86_64/', '-pthread', '-mfpmath=sse', '-std=c++11', '-fpermissive', '-Ibitmap', '-I../bitmap', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/tier1', '-I../public/tier1', '-Ithirdparty/stb', '-I../thirdparty/stb', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNO_MEMOVERRIDE_NEW_DELETE=1', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '../bitmap/colorconversion.cpp', '-c', '-o/Users/mainuser/source-engine/build/bitmap/colorconversion.cpp.1.o']
[ 163/2274] Compiling vgui2/src/vgui_key_translation.cpp
10:41:17 runner ['/usr/bin/clang++', '-MMD', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/mainuser/source-engine/lib/darwin/x86_64/', '-pthread', '-mfpmath=sse', '-std=c++11', '-fpermissive', '-Ivgui2/vgui_controls', '-I../vgui2/vgui_controls', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/tier1', '-I../public/tier1', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNO_MEMOVERRIDE_NEW_DELETE=1', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '../vgui2/src/vgui_key_translation.cpp', '-c', '-o/Users/mainuser/source-engine/build/vgui2/src/vgui_key_translation.cpp.37.o']
[ 164/2274] Compiling vgui2/vgui_controls/URLLabel.cpp
10:41:17 runner ['/usr/bin/clang++', '-MMD', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/mainuser/source-engine/lib/darwin/x86_64/', '-pthread', '-mfpmath=sse', '-std=c++11', '-fpermissive', '-Ivgui2/vgui_controls', '-I../vgui2/vgui_controls', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/tier1', '-I../public/tier1', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNO_MEMOVERRIDE_NEW_DELETE=1', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '../vgui2/vgui_controls/URLLabel.cpp', '-c', '-o/Users/mainuser/source-engine/build/vgui2/vgui_controls/URLLabel.cpp.37.o']
[ 165/2274] Compiling vgui2/vgui_controls/TreeViewListControl.cpp
10:41:17 runner ['/usr/bin/clang++', '-MMD', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/mainuser/source-engine/lib/darwin/x86_64/', '-pthread', '-mfpmath=sse', '-std=c++11', '-fpermissive', '-Ivgui2/vgui_controls', '-I../vgui2/vgui_controls', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/tier1', '-I../public/tier1', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNO_MEMOVERRIDE_NEW_DELETE=1', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '../vgui2/vgui_controls/TreeViewListControl.cpp', '-c', '-o/Users/mainuser/source-engine/build/vgui2/vgui_controls/TreeViewListControl.cpp.37.o']
clang: warning: argument unused during compilation: '-L/Users/mainuser/source-engine/lib/darwin/x86_64/' [-Wunused-command-line-argument]
../bitmap/colorconversion.cpp:29:10: fatal error: 'stb_dxt.h' file not found
#include "stb_dxt.h"
         ^~~~~~~~~~~
1 error generated.

clang: warning: argument unused during compilation: '-L/Users/mainuser/source-engine/lib/darwin/x86_64/' [-Wunused-command-line-argument]

clang: warning: argument unused during compilation: '-L/Users/mainuser/source-engine/lib/darwin/x86_64/' [-Wunused-command-line-argument]

clang: warning: argument unused during compilation: '-L/Users/mainuser/source-engine/lib/darwin/x86_64/' [-Wunused-command-line-argument]

Waf: Leaving directory `/Users/mainuser/source-engine/build'
Build failed
 -> task in 'bitmap' failed with exit status 1: 
	{task 4597402768: cxx colorconversion.cpp -> colorconversion.cpp.1.o}
['/usr/bin/clang++', '-MMD', '-fno-strict-aliasing', '-fvisibility=hidden', '-O2', '-funsafe-math-optimizations', '-ftree-vectorize', '-ffast-math', '-pipe', '-fPIC', '-L/Users/mainuser/source-engine/lib/darwin/x86_64/', '-pthread', '-mfpmath=sse', '-std=c++11', '-fpermissive', '-Ibitmap', '-I../bitmap', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/tier1', '-I../public/tier1', '-Ithirdparty/stb', '-I../thirdparty/stb', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DPLATFORM_64BITS=1', '-DOSX=1', '-D_OSX=1', '-DPOSIX=1', '-D_POSIX=1', '-DPLATFORM_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.dylib', '-DNO_MEMOVERRIDE_NEW_DELETE=1', '-DNDEBUG', '-DGIT_COMMIT_HASH="[]"', '-DHAVE_SDL2=1', '-DHAVE_FT2=1', '-DHAVE_FC=1', '-DHAVE_JPEG=1', '-DHAVE_PNG=1', '-DHAVE_CURL=1', '-DHAVE_ZLIB=1', '../bitmap/colorconversion.cpp', '-c', '-o/Users/mainuser/source-engine/build/bitmap/colorconversion.cpp.1.o']

**Comment by nillerusr** [comment]
`git submodule update --init`
@Yura97orel

**Comment by SaturnVguy** [comment]
So I am having the same issue and running, git submodule update --init doesn't do anything or the terminal just says it can't find the repository. 
I have tried reinstalling llvm, and its different versions but that doesn't work. any idea on how to fix this?
