### ISSUE TITLE
Waf configuration failure | Checking for required C Flags: no

### ISSUE THREAD

**Issue by ClaymQ** [nillerusr/source-engine#327]
I am trying to configure waf using arch linux proot distro via termux.

Starting proot with --isolated flag

Command for configuring: ./waf configure -T release -8 --togles --android=aarch64,host,21 -v

config.log - https://files.catbox.moe/ly3uk7.log

I dont really understand what I am doing wrong..

**Comment by nillerusr** [comment]
I'm not going to support builds via termux. Find out for yourself. Yes, it is possible, but even I need 30 minutes to figure out how.
