### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Low1y** [nillerusr/source-engine#33]
log is here:

kubuntu@kubuntu-User ~/Р/r/source-engine (master)> ./waf build
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f458685ff50>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f458685ff50>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f458685ff50>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f458685ff50>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f458685ff50>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f458685ff50>
Build commands will be stored in build/compile_commands.json
Traceback (most recent call last):
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Scripting.py", line 163, in waf_entry_point
    run_commands()
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Scripting.py", line 259, in run_commands
    ctx = run_command(cmd_name)
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Scripting.py", line 243, in run_command
    ctx.execute()
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Scripting.py", line 586, in execute
    return execute_method(self)
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Build.py", line 235, in execute
    self.execute_build()
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/extras/clang_compilation_database.py", line 133, in new_execute_build
    Scripting.run_command('clangdb')
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Scripting.py", line 243, in run_command
    ctx.execute()
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/extras/clang_compilation_database.py", line 119, in execute
    self.write_compilation_database()
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/extras/clang_compilation_database.py", line 47, in write_compilation_database
    root = database_file.read_json()
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Node.py", line 244, in read_json
    return json.loads(self.read(encoding=encoding), object_pairs_hook=object_pairs_hook)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Node.py", line 240, in object_pairs
    return dict((str(pair[0]), convert(pair[1])) for pair in pairs)
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Node.py", line 240, in <genexpr>
    return dict((str(pair[0]), convert(pair[1])) for pair in pairs)
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Node.py", line 233, in convert
    return [convert(element) for element in value]
  File "/home/kubuntu/Рабочий стол/repos/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Node.py", line 235, in convert
    return str(value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-22: ordinal not in range(128)

**Comment by KUKURUZKA165** [comment]
Try to build from con-cyrillic named folder

**Comment by ItzVladik** [comment]
Кирпичик, русские буквы снеси, ругается на кириллицу

**Comment by Low1y** [comment]
kubuntu@kubuntu-User:~/Рабочий стол/pepos/source-engine$ ./waf configure -T debug
Setting top to                                          : /home/kubuntu/Рабочий стол/pepos/source-engine 
Setting out to                                          : /home/kubuntu/Рабочий стол/pepos/source-engine/build 
Checking for 'gcc' (C compiler)                         : /usr/bin/gcc 
Target OS                                               : linux 
Target CPU                                              : x86_64 
Target binfmt                                           : elf 
Checking for 'g++' (C++ compiler)                       : /usr/bin/g++ 
Target OS                                               : linux 
Target CPU                                              : x86_64 
Target binfmt                                           : elf 
Checking for program 'git'                              : /usr/bin/git 
Checking git hash                                       : d947e5e 
Checking for program 'strip'                            : /usr/bin/strip 
Checking for program 'objcopy'                          : /usr/bin/objcopy 
WARNING: will build engine for 32-bit target
Checking if 'gcc' can target 32-bit                     : no 
...trying with additional flags                         : yes 
Checking for required C flags                           : yes 
Checking for required C++ flags                         : yes 
Checking supported flags for g++ in parallel            : started 
... -Wstrict-aliasing                                   : yes 
... -pipe                                               : yes 
... -Wuninitialized                                     : yes 
... -fdiagnostics-color=always                          : yes 
... -Wcast-align                                        : yes 
... -Winit-self                                         : yes 
... -Wall                                               : yes 
... -faligned-new                                       : yes 
-> processing test results                              : all ok 
Checking supported flags for gcc in parallel            : started 
... -pipe                                               : yes 
... -Wstrict-aliasing                                   : yes 
... -Wall                                               : yes 
... -faligned-new                                       : no 
... -fdiagnostics-color=always                          : yes 
... -fnonconst-initializers                             : no 
... -Wuninitialized                                     : yes 
... -Winit-self                                         : yes 
... -Wcast-align                                        : yes 
-> processing test results                              : 2 test failed 
Checking for program 'pkg-config'                       : /usr/bin/pkg-config 
Checking for 'sdl2'                                     : yes 
Checking for 'freetype2'                                : yes 
Checking for 'freetype2' sanity                         : yes 
Checking for 'fontconfig'                               : yes 
Checking for 'fontconfig' sanity                        : yes 
Checking for 'openal'                                   : yes 
Checking for 'libjpeg'                                  : yes 
Checking for 'libpng'                                   : yes 
Checking for 'libcurl'                                  : yes 
Checking for 'zlib'                                     : yes 
Checking for library dl                                 : yes 
Checking for library bz2                                : yes 
Checking for library rt                                 : yes 
Checking for library m                                  : yes 
--> appframework                                        : in progress 
<-- appframework                                        : done 
--> bitmap                                              : in progress 
<-- bitmap                                              : done 
--> choreoobjects                                       : in progress 
<-- choreoobjects                                       : done 
--> datacache                                           : in progress 
<-- datacache                                           : done 
--> datamodel                                           : in progress 
<-- datamodel                                           : done 
--> dmxloader                                           : in progress 
<-- dmxloader                                           : done 
--> engine                                              : in progress 
<-- engine                                              : done 
--> engine/voice_codecs/minimp3                         : in progress 
<-- engine/voice_codecs/minimp3                         : done 
--> filesystem                                          : in progress 
<-- filesystem                                          : done 
--> game/client                                         : in progress 
<-- game/client                                         : done 
--> game/server                                         : in progress 
<-- game/server                                         : done 
--> gameui                                              : in progress 
<-- gameui                                              : done 
--> inputsystem                                         : in progress 
<-- inputsystem                                         : done 
--> ivp/havana                                          : in progress 
<-- ivp/havana                                          : done 
--> ivp/havana/havok/hk_base                            : in progress 
<-- ivp/havana/havok/hk_base                            : done 
--> ivp/havana/havok/hk_math                            : in progress 
<-- ivp/havana/havok/hk_math                            : done 
--> ivp/ivp_compact_builder                             : in progress 
<-- ivp/ivp_compact_builder                             : done 
--> ivp/ivp_physics                                     : in progress 
<-- ivp/ivp_physics                                     : done 
--> launcher                                            : in progress 
<-- launcher                                            : done 
--> launcher_main                                       : in progress 
<-- launcher_main                                       : done 
--> materialsystem                                      : in progress 
<-- materialsystem                                      : done 
--> materialsystem/shaderapidx9                         : in progress 
<-- materialsystem/shaderapidx9                         : done 
--> materialsystem/shaderlib                            : in progress 
<-- materialsystem/shaderlib                            : done 
--> materialsystem/stdshaders                           : in progress 
<-- materialsystem/stdshaders                           : done 
--> mathlib                                             : in progress 
<-- mathlib                                             : done 
--> particles                                           : in progress 
<-- particles                                           : done 
--> scenefilecache                                      : in progress 
<-- scenefilecache                                      : done 
--> serverbrowser                                       : in progress 
<-- serverbrowser                                       : done 
--> soundemittersystem                                  : in progress 
<-- soundemittersystem                                  : done 
--> studiorender                                        : in progress 
<-- studiorender                                        : done 
--> thirdparty/StubSteamAPI                             : in progress 
<-- thirdparty/StubSteamAPI                             : done 
--> tier0                                               : in progress 
<-- tier0                                               : done 
--> tier1                                               : in progress 
<-- tier1                                               : done 
--> tier2                                               : in progress 
<-- tier2                                               : done 
--> tier3                                               : in progress 
<-- tier3                                               : done 
--> togl                                                : in progress 
<-- togl                                                : done 
--> vgui2/matsys_controls                               : in progress 
<-- vgui2/matsys_controls                               : done 
--> vgui2/src                                           : in progress 
<-- vgui2/src                                           : done 
--> vgui2/vgui_controls                                 : in progress 
<-- vgui2/vgui_controls                                 : done 
--> vgui2/vgui_surfacelib                               : in progress 
<-- vgui2/vgui_surfacelib                               : done 
--> vguimatsurface                                      : in progress 
<-- vguimatsurface                                      : done 
--> video                                               : in progress 
<-- video                                               : done 
--> vphysics                                            : in progress 
<-- vphysics                                            : done 
--> vpklib                                              : in progress 
<-- vpklib                                              : done 
--> vstdlib                                             : in progress 
<-- vstdlib                                             : done 
--> vtf                                                 : in progress 
<-- vtf                                                 : done 
'configure' finished successfully (0.538s)

**Comment by Low1y** [comment]
> Кирпичик, русские буквы снеси, ругается на кириллицу

Thats's not cyrrilic. 

new log in another folder:
kubuntu@kubuntu-User:~/source-engine$ ./waf configure -T debug
invalid lock file in /home/kubuntu/source-engine
Setting top to                                          : /home/kubuntu/source-engine 
Setting out to                                          : /home/kubuntu/source-engine/build 
Checking for 'gcc' (C compiler)                         : /usr/bin/gcc 
Target OS                                               : linux 
Target CPU                                              : x86_64 
Target binfmt                                           : elf 
Checking for 'g++' (C++ compiler)                       : /usr/bin/g++ 
Target OS                                               : linux 
Target CPU                                              : x86_64 
Target binfmt                                           : elf 
Checking for program 'git'                              : /usr/bin/git 
Checking git hash                                       : d947e5e 
Checking for program 'strip'                            : /usr/bin/strip 
Checking for program 'objcopy'                          : /usr/bin/objcopy 
WARNING: will build engine for 32-bit target
Checking if 'gcc' can target 32-bit                     : no 
...trying with additional flags                         : yes 
Checking for required C flags                           : yes 
Checking for required C++ flags                         : yes 
Checking supported flags for g++ in parallel            : started 
... -Wstrict-aliasing                                   : yes 
... -pipe                                               : yes 
... -Wuninitialized                                     : yes 
... -Wall                                               : yes 
... -Wcast-align                                        : yes 
... -Winit-self                                         : yes 
... -faligned-new                                       : yes 
... -fdiagnostics-color=always                          : yes 
-> processing test results                              : all ok 
Checking supported flags for gcc in parallel            : started 
... -Wstrict-aliasing                                   : yes 
... -Wcast-align                                        : yes 
... -Wall                                               : yes 
... -faligned-new                                       : no 
... -fdiagnostics-color=always                          : yes 
... -pipe                                               : yes 
... -fnonconst-initializers                             : no 
... -Wuninitialized                                     : yes 
... -Winit-self                                         : yes 
-> processing test results                              : 2 test failed 
Checking for program 'pkg-config'                       : /usr/bin/pkg-config 
Checking for 'sdl2'                                     : yes 
Checking for 'freetype2'                                : yes 
Checking for 'freetype2' sanity                         : yes 
Checking for 'fontconfig'                               : yes 
Checking for 'fontconfig' sanity                        : yes 
Checking for 'openal'                                   : yes 
Checking for 'libjpeg'                                  : yes 
Checking for 'libpng'                                   : yes 
Checking for 'libcurl'                                  : yes 
Checking for 'zlib'                                     : yes 
Checking for library dl                                 : yes 
Checking for library bz2                                : yes 
Checking for library rt                                 : yes 
Checking for library m                                  : yes 
--> appframework                                        : in progress 
<-- appframework                                        : done 
--> bitmap                                              : in progress 
<-- bitmap                                              : done 
--> choreoobjects                                       : in progress 
<-- choreoobjects                                       : done 
--> datacache                                           : in progress 
<-- datacache                                           : done 
--> datamodel                                           : in progress 
<-- datamodel                                           : done 
--> dmxloader                                           : in progress 
<-- dmxloader                                           : done 
--> engine                                              : in progress 
<-- engine                                              : done 
--> engine/voice_codecs/minimp3                         : in progress 
<-- engine/voice_codecs/minimp3                         : done 
--> filesystem                                          : in progress 
<-- filesystem                                          : done 
--> game/client                                         : in progress 
<-- game/client                                         : done 
--> game/server                                         : in progress 
<-- game/server                                         : done 
--> gameui                                              : in progress 
<-- gameui                                              : done 
--> inputsystem                                         : in progress 
<-- inputsystem                                         : done 
--> ivp/havana                                          : in progress 
<-- ivp/havana                                          : done 
--> ivp/havana/havok/hk_base                            : in progress 
<-- ivp/havana/havok/hk_base                            : done 
--> ivp/havana/havok/hk_math                            : in progress 
<-- ivp/havana/havok/hk_math                            : done 
--> ivp/ivp_compact_builder                             : in progress 
<-- ivp/ivp_compact_builder                             : done 
--> ivp/ivp_physics                                     : in progress 
<-- ivp/ivp_physics                                     : done 
--> launcher                                            : in progress 
<-- launcher                                            : done 
--> launcher_main                                       : in progress 
<-- launcher_main                                       : done 
--> materialsystem                                      : in progress 
<-- materialsystem                                      : done 
--> materialsystem/shaderapidx9                         : in progress 
<-- materialsystem/shaderapidx9                         : done 
--> materialsystem/shaderlib                            : in progress 
<-- materialsystem/shaderlib                            : done 
--> materialsystem/stdshaders                           : in progress 
<-- materialsystem/stdshaders                           : done 
--> mathlib                                             : in progress 
<-- mathlib                                             : done 
--> particles                                           : in progress 
<-- particles                                           : done 
--> scenefilecache                                      : in progress 
<-- scenefilecache                                      : done 
--> serverbrowser                                       : in progress 
<-- serverbrowser                                       : done 
--> soundemittersystem                                  : in progress 
<-- soundemittersystem                                  : done 
--> studiorender                                        : in progress 
<-- studiorender                                        : done 
--> thirdparty/StubSteamAPI                             : in progress 
<-- thirdparty/StubSteamAPI                             : done 
--> tier0                                               : in progress 
<-- tier0                                               : done 
--> tier1                                               : in progress 
<-- tier1                                               : done 
--> tier2                                               : in progress 
<-- tier2                                               : done 
--> tier3                                               : in progress 
<-- tier3                                               : done 
--> togl                                                : in progress 
<-- togl                                                : done 
--> vgui2/matsys_controls                               : in progress 
<-- vgui2/matsys_controls                               : done 
--> vgui2/src                                           : in progress 
<-- vgui2/src                                           : done 
--> vgui2/vgui_controls                                 : in progress 
<-- vgui2/vgui_controls                                 : done 
--> vgui2/vgui_surfacelib                               : in progress 
<-- vgui2/vgui_surfacelib                               : done 
--> vguimatsurface                                      : in progress 
<-- vguimatsurface                                      : done 
--> video                                               : in progress 
<-- video                                               : done 
--> vphysics                                            : in progress 
<-- vphysics                                            : done 
--> vpklib                                              : in progress 
<-- vpklib                                              : done 
--> vstdlib                                             : in progress 
<-- vstdlib                                             : done 
--> vtf                                                 : in progress 
<-- vtf                                                 : done 
'configure' finished successfully (0.565s)
kubuntu@kubuntu-User:~/source-engine$ ./waf build
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7ff5f802fe50>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7ff5f802fe50>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7ff5f802fe50>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7ff5f802fe50>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7ff5f802fe50>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7ff5f802fe50>
Build commands will be stored in build/compile_commands.json
Traceback (most recent call last):
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Scripting.py", line 163, in waf_entry_point
    run_commands()
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Scripting.py", line 259, in run_commands
    ctx = run_command(cmd_name)
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Scripting.py", line 243, in run_command
    ctx.execute()
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Scripting.py", line 586, in execute
    return execute_method(self)
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Build.py", line 235, in execute
    self.execute_build()
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/extras/clang_compilation_database.py", line 133, in new_execute_build
    Scripting.run_command('clangdb')
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Scripting.py", line 243, in run_command
    ctx.execute()
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/extras/clang_compilation_database.py", line 119, in execute
    self.write_compilation_database()
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/extras/clang_compilation_database.py", line 47, in write_compilation_database
    root = database_file.read_json()
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Node.py", line 244, in read_json
    return json.loads(self.read(encoding=encoding), object_pairs_hook=object_pairs_hook)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Node.py", line 240, in object_pairs
    return dict((str(pair[0]), convert(pair[1])) for pair in pairs)
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Node.py", line 240, in <genexpr>
    return dict((str(pair[0]), convert(pair[1])) for pair in pairs)
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Node.py", line 233, in convert
    return [convert(element) for element in value]
  File "/home/kubuntu/source-engine/.waf-2.0.22-a21fa92a45548e4c642deabae50eb159/waflib/Node.py", line 235, in convert
    return str(value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-22: ordinal not in range(128)
kubuntu@kubuntu-User:~/source-engine$

**Comment by Low1y** [comment]
Sometimes it's not the Cyrillic alphabet

**Comment by lilmayofuksu** [comment]
try this command before configuring 
export PYTHONIOENCODING=utf-8

**Comment by nillerusr** [comment]
outdated
