### ISSUE TITLE
Как из исходников собрать TF2?:)

### ISSUE THREAD

**Issue by ArtemS2** [nillerusr/source-engine#333]
![2](https://github.com/nillerusr/source-engine/assets/69766464/c0678d36-adeb-46c5-8044-06ca40c09f64)
В дисе написали, что такое есть)

**Comment by SanyaSho** [comment]
тебе никак

**Comment by ArtemS2** [comment]
@SanyaSho я уже понял, что никак ,  сейчас закрою обсуждение.)
