### ISSUE TITLE
"Your compiler sucks"

### ISSUE THREAD

**Issue by marcikaa78** [nillerusr/source-engine#348]
![image](https://github.com/nillerusr/source-engine/assets/132925550/16526547-059d-4690-9960-09ccf2d95c78)

**Comment by Aleph-202** [comment]
braindead

**Comment by marcikaa78** [comment]
:(

**Comment by er2off** [comment]
agree with nillerusr, msvc is really sucks

but anyway, @nillerusr, HOW? it should target 64 bit but waf doesn't detect it

**Comment by nillerusr** [comment]
@marcikaa78 send Complete log :trollface:

**Comment by marcikaa78** [comment]
https://pastebin.com/5pptud93

**Comment by mittorn** [comment]
> out: LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'


UCRT is missing? Broken windows sdk installation? Try reinstall it and 
check C:\\Program Files (x86)\\Windows Kits\\10 folder if in contain 
needed files

Modern MSVC toolchain really sucks as cannot keep toolchain in single 
path and allows mixing incompatible components...

Also it lost devenv scripts like vcvarsall which at least guaranted 
setting up working environment without needing build system find all 
these components itself...

**Comment by marcikaa78** [comment]
Thanks! Reinstalled Windows SDK, and it works. YaY!

**Comment by marcikaa78** [comment]
Thanks! Reinstalled Windows SDK, and it works. YaY!

**Comment by SamuelEatsPizza** [comment]
NOTE:
dont use WSL to compile. you get the "your compiler sucks" problem. it worked fine when I copied it out of wsl.
