### ISSUE TITLE
black screen after loading

### ISSUE THREAD

**Issue by TheLocalMoon** [nillerusr/source-engine#350]
ermm what the sigma

![image](https://github.com/nillerusr/source-engine/assets/134215072/f0a861cf-ad93-4867-b4fd-3984366b2901)

**Comment by TheLocalMoon** [comment]
when i hover on buttons (i know where they are) the sounds are playing tho

**Comment by maksw2** [comment]
i'm experiencing the same problem (32 bit binaries), it can load up a map through launch arguments, but doesn't recognize any inputs in game. there are some problems with viewmodels. what i did is copy hl2dm, delete bin folder, copy compiled files and overwrite existing ones. i used these launch arguments: hl2_launcher.exe -game hl2mp -dxlevel 95 -w 1920 -h 1080 -windowed -noborder -insecure +map dm_lockdown

**Comment by maksw2** [comment]
the 64 bit binaries crash on load

**Comment by dimhotepus** [comment]
`-dxlevel 85` as launch arguments.


Or copy shaders from tf2

Reason is dx 9+ shaders are changed by valve and not compatible with source.

**Comment by maksw2** [comment]
with -dxlevel 85 it crashes. i'm looking forward to the tf2 approach. can you tell me which files to copy over?

**Comment by dimhotepus** [comment]
> with -dxlevel 85 it crashes. i'm looking forward to the tf2 approach. can you tell me which files to copy over?

What if `-dxlevel 90` ?

If not working, for TF2 go to `tf2\shaders\`, backup `hl2\shaders`, replace `hl2\shaders` with `tf2\shaders`.

**Comment by dimhotepus** [comment]
> hl2 works just fine, only hl2mp has that problem. i can't seem to find the shader files, is it in a .vpk?

well, I know only about hl2 issue. With hl2mp all is possible.

try to extract shaders from VPK.

**Comment by maksw2** [comment]
after copying hl2's shaders it looks something like this
![image](https://github.com/nillerusr/source-engine/assets/66273956/39d70491-b767-437a-b53d-81244681c2ba)

**Comment by maksw2** [comment]
the buttons still make a sound when hovered over, and the loading image is still good.

**Comment by maksw2** [comment]
it's probably to do with vgui.

**Comment by nillerusr** [comment]
1. add `-dxlevel 95` option
2. copy shaders from retail hl2 folder to mp hl2 folder or just hl2_misc_*.vpk ( idk why, but shaders in mp branch and sp branch differs )
Also you can recompile stdshaders_dx9 from mp branch.

**Comment by maksw2** [comment]
i was able to run hl2mp and connect to a server simply by moving "hl2mp" folder to half-life 2 dir. lol.
