### ISSUE TITLE
'tier 0' failed with exit status 2

### ISSUE THREAD

**Issue by 2005abruno** [nillerusr/source-engine#351]
I do not understand what i did wrong i would like some help. I will send log if needed

**Comment by 2005abruno** [comment]
this happens when i run ./waf.bat install

**Comment by maksw2** [comment]
we can't do anything without the logs. also, it looks like the issue is on your side. what did you specify as --prefix ?

**Comment by 2005abruno** [comment]
this is what i had typed in "`./waf.bat configure -T release --prefix="D:\SteamLibrary\steamapps\common\Half-Life 2" --build-games=hl2` " and where do i find the log at om new to this sry

**Comment by maksw2** [comment]
first, you can throw away --build-games since hl2 is the default. also, in the prefix just type --prefix=mod_hl2. that will create a folder mod_hl2 with all the compiled files (after waf.bat install). then you can copy them over where you want. don't forget to delete the hl2 bin folder, otherwise video_quicktime.dll error.

**Comment by 2005abruno** [comment]
ok ill try that

**Comment by 2005abruno** [comment]
that didnt work i still got the error.

**Comment by maksw2** [comment]
can you provide the full log?

**Comment by 2005abruno** [comment]
I still am not sure where the log file gets saved to. if you could help me with that i can get the logs

**Comment by maksw2** [comment]
just copy the console where the error occurs and down a few lines.

**Comment by 2005abruno** [comment]
here is only a few lines of it starting from where the error started ```
D:\source-engine\public\tier0\basetypes.h(106): error C2371: 'uintptr_t': redefinition; different basic types
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\vadefs.h(61): note: see declaration of 'uintptr_t'
D:\source-engine\public\tier0\platform.h(489): error C4235: nonstandard extension used: '__asm' keyword not supported on this architecture
D:\source-engine\public\tier0\platform.h(491): error C2065: 'fnclex': undeclared identifier
D:\source-engine\public\tier0\platform.h(492): error C2146: syntax error: missing ';' before identifier 'fnstcw'
D:\source-engine\public\tier0\platform.h(492): error C2065: 'fnstcw': undeclared identifier
D:\source-engine\public\tier0\platform.h(492): error C2146: syntax error: missing ';' before identifier 'word'
D:\source-engine\public\tier0\platform.h(492): error C2131: expression did not evaluate to a constant
D:\source-engine\public\tier0\platform.h(492): note: failure was caused by a read of a variable outside its lifetime
D:\source-engine\public\tier0\platform.h(492): note: see usage of 'tmpCtrlW'
D:\source-engine\public\tier0\platform.h(493): error C2146: syntax error: missing ';' before identifier 'and'
D:\source-engine\public\tier0\platform.h(493): error C2065: 'and': undeclared identifier
D:\source-engine\public\tier0\platform.h(493): error C3688: invalid literal suffix 'FCC0h'; literal operator or literal operator template 'operator ""FCC0h' not found
D:\source-engine\public\tier0\platform.h(494): error C2146: syntax error: missing ';' before identifier 'or'
D:\source-engine\public\tier0\platform.h(494): error C2065: 'or': undeclared identifier
D:\source-engine\public\tier0\platform.h(494): error C3688: invalid literal suffix 'h'; literal operator or literal operator template 'operator ""h' not found
```

**Comment by 2005abruno** [comment]
this is when i did ./waf.bat install

**Comment by maksw2** [comment]
try deleting it and recloning with --recursive

**Comment by 2005abruno** [comment]
ok it started working but i got an internal compiler error im gunna install vs2017

**Comment by 2005abruno** [comment]
nevermind i ran out of space on the drive i was installing to

**Comment by 2005abruno** [comment]
It worked Thanks for your help

**Comment by 2005abruno** [comment]
thanks

**Comment by maksw2** [comment]
yeah, vs2022 has some weird problems and that's the solution that worked for me. glad that i could help.
