### ISSUE TITLE
[CS:S] [HL2:DM] No interface at startup

### ISSUE THREAD

**Issue by DiegoArmando-27** [nillerusr/source-engine#363]
![image](https://github.com/nillerusr/source-engine/assets/73876067/21e8c9aa-5d9f-4ddb-866e-ea032de33b9c)
![image](https://github.com/nillerusr/source-engine/assets/73876067/cf225810-9d05-436a-81fa-f9dad64a54be)
But when I hover on buttons, the sounds are playing

**Comment by maksw2** [comment]
duplicate of #350

**Comment by DiegoArmando-27** [comment]
Copying shaders helped me. Closing
