### ISSUE TITLE
Error: Waf cannot be unpacked, check that bzip2 support is present

### ISSUE THREAD

**Issue by MatveySDK** [nillerusr/source-engine#370]
How to fix an error when entering the command ./waf install?
`'bunzip2' is not recognized as an internal or external command,
operable program or batch file.
Error: Waf cannot be unpacked, check that bzip2 support is present`

In the past, a person from discord @AruMoon  helped me and then everything worked, but when I started compiling again, there was an error. How can I fix it?

**Comment by yungDoom** [comment]
Do you cloned the repo with Git? Did you add `--recursive` parameter while cloning it?

**Comment by yungDoom** [comment]
Also, What Python version do you have?

**Comment by MatveySDK** [comment]
> И еще, какая у вас версия Python?

3.12

**Comment by MatveySDK** [comment]
> Вы клонировали репозиторий с помощью Git? Вы добавляли `--recursive`параметры при клонировании?

Oh, I didn't take that into account. I'll try

**Comment by yungDoom** [comment]
Okay

**Comment by MatveySDK** [comment]
I repeated the download with the console, but unfortunately it still asks for bunzip2. What else could it be? If I'm doing something wrong, I'll close the problem...

**Comment by yungDoom** [comment]
Remove Python from Control Panel and Install it again but don't forget to tick "Add to PATH"

**Comment by yungDoom** [comment]
Python is already includes bunzip2 in itself so you probably have a broken python installation i think 🤔

**Comment by MatveySDK** [comment]
> Сначала вам нужно настроить исходный движок, попробовать ввести текст `waf.bat configure -T release --prefix=hl2 --build-games=hl2 --disable-warns --enable-opus`, а затем ввести его.

Is it possible to do the setup other than in powershell?
New error:
`waf.bat : The name "waf.bat" is not recognized as the name of a cmdlet, function, script file, or executable program. Check for correctness
spelling of the name, as well as the presence and correctness of the path, then try again.
line:1 character:1
+ waf.bat configure -T release --prefix=hl2 --build-games=hl2 --disable ...
+ ~~~~~~~
    + CategoryInfo : ObjectNotFound: (waf.bat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

Python has been added to Path

After the error has passed, when writing ./waf install
What happens is this:
`"chcp" is not internal or external
command, executable program, or batch file.
"findstr" is not internal or external
command, executable program, or batch file.`

**Comment by yungDoom** [comment]
> > Сначала вам нужно настроить исходный движок, попробовать ввести текст `waf.bat configure -T release --prefix=hl2 --build-games=hl2 --disable-warns --enable-opus`, а затем ввести его.
> 
> Is it possible to do the setup other than in powershell? New error: `waf.bat : The name "waf.bat" is not recognized as the name of a cmdlet, function, script file, or executable program. Check for correctness spelling of the name, as well as the presence and correctness of the path, then try again. line:1 character:1
> 
> * waf.bat configure -T release --prefix=hl2 --build-games=hl2 --disable ...
> * ```
>     + CategoryInfo : ObjectNotFound: (waf.bat:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException`
>   ```
> 
> Python has been added to Path
> 
> After the error has passed, when writing ./waf install What happens is this: `"chcp" is not internal or external command, executable program, or batch file. "findstr" is not internal or external command, executable program, or batch file.`

i can compile the game in cmd too, so try typing .\waf.bat rather than waf.bat and also you should be in the source-engine folder when typing this commands.

**Comment by MatveySDK** [comment]
> > > Сначала вам нужно настроить исходный движок, попробуйте ввести текст `waf.bat configure -T release --prefix=hl2 --build-games=hl2 --disable-warns --enable-opus`, а затем введите его.
> > 
> > 
> > Возможно ли выполнить настройку не в powershell? Новая ошибка: `waf.bat : Имя "waf.bat" не распознано как имя командлета, функции, файла сценария или исполняемой программы. Проверьте правильность написания имени, а также наличие и правильность пути, затем повторите попытку. строка:1 символ:1
> > 
> > * waf.bat настроить -T release --prefix=hl2 --build-games=hl2 --disable ...
> > * ```
> >     + CategoryInfo : ObjectNotFound: (waf.bat:String) [], CommandNotFoundException
> >     + FullyQualifiedErrorId : CommandNotFoundException`
> >   ```
> > 
> > Python добавлен в Path
> > После того, как ошибка исчезла, при написании ./waf install происходит следующее:`"chcp" is not internal or external command, executable program, or batch file. "findstr" is not internal or external command, executable program, or batch file.`
> 
> Я также могу скомпилировать игру в cmd, поэтому попробуйте ввести .\waf.bat вместо waf.bat, а также вы должны находиться в папке исходного движка при вводе этих команд.

I am doing work in the folder where waf.bat is located, I wrote the command .\waf.bat ....

And there were no errors, but this appears:
`"chcp" is not internal or external command, executable program, or batch file. "findstr" is not internal or external command, executable program, or batch file.`

**Comment by yungDoom** [comment]
`where chcp` vshould show `C:\Windows\System32\chcp.com`

**Comment by yungDoom** [comment]
If it doesn't show anything, you should add your system32 to PATH

**Comment by MatveySDK** [comment]
> If it doesn't show anything, you should add your system32 to PATH (System Environment Variable) ![image](https://private-user-images.githubusercontent.com/146978592/354583495-26178dff-88a8-47b7-99af-593e58250897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDE0ODUsIm5iZiI6MTcyMjYwMTE4NSwicGF0aCI6Ii8xNDY5Nzg1OTIvMzU0NTgzNDk1LTI2MTc4ZGZmLTg4YTgtNDdiNy05OWFmLTU5M2U1ODI1MDg5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxMjE5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGNkNjU2YmNjYzZjNTE5NTc5NzE2M2I3NWFiZmE1NjE5YWNjYTEzYzczMTM5ZGEyZjAyZTI5OGU0OWFkM2RmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TcaogeARFXSCqz-gzTM_tyAB34RsDnVaPhioXNNtkJ8) ![image](https://private-user-images.githubusercontent.com/146978592/354583343-2863dfaf-af31-4ef3-a735-c35a9c8bb2c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDE0ODUsIm5iZiI6MTcyMjYwMTE4NSwicGF0aCI6Ii8xNDY5Nzg1OTIvMzU0NTgzMzQzLTI4NjNkZmFmLWFmMzEtNGVmMy1hNzM1LWMzNWE5YzhiYjJjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxMjE5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzg1OGU5NzUyOTI2Y2M2ZDMwZGIxNTNmODJhNDU1YzVlZjlkNTYxOWIxNjY4ZmI1ODdlMTU3N2UxNTc5ZDY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ba0MK6CaCSNN3BHFeQ4SVAH6SsP5-P6_AtxvxIUQoI)

I added it with the name src, but nothing, no results... What else could it be? Or have you already tried everything?
