### ISSUE TITLE
[Question] is this a multiplayer fork of source or a singleplayer?

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [nillerusr/source-engine#373]
is this multiplayer or singleplayer?

**Comment by FoxbitDreamtail** [comment]
I actually believe that it's both. And there are community-made servers that this does connect to if you want to play Half-Life 2 multiplayer or Half-Life 2 deathmatch as it's called, or Team Fortress 2 Classic, Or if you want to play Counter Strike: Source, it's also available.

**Comment by GuestSneezeOSDev** [comment]
thank you
