### ISSUE TITLE
Issue while building

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [nillerusr/source-engine#377]
```
gsosdev@debian:/Source$ ./waf configure -T release --prefix=build/bin --build-games=hl2mp
Setting top to                                          : /XenSource
Setting out to                                          : /XenSource/build
Checking for 'gcc' (C compiler)                         : /usr/bin/gcc
Target OS                                               : linux
Target CPU                                              : x86_64
Target binfmt                                           : elf
Checking for 'g++' (C++ compiler)                       : /usr/bin/g++
Target OS                                               : linux
Target CPU                                              : x86_64
Target binfmt                                           : elf
Checking for program 'git'                              : /usr/bin/git
Checking git hash                                       : beafcd0e-dirty
Checking for program 'strip'                            : /usr/bin/strip
Checking for program 'objcopy'                          : /usr/bin/objcopy
WARNING: will build engine for 32-bit target
Checking if 'gcc' can target 32-bit                     : no
...trying with additional flags                         : no
Compiler can't create 32-bit code!
(complete log in /XenSource/build/config.log)
```
I installed all dependencies
I also do want to note i was using WSL

**Comment by FoxbitDreamtail** [comment]
So the first thing you're going to want to notice is that you're trying to compile for Linux on Windows. If you intend to use the Windows version, don't do it this way, Second off, you're going to want a version of Visual Studio to compile the actual project. You can create the Visual Studio files using waf, WSL is completely unnecessary for this project.

**Comment by ThePixelMoon** [comment]
> So the first thing you're going to want to notice is that you're trying to compile for Linux on Windows. If you intend to use the Windows version, don't do it this way, Second off, you're going to want a version of Visual Studio to compile the actual project. You can create the Visual Studio files using waf, WSL is completely unnecessary for this project as waf can and does run natively using the windows version of python.

what if he wants to compile for linux but he's a lazy ass and cant move to linux to do it?

**Comment by GuestSneezeOSDev** [comment]
I'll just use VM's instead of WSL
