### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by unkn0wncvm1** [nillerusr/source-engine#395]
hello im trying to run hl2mp on fedora but i get segmentation falust core dumped
system info:Linux fedora 6.11.7-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov  8 19:23:10 UTC 2024 x86_64 GNU/Linux
Full log:
`SDL version: 2.30.3 rev: SDL-release-2.30.3-0-gfb1497566
LoadLibrary: path: /home/user/source-engine/hl2mp/bin/libfilesystem_stdio.so
SDL video target is 'wayland'
SDL video target is 'wayland'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
Segmentation fault (core dumped)
`

**Comment by unkn0wncvm1** [comment]
nevermind, changing to x11 fixed the issue

**Comment by ItzVladik** [comment]
LOL, if you catch segmentation fault again, please compile engine with debug, run with gdb, catch crash and send gdb backtrace

**Comment by unkn0wncvm1** [comment]
btw if you relly dont want to shiwtch from wayland set the SDL_VIDEDRIVER to x11 like this
`SDL_VIDEODRIVER=x11 ./hl2_launcher`
