### ISSUE TITLE
Can't build on Mac Intel 64 bit

### ISSUE THREAD

**Issue by zakhar-gulchak** [nillerusr/source-engine#398]
I got an issue after running 'python3 waf build'.
I have a MacOS Sequoia 15.1. Mac is running on Intel chip

```
clang++: warning: argument unused during compilation: '-L/Users/zakhargulchak/source-engine/lib/darwin/x86_64/' [-Wunused-command-line-argument]
In file included from ../tier0/systeminformation.cpp:9:
In file included from ../tier0/pch_tier0.h:20:
In file included from ../public/tier0/basetypes.h:11:
In file included from ../public/tier0/commonmacros.h:15:
../public/tier0/platform.h:86:10: fatal error: 'new' file not found
   86 | #include <new>
      |          ^~~~~
1 error generated.
```

**Comment by FlamedDogo99** [comment]
I have a M2, so this could easily do nothing for you, but uninstalling binutils fixed that for me (@Hakase on the macports discord was super helpful for troubleshooting things last year when I was struggling to get it to build. Would recommend if you continue to have problems)

**Comment by zakhar-gulchak** [comment]
this doesn't help me, unfortunatly.
Can you clarify which discord channel you mean @FlamedDogo99

**Comment by FlamedDogo99** [comment]
https://discord.gg/5xqUxWWCQa
