### ISSUE TITLE
Do not works on Nvidia Shield 2019 Pro

### ISSUE THREAD

**Issue by benda95280** [nillerusr/source-engine#4]
Hello,

First, hope you've got an happy christmas :)

It seems it do not works on Nvidia Shield Pro 2019.
App is able to found Obb file, but after launching, i stay on a black screen.
Tested with same source on my Xiaomi Phone with success.

Could you tell me what i can try/do to get it work ?

**Comment by nillerusr** [comment]
This repo for new port. Open this issue in srceng-android repo please
