### ISSUE TITLE
cstrike font and logo does not render

### ISSUE THREAD

**Issue by tinspin** [nillerusr/source-engine#401]
Latest all on Raspberry 4

**Comment by unkn0wncvm1** [comment]
try to copy hl2_misc_*.vpk from the hl2 pre 20th anniversary build to the hl2 folder in css

**Comment by tinspin** [comment]
Works! Thx! Now we just need to port CS2 models, textures and levels! XD

**Comment by tinspin** [comment]
Works! Thx! Now we just need to port CS2 models, textures and levels! XD
