### ISSUE TITLE
help

### ISSUE THREAD

**Issue by nn15** [nillerusr/source-engine#41]
Build failed
 -> task in 'client' failed with exit status 1: 
	{task 140456212640464: cxx achievements_cs.cpp -> achievements_cs.cpp.9.o}
['/home/nn/andk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++', '--sysroot=/home/nn/andk/android-ndk-r10e/platforms/android-21/arch-arm', '-I/home/nn/andk/android-ndk-r10e/sources/cxx-stl/stlport/stlport', '-I/home/nn/andk/android-ndk-r10e/sources/android/support/include', '-DANDROID', '-D__ANDROID__', '-mthumb', '-mfpu=neon', '-mcpu=cortex-a9', '-DHAVE_EFFICIENT_UNALIGNED_ACCESS', '-DVECTORIZE_SINCOS', '-mvectorize-with-neon-quad', '-D_NDK_MATH_NO_SOFTFP=1', '-mfloat-abi=hard', '-DLOAD_HARDFP', '-DSOFTFP_LINK', '-g', '-fvisibility=hidden', '-O0', '-fPIC', '-L/home/nn/source-engine-togles3/lib/android/armeabi-v7a/', '-I/home/nn/source-engine-togles3/thirdparty/curl/include', '-I/home/nn/source-engine-togles3/thirdparty/SDL', '-I/home/nn/source-engine-togles3/thirdparty/openal-soft/include/', '-I/home/nn/source-engine-togles3/thirdparty/fontconfig', '-I/home/nn/source-engine-togles3/thirdparty/freetype/include', '-llog', '-fsigned-char', '-mcpu=cortex-a15', '-mtune=cortex-a15', '-std=c++11', '-fpermissive', '-pipe', '-Wall', '-fdiagnostics-color=always', '-Wcast-align', '-Wuninitialized', '-Winit-self', '-Wstrict-aliasing', '-fPIC', '-Igame/client', '-I../game/client', '-Igame/client/game_controls', '-I../game/client/game_controls', '-Icommon', '-I../common', '-Ipublic', '-I../public', '-Ipublic/tier0', '-I../public/tier0', '-Ipublic/tier1', '-I../public/tier1', '-Ivgui2/include', '-I../vgui2/include', '-Ivgui2/controls', '-I../vgui2/controls', '-Igame/shared', '-I../game/shared', '-Igame/client', '-I../game/client', '-Igame/shared', '-I../game/shared', '-Igame/client/game_controls', '-I../game/client/game_controls', '-Ithirdparty/sixensesdk/include', '-I../thirdparty/sixensesdk/include', '-Igame/shared/cstrike/control', '-I../game/shared/cstrike/control', '-Igame/client/cstrike', '-I../game/client/cstrike', '-Igame/client/cstrike/control', '-I../game/client/cstrike/control', '-Igame/client/cstrike/VGUI', '-I../game/client/cstrike/VGUI', '-Igame/shared/cstrike', '-I../game/shared/cstrike', '-I../common', '-DDX_TO_GL_ABSTRACTION', '-DGL_GLEXT_PROTOTYPES', '-DBINK_VIDEO', '-DUSE_SDL=1', '-DANDROID=1', '-D_ANDROID=1', '-DLINUX=1', '-D_LINUX=1', '-DPOSIX=1', '-D_POSIX=1', '-DGNUC', '-DNO_HOOK_MALLOC', '-D_DLL_EXT=.so', '-DNDEBUG', '-DCOMPILER_GCC=1', '-DNO_STRING_T', '-DCLIENT_DLL', '-DVECTOR', '-DVERSION_SAFE_STEAM_API_INTERFACES', '-Dstrncpy=use_Q_strncpy_instead', '-D_snprintf=use_Q_snprintf_instead', '-DCSTRIKE_DLL', '-DNEXT_BOT', '../game/shared/cstrike/achievements_cs.cpp', '-c', '-o/home/nn/source-engine-togles3/build/game/shared/cstrike/achievements_cs.cpp.9.o']

**Comment by nn15** [comment]
ok

**Comment by magisk666** [comment]
С Новым Годом!

**Comment by nn15** [comment]
-hard
