### ISSUE TITLE
I can not switch guns

### ISSUE THREAD

**Issue by nn15** [nillerusr/source-engine#42]
when i use invprev it will switch to knife

**Comment by magisk666** [comment]
> 当我使用 invprev 它会切换到刀

Yes, this is the problem he encountered when playing CSS android, but it has been fixed.

**Comment by nn15** [comment]
sv_pure -1

**Comment by magisk666** [comment]
> sv_pure -1

himfix

**Comment by magisk666** [comment]
笑死我

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
