### ISSUE TITLE
Compiling hl2dm launcher, something went wrong

### ISSUE THREAD

**Issue by magisk666** [nillerusr/source-engine#44]
My friend compiled a hl2dm launcher today and built it from this repository, but something went wrong. There are bugs in the font display in the game, including the game screen becoming darker, but at the same time some lighting effects rendering problems have been fixed, I hope the next This commit fixes these issues.
![Screenshot_20220210-151822](https://user-images.githubusercontent.com/77914162/153358644-667dbbd1-88f4-45a6-84d7-21b66b880773.png)
![Screenshot_20220210-151621](https://user-images.githubusercontent.com/77914162/153358679-e9fa40a1-87c3-4990-8fdb-31645205f963.png)
![Screenshot_20220210-151012](https://user-images.githubusercontent.com/77914162/153358694-3d2ae873-c9c3-4e40-b285-a8e8705309c0.png)

**Comment by nn15** [comment]
az

**Comment by nn15** [comment]
不可能

**Comment by nn15** [comment]
滑稽

**Comment by magisk666** [comment]
When will the screen problems be fixed? 😯

**Comment by nn15** [comment]
never

**Comment by magisk666** [comment]
> 绝不

现在渲染器好了，什么时候更新1.09版本的其他启动器？
