### ISSUE TITLE
Build Issues(master branch)

### ISSUE THREAD

**Issue by CNSRxiaodo** [nillerusr/source-engine#47]
Checking for 'gcc' (C compiler)
find program=['gcc', 'cc'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/usr/local/bin/cmake/bin', '/root/bin'] var='CC' -> ['/usr/local/bin/android-ndk-r10e/toolchains/arm-linux-andro
ideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc']from /root/source-engine: Program ['/usr/local/bin/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc'] is not executable
not found
-------------------------------------------------------
Checking for 'clang' (C compiler)
find program=['clang'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/usr/local/bin/cmake/bin', '/root/bin'] var='CC' -> ['/usr/local/bin/android-ndk-r10e/toolchains/arm-linux-androidea
bi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc']from /root/source-engine: Program ['/usr/local/bin/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc'] is not executable
not found
-------------------------------------------------------
Checking for 'icc' (C compiler)
find program=['icc', 'ICL'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/usr/local/bin/cmake/bin', '/root/bin'] var='CC' -> ['/usr/local/bin/android-ndk-r10e/toolchains/arm-linux-andr
oideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc']from /root/source-engine: Program ['/usr/local/bin/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc'] is not executable
not found
from /root/source-engine: could not configure a C compiler!

-------------------------------------------------------
Linux used: CentOS7 x86_64
Build parameter:  ./waf configure -T debug --android=armeabi-v7a-hard,4.9,21
Using the Lastest master branch.

I already installed gcc, g++, and clang from yum, but the waf always can't find them!
Same Problem on Ubuntu 20.04 x86_64!
![image](https://user-images.githubusercontent.com/30372006/153944248-946bb1f1-63cb-4a6a-9909-7f0c3c03381e.png)

**Comment by TheASVigilante** [comment]
Config.log pls

**Comment by CNSRxiaodo** [comment]
issues solved. before you execute ./waf configure, you should execute this command: chmod +x $ANDROID_NDK_PATH -R.

**Comment by guranu** [comment]
i know this issue is closed and all but when i try to execute chmod +x $ANDROID_NDK_PATH -R i get this error:
![3523233](https://user-images.githubusercontent.com/103632948/166203569-f045a056-5464-44a3-bba0-333b2dfb36c6.jpg)

**Comment by guranu** [comment]
i know this issue is closed but when i try to execute chmod +x $ANDROID_NDK_PATH -R i get this error:
![Screenshot_20220502-110728_1](https://user-images.githubusercontent.com/103632948/166203827-64882d02-959e-40b9-bd13-d72c15b25229.jpg)
