### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by CNSRxiaodo** [nillerusr/source-engine#48]
---------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/30372006/153951657-bf1b94e2-abd7-4612-8f77-1d630b25c7c9.png)
---------------------------------------------------------------------------------
Linux used: CentOS7 x86_64
Build parameter: ./waf configure -T debug --android=armeabi-v7a-hard,4.9,21
Using the Lastest master branch.
Same Error on my Ubuntu 20.04 x86_64!

**Comment by nn15** [comment]
IDK IFT

**Comment by nn15** [comment]
作者处理问题较慢

**Comment by nillerusr** [comment]
Which version of python are you using?

**Comment by CNSRxiaodo** [comment]
> 

Python 2.7.5 (default, Nov 16 2020, 22:23:17)

**Comment by CNSRxiaodo** [comment]
config.log: https://anonfiles.com/ta38hbI6x4/config_log

**Comment by nillerusr** [comment]
Do it wrong

**Comment by magisk666** [comment]
你应该使用3。x版本
