### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mihaios1k** [nillerusr/source-engine#5]
./createallprojects Остановилось на
```
Parsing: havana_constraints.vpc
ERROR: Cannot open havana_constraints.vpc
~/source-engine

```

**Comment by nillerusr** [comment]
Понимаю. Я даже и не знаю что тут делать. Все дело в отсутвующих исходниках физики. Вернее я их залил, но в приватную репу. Велика вероятность, что за havoc может DCMA прилететь. Я наверное просто залью уже готовые блобы

**Comment by mihaios1k** [comment]
Что бы добавить мод по типу Portal Prelude апк нужно компилить?

**Comment by mihaios1k** [comment]
Блин как скомпилить то?
