### ISSUE TITLE
Create sln error: ERROR: Cannot open socketlib.vpc

### ISSUE THREAD

**Issue by CeSun** [nillerusr/source-engine#50]
Use Windows Branch

```
Parsing: socketlib.vpc
ERROR: Cannot open socketlib.vpc
```

**Comment by TheASVigilante** [comment]
Exclude it by adding -socketlib to the bat file

**Comment by TheASVigilante** [comment]
It is prebuilt so we don't have to compile it

**Comment by JusicP** [comment]
creategameprojects.bat

**Comment by LegendaryGuard** [comment]
> Exclude it by adding -socketlib to the bat file

After doing this, stops here and gets this error: 
```
Parsing: fbx2dmx.vpc
ERROR: Cannot open fbx2dmx.vpc
```

**Comment by TheASVigilante** [comment]
@LegendaryGuard 
vpc is case-sensitive, the filenames specified in the vpc files have the wrong capitalisation.

**Comment by LegendaryGuard** [comment]
> @LegendaryGuard vpc is case-sensitive, the filenames specified in the vpc files have the wrong capitalisation. EDIT: Looking at it again, someone may have removed some of those files since they still are in my source tree

Same errors. I don't know where these files are if these should be added.

**Comment by TheASVigilante** [comment]
@LegendaryGuard If you really want to build them, check the leak all this code came from, if it's not in that leaked source tree, then check the cs:go source tree that was leaked alongside it, that's guaranteed to have it.

**Comment by LegendaryGuard** [comment]
> @LegendaryGuard If you really want to build them, check the leak all this code came from, if it's not in that leaked source tree, then check the cs:go source tree that was leaked alongside it, that's guaranteed to have it.
This cs:go sourcee tree has issues when compiling the solution, no issues when the solution is created. But it doesn't solve the build thingy nor the project here.
