### ISSUE TITLE
Program received signal SIGILL, Illegal instruction.

### ISSUE THREAD

**Issue by lilmayofuksu** [nillerusr/source-engine#56]
I literally have no idea what causes this error.
This happened on my VPS(Ubuntu 20.04) with dedicated build.

```
Breakpoint 5, CKeyValuesSystem::CKeyValuesSystem (this=0xf7a762a0 <g_KeyValuesSystem>) at ../vstdlib/KeyValuesSystem.cpp:124
124		m_Strings.Init( 4*1024*1024, 64*1024, 0, 4 );

Program received signal SIGILL, Illegal instruction.
CMemoryStack::Init (this=0xf7a762a8 <g_KeyValuesSystem+8>, maxSize=4194304, commitSize=65536, initialCommit=0, alignment=4) at ../tier1/memstack.cpp:117
117		m_pBase = (byte *)MemAlloc_AllocAligned( m_maxSize, alignment ? alignment : 1 );

Program terminated with signal SIGILL, Illegal instruction.
The program no longer exists.
```

![image](https://user-images.githubusercontent.com/11977128/156949180-729ba635-792d-415e-9bf1-a6a2776cd559.png)

**Comment by lilmayofuksu** [comment]
Crash happenes when dedicated_main tries to load vstdlib.so
https://github.com/nillerusr/source-engine/blob/c165fb22361bb509946ca76e7ed39ed939ce04e2/dedicated_main/main.cpp#L207

**Comment by TheASVigilante** [comment]
What does disassembly show?

**Comment by lilmayofuksu** [comment]
I figured out the issue. That error is happening because the build I was using had AVX2 instructions.
https://github.com/lilmayofuksu/source-engine-dedicated/commit/476e4d96e11e7f27a480ac6dab380852ae061643 fixes the issue
