### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by MagicManWithLinux** [nillerusr/source-engine#58]
`Build failed
 -> task in 'vaudio_opus' failed with exit status 1: 
	{task 140627138532944: cxxshlib voiceencoder_opus.cpp.8.o,voice_codec_frame.cpp.8.o,interface.cpp.8.o -> libvaudio_opus.so}
['/usr/bin/g++', '-m32', '-Wl,--no-undefined', '-fPIC', '-march=native', '-mtune=native', '-mfpmath=sse', '-msse', '-msse2', '-pthread', '-shared', 'engine/voice_codecs/opus/voiceencoder_opus.cpp.8.o', 'engine/voice_codecs/frame_encoder/voice_codec_frame.cpp.8.o', 'tier1/interface.cpp.8.o', '-o/home/magicmanwithlinux/source-engine/build/engine/voice_codecs/opus/libvaudio_opus.so', '-Wl,-Bstatic', '-Ltier1', '-ltier1', '-Wl,-Bdynamic', '-Lvstdlib', '-Ltier0', '-lvstdlib', '-ltier0', '-ldl', '-lm', '-lopus']`

**Comment by TheASVigilante** [comment]
Could you provide a little more information about what failed? There is not much to go off of here

**Comment by lilmayofuksu** [comment]
install libopus-dev:i386 try again

**Comment by Aleph-202** [comment]
compile without opus, remove it from wscript
