### ISSUE TITLE
Android NDK Building Question

### ISSUE THREAD

**Issue by IdleFishEngineer** [nillerusr/source-engine#59]
I used android-ndk r10e to build source for android on the centos7 VM,but waf always informed me unable to locate any c++ compiler at the ndk toolchain subfolder,but im sure the compiler binary file is exist.
Whats going on?did i forget about something?
![2022-03-27 16_07_03-CentOS 7 64 位 - VMware Workstation](https://user-images.githubusercontent.com/34435856/160272753-cf9dfaf3-7435-4004-bb21-2356bc7cb583.png)
here is the config log,please check it out.
https://github.com/IdleFishEngineer/ForkStack/blob/main/config.log

**Comment by IdleFishEngineer** [comment]
same as #47  solved.

**Comment by IdleFishEngineer** [comment]
Some other questions:(list of libs not found)
Checking git hash                                       : no 
... ...
Checking for program '/home/srcengbuild/\xe5\x85\xac\xe5\x85\xb1/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-objcopy' : not found 
... ...
... -faligned-new                                                                                                                                               : no 
-> processing test results                                                                                                                                      : 1 test failed 
... ...
... -faligned-new                                                                                                                                               : no 
... ...
... -fnonconst-initializers                                                                                                                                     : no 
-> processing test results                                                                                                                                      : 2 test failed 
... ...
Checking for library opus                                                                                                                                       : not found 
(I'm sure i have installed opus,version is opus-1.0.2-6.el7.x86_64)

Here is the config log,please check it out and give some help.
https://github.com/IdleFishEngineer/ForkStack/blob/main/config.log

**Comment by IdleFishEngineer** [comment]
maybe libopus i386 required?

**Comment by IdleFishEngineer** [comment]
same as  #36, i can't install libopus:i386,because i cant unpack .deb , so i just ignore and remove it from wscript.(Maybe i should try other platform like ubuntu)

**Comment by IdleFishEngineer** [comment]
Question 3:**No wscript file in ivp/havana**
It seems this module need a wscript?But i didn't find any  in the source file.
![image](https://user-images.githubusercontent.com/34435856/160285762-ca941ba4-09b9-4ef9-b904-220707d18047.png)
I upload the config log,please check it out and give some suggestions!!
https://github.com/IdleFishEngineer/ForkStack/blob/main/config.log

**Comment by TheASVigilante** [comment]
Are you sure you pulled the ivp submodule with the engine? Since there is indeed a wscript in it. Try repulling it.

**Comment by IdleFishEngineer** [comment]
> 
Indead, i forgot to clone this module.thank you!

**Comment by IdleFishEngineer** [comment]
> TheASVigilante

Indead, i forgot to clone this module.thank you!
