### ISSUE TITLE
Don't launch in windows branch

### ISSUE THREAD

**Issue by LakoMoor** [nillerusr/source-engine#62]
![image](https://user-images.githubusercontent.com/44299427/161479075-45bb48e7-01fe-443f-874d-6d635b436cd1.png)
Files all compiled. I try use in one folder for all dll and exe files.

**Comment by TheASVigilante** [comment]
Just a sanity check, do you have steam_api.dll compiled?

**Comment by LakoMoor** [comment]
> 
yep
![image](https://user-images.githubusercontent.com/44299427/161492318-20d068fa-d3b9-4552-b686-3fce2c3f2102.png)

**Comment by TheASVigilante** [comment]
What dlls do you have in the bin folder where you're trying to run the game?

**Comment by LakoMoor** [comment]
> What dlls do you have in the bin folder where you're trying to run the game?

![image](https://user-images.githubusercontent.com/44299427/162112761-1f099fd4-1ac5-4f3d-b68e-2da8ed928a62.png)

**Comment by TheASVigilante** [comment]
Is that the exe you're trying to run? Source only checks for dlls in the bin folder thats in the same directory as the exe

**Comment by boris768** [comment]
> > What dlls do you have in the bin folder where you're trying to run the game?
> 
> ![image](https://user-images.githubusercontent.com/44299427/162112761-1f099fd4-1ac5-4f3d-b68e-2da8ed928a62.png)

get original game and backup next dirs
_/bin
/hl2/bin_
**copy to /bin**
_datacache.dll
engine.dll
vaudio_minimp3.dll
filesystem_stdio.dll
GameUI.dll
inputsystem.dll
launcher.dll
materialsystem.dll
shaderapidx9.dll
stdshader_dx9.dll
scenefilecache.dll
ServerBrowser.dll
soundemittersystem.dll
studiorender.dll
steam_api.dll
tier0.dll
vgui2.dll
vguimatsurface.dll
video_services.dll
vphysics.dll
vstdlib.dll_
**copy to hl2/bin**
_client.dll
server.dll_
**copy to game root**
_hl2_launcher.exe_

**Comment by LakoMoor** [comment]
> > > What dlls do you have in the bin folder where you're trying to run the game?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/44299427/162112761-1f099fd4-1ac5-4f3d-b68e-2da8ed928a62.png)
> 
> get original game and backup next dirs _/bin /hl2/bin_ **copy to /bin** _datacache.dll engine.dll vaudio_minimp3.dll filesystem_stdio.dll GameUI.dll inputsystem.dll launcher.dll materialsystem.dll shaderapidx9.dll stdshader_dx9.dll scenefilecache.dll ServerBrowser.dll soundemittersystem.dll studiorender.dll steam_api.dll tier0.dll vgui2.dll vguimatsurface.dll video_services.dll vphysics.dll vstdlib.dll_ **copy to hl2/bin** _client.dll server.dll_ **copy to game root** _hl2_launcher.exe_

Ok its work... But there doesn't give an error, and dont launch :D. I'll try use arguments... unsuccessful

**Comment by boris768** [comment]
> > > > What dlls do you have in the bin folder where you're trying to run the game?
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/44299427/162112761-1f099fd4-1ac5-4f3d-b68e-2da8ed928a62.png)
> > 
> > 
> > get original game and backup next dirs _/bin /hl2/bin_ **copy to /bin** _datacache.dll engine.dll vaudio_minimp3.dll filesystem_stdio.dll GameUI.dll inputsystem.dll launcher.dll materialsystem.dll shaderapidx9.dll stdshader_dx9.dll scenefilecache.dll ServerBrowser.dll soundemittersystem.dll studiorender.dll steam_api.dll tier0.dll vgui2.dll vguimatsurface.dll video_services.dll vphysics.dll vstdlib.dll_ **copy to hl2/bin** _client.dll server.dll_ **copy to game root** _hl2_launcher.exe_
> 
> Ok its work... But there doesn't give an error, and dont launch :D. I'll try use arguments... unsuccessful

yes, there is some error in code with model loading (game cant free memory buffer). You can build debug, but it will be not much playable (tens asserts, main menu is not displayed, gameplay is broken)
![image](https://user-images.githubusercontent.com/3601110/162589662-3c986702-230a-4c7c-a579-196aca46e6eb.png)

**Comment by boris768** [comment]
Ok, i managed to (ghetto)fix release build crash
source-engine\public\tier1\utlmemory.h, line 801
`free( (void*)m_pMemory );`
change to
`g_pMemAlloc->Free((void*)m_pMemory);`

Something is wrong with the linking, it calls MemAlloc::Alloc to allocate memory, but frees it with std::free, which causes a heap corruption error

**Comment by LakoMoor** [comment]
> Хорошо, мне удалось (гетто) исправить сбой сборки релиза source-engine\public\tier1\utlmemory.h, строка 801 `free( (void*)m_pMemory );` изменить на `g_pMemAlloc->Free((void*)m_pMemory);`
> 
> Что-то не так с линковкой, она вызывает MemAlloc::Alloc для выделения памяти, но освобождает ее с помощью std::free, что вызывает ошибку повреждения кучи



> > > > > Какие dll у вас есть в папке bin, где вы пытаетесь запустить игру?
> > > > 
> > > > 
> > > > ![изображение](https://user-images.githubusercontent.com/44299427/162112761-1f099fd4-1ac5-4f3d-b68e-2da8ed928a62.png)
> > > 
> > > 
> > > получить исходную игру и сделать резервную копию следующих каталогов _/bin /hl2/bin _ **скопировать в /bin ** _datacache.dll engine.dll vaudio_minimp3.dll filesystem_stdio.dll GameUI.dll inputsystem.dll launcher.dll materialsystem.dll shaderapidx9.dll stdshader_dx9.dll scenefilecache.dll ServerBrowser.dll soundemittersystem.dll studiorender.dll steam_api.dll tier0.dll vgui2.dll vguimatsurface.dll video_services.dll vphysics.dll vstdlib.dll _ **скопировать в hl2/bin ** _client.dll server.dll _ **скопировать в корень игры ** _hl2_launcher.exe_
> > 
> > 
> > Ок, работает... Но ошибки не выдает и не запускается :D. Я попробую использовать аргументы... безуспешно
> 
> да, ошибка в коде с загрузкой модели (игра не может освободить буфер памяти). Можно собрать отладку, но играть будет не очень (десятки ассертов, главное меню не отображается, геймплей сломан) ![изображение](https://user-images.githubusercontent.com/3601110/162589662-3c986702-230a-4c7c-a579-196aca46e6eb.png)

How you launch ? :D

**Comment by boris768** [comment]
> > Хорошо, мне удалось (гетто) исправить сбой сборки релиза source-engine\public\tier1\utlmemory.h, строка 801 `free( (void*)m_pMemory );` изменить на `g_pMemAlloc->Free((void*)m_pMemory);`
> > Что-то не так с линковкой, она вызывает MemAlloc::Alloc для выделения памяти, но освобождает ее с помощью std::free, что вызывает ошибку повреждения кучи
> 
> > > > > > Какие dll у вас есть в папке bin, где вы пытаетесь запустить игру?
> > > > > 
> > > > > 
> > > > > ![изображение](https://user-images.githubusercontent.com/44299427/162112761-1f099fd4-1ac5-4f3d-b68e-2da8ed928a62.png)
> > > > 
> > > > 
> > > > получить исходную игру и сделать резервную копию следующих каталогов _/bin /hl2/bin _ **скопировать в /bin ** _datacache.dll engine.dll vaudio_minimp3.dll filesystem_stdio.dll GameUI.dll inputsystem.dll launcher.dll materialsystem.dll shaderapidx9.dll stdshader_dx9.dll scenefilecache.dll ServerBrowser.dll soundemittersystem.dll studiorender.dll steam_api.dll tier0.dll vgui2.dll vguimatsurface.dll video_services.dll vphysics.dll vstdlib.dll _ **скопировать в hl2/bin ** _client.dll server.dll _ **скопировать в корень игры ** _hl2_launcher.exe_
> > > 
> > > 
> > > Ок, работает... Но ошибки не выдает и не запускается :D. Я попробую использовать аргументы... безуспешно
> > 
> > 
> > да, ошибка в коде с загрузкой модели (игра не может освободить буфер памяти). Можно собрать отладку, но играть будет не очень (десятки ассертов, главное меню не отображается, геймплей сломан) ![изображение](https://user-images.githubusercontent.com/3601110/162589662-3c986702-230a-4c7c-a579-196aca46e6eb.png)
> 
> How you launch ? :D

I did all what i say here.  
1. clone windows branche
2. patch utlmemory.h
3. build
4. copy to retail game

idk, how this source works good on android (are there too much difference with master branch?), but vgui is broken completly (no UI), all ragdolls have broken physics, static props havent transparency, most particles just broken. BUT, i with this problems finished canals and this was much funny experience to play without scope, hp and armor inidicators, also alliance solders is invisible

**Comment by JusicP** [comment]
> > > Хорошо, мне удалось (гетто) исправить сбой сборки релиза source-engine\public\tier1\utlmemory.h, строка 801 `free( (void*)m_pMemory );` изменить на `g_pMemAlloc->Free((void*)m_pMemory);`
> > > Что-то не так с линковкой, она вызывает MemAlloc::Alloc для выделения памяти, но освобождает ее с помощью std::free, что вызывает ошибку повреждения кучи
> > 
> > 
> > > > > > > Какие dll у вас есть в папке bin, где вы пытаетесь запустить игру?
> > > > > > 
> > > > > > 
> > > > > > ![изображение](https://user-images.githubusercontent.com/44299427/162112761-1f099fd4-1ac5-4f3d-b68e-2da8ed928a62.png)
> > > > > 
> > > > > 
> > > > > получить исходную игру и сделать резервную копию следующих каталогов _/bin /hl2/bin _ **скопировать в /bin ** _datacache.dll engine.dll vaudio_minimp3.dll filesystem_stdio.dll GameUI.dll inputsystem.dll launcher.dll materialsystem.dll shaderapidx9.dll stdshader_dx9.dll scenefilecache.dll ServerBrowser.dll soundemittersystem.dll studiorender.dll steam_api.dll tier0.dll vgui2.dll vguimatsurface.dll video_services.dll vphysics.dll vstdlib.dll _ **скопировать в hl2/bin ** _client.dll server.dll _ **скопировать в корень игры ** _hl2_launcher.exe_
> > > > 
> > > > 
> > > > Ок, работает... Но ошибки не выдает и не запускается :D. Я попробую использовать аргументы... безуспешно
> > > 
> > > 
> > > да, ошибка в коде с загрузкой модели (игра не может освободить буфер памяти). Можно собрать отладку, но играть будет не очень (десятки ассертов, главное меню не отображается, геймплей сломан) ![изображение](https://user-images.githubusercontent.com/3601110/162589662-3c986702-230a-4c7c-a579-196aca46e6eb.png)
> > 
> > 
> > How you launch ? :D
> 
> I did all what i say here.
> 
> 1. clone windows branche
> 2. patch utlmemory.h
> 3. build
> 4. copy to retail game
> 
> idk, how this source works good on android (are there too much difference with master branch?), but vgui is broken completly (no UI), all ragdolls have broken physics, static props havent transparency, most particles just broken. BUT, i with this problems finished canals and this was much funny experience to play without scope, hp and armor inidicators, also alliance solders is invisible

use tf2 shaders

**Comment by LegendaryGuard** [comment]
This issue remains as a TODO to complete a build for Windows, it's referenced to the other issue too: #50 <br/>
In Windows, we should use `createallprojects.bat` to generate the solution, isn't it? I see the script is set for VS2013. 
<br/>Hopefully we can successfully build the solution if all goes well.

Linux (32bits and 64bits) and Android (armv7) are available and can be compiled at the moment, btw.

**Comment by LegendaryGuard** [comment]
When running `waf.bat configure` in Windows CMD, outputs Python errors.

Log:
```batch
C:\msys64\home\user\source-engine>waf.bat configure -T debug --64bits
Página de códigos activa: 1252
Using python
Setting top to                                          : C:\msys64\home\user\source-engine
Setting out to                                          : C:\msys64\home\user\source-engine\build
Checking for program 'CL'                               : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\CL.exe
Checking for program 'CL'                               : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\CL.exe
Checking for program 'LINK'                             : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\LINK.exe
Checking for program 'LIB'                              : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\LIB.exe
Checking for program 'MT'                               : C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\\x86\MT.exe
Checking for program 'RC'                               : C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\\x86\RC.exe
Checking for 'msvc' (C compiler)                        : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\CL.exe
Target OS                                               : win32
Target CPU                                              : x86
Target binfmt                                           : pe
Checking for 'msvc' (C++ compiler)                      : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\CL.exe
Target OS                                               : win32
Target CPU                                              : x86
Target binfmt                                           : pe
Checking for program 'git'                              : C:\Program Files\Git\cmd\git.exe
Checking git hash                                       : 99e6aee
Checking if 'msvc' can target 32-bit                    : yes
Traceback (most recent call last):
  File "C:\msys64\home\user\source-engine\waf3-2.0.22-a21fa92a45548e4c642deabae50eb159\waflib\Scripting.py", line 163, in waf_entry_point
    run_commands()
  File "C:\msys64\home\user\source-engine\waf3-2.0.22-a21fa92a45548e4c642deabae50eb159\waflib\Scripting.py", line 259, in run_commands
    ctx = run_command(cmd_name)
  File "C:\msys64\home\user\source-engine\waf3-2.0.22-a21fa92a45548e4c642deabae50eb159\waflib\Scripting.py", line 243, in run_command
    ctx.execute()
  File "C:\msys64\home\user\source-engine\waf3-2.0.22-a21fa92a45548e4c642deabae50eb159\waflib\Configure.py", line 163, in execute
    super(ConfigurationContext, self).execute()
  File "C:\msys64\home\user\source-engine\waf3-2.0.22-a21fa92a45548e4c642deabae50eb159\waflib\Context.py", line 218, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "C:\msys64\home\user\source-engine\waf3-2.0.22-a21fa92a45548e4c642deabae50eb159\waflib\Context.py", line 300, in recurse
    user_function(self)
  File "C:\msys64\home\user\source-engine\wscript", line 287, in configure
    cflags, linkflags = conf.get_optimization_flags()
  File "C:\msys64\home\user\source-engine\waf3-2.0.22-a21fa92a45548e4c642deabae50eb159\waflib\Configure.py", line 321, in fun
    return f(*k, **kw)
  File "C:\msys64\home\user\source-engine\scripts\waifulib\compiler_optimizations.py", line 150, in get_optimization_flags
    linkflags = conf.get_flags_by_type(LINKFLAGS, conf.options.BUILD_TYPE, conf.env.COMPILER_CC, conf.env.CC_VERSION[0])
IndexError: list index out of range

C:\msys64\home\user\source-engine>
```

**Comment by LegendaryGuard** [comment]
After merging #79 , I opened the solution in VS2022. I see there are projects from VS2013 Windows XP. After building the solution in VS2022 returns all errors, maybe I don't have something or I didn't well, idk.

<img src="https://user-images.githubusercontent.com/49716252/181108718-647fd3e6-16fa-45bb-bf9a-dba80f5687e1.png" alt="everytvs2022slnsourceengine" width=600 />


Build log: [build_everythingsln_usingVS2022.txt](https://github.com/nillerusr/source-engine/files/9193192/build_everythingsln_usingVS2022.txt)

Build line conclusion: <br/>
`========== Build: 0 succeeded, 189 failed, 0 up-to-date, 0 skipped ==========`

No success :(

**Comment by LegendaryGuard** [comment]
Ah, btw, @nillerusr , you forgot to update ivp submodule, source physics have been updated after https://github.com/nillerusr/source-physics/pull/4 PR.

**Comment by WitherOrNot** [comment]
Currently testing build under VS2013, I will try to fix as many Windows build issues as I can.

**Comment by nillerusr** [comment]
@WitherOrNot dont build using vpc

**Comment by nillerusr** [comment]
Maybe i will fix waf build tomorrow

**Comment by LegendaryGuard** [comment]
> Maybe i will fix waf build tomorrow

As you can. 👌 


Meanwhile, I tinkered windows branch, you can execute `waf configure -T release` successfully. Using `waf install` the build fails at [77/2202], the code history is older than master branch and it hasn't been updated so far. <br/>Maybe libs and other resources are fixed there, I think it would get fixed and able to be compiled with waf.

Log of `waf configure -T release` (successful):
```
C:\msys64\home\user\source-engine>waf.bat configure -T release
Página de códigos activa: 1252
Using python
Setting top to                                          : C:\msys64\home\user\source-engine
Setting out to                                          : C:\msys64\home\user\source-engine\build
Build type                                              : release
LTO build                                               : no
PolyOpt build                                           : no
Checking for 'msvc' (C compiler)                        : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\CL.exe
Target OS                                               : win32
Target CPU                                              : x86
Target binfmt                                           : pe
Checking for 'msvc' (C++ compiler)                      : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\CL.exe
Target OS                                               : win32
Target CPU                                              : x86
Target binfmt                                           : pe
Checking for program 'git'                              : C:\Program Files\Git\cmd\git.exe
Checking git hash                                       : edbe1bac-dirty
Checking if 'msvc' can target 32-bit                    : yes
Checking for MSVC library                               : user32
Checking for MSVC library                               : shell32
Checking for MSVC library                               : gdi32
Checking for MSVC library                               : advapi32
Checking for MSVC library                               : dbghelp
Checking for MSVC library                               : psapi
Checking for MSVC library                               : ws2_32
Checking for MSVC library                               : rpcrt4
Checking for MSVC library                               : winmm
Checking for MSVC library                               : wininet
Checking for MSVC library                               : ole32
Checking for MSVC library                               : shlwapi
Checking for MSVC library                               : imm32
Checking for library libz                               : yes
Checking for library nvtc                               : yes
Checking for library ati_compress_mt_vc10               : yes
Checking for library SDL2                               : yes
Checking for library libjpeg                            : yes
Checking for library libpng                             : yes
Checking for library d3dx9                              : yes
Checking for library d3d9                               : yes
Checking for library dsound                             : yes
Checking for library dxguid                             : yes
--> appframework                                        : in progress
<-- appframework                                        : done
--> bitmap                                              : in progress
<-- bitmap                                              : done
--> choreoobjects                                       : in progress
<-- choreoobjects                                       : done
--> datacache                                           : in progress
<-- datacache                                           : done
--> datamodel                                           : in progress
<-- datamodel                                           : done
--> dmxloader                                           : in progress
<-- dmxloader                                           : done
--> engine                                              : in progress
<-- engine                                              : done
--> engine/voice_codecs/minimp3                         : in progress
<-- engine/voice_codecs/minimp3                         : done
--> filesystem                                          : in progress
<-- filesystem                                          : done
--> game/client                                         : in progress
<-- game/client                                         : done
--> game/server                                         : in progress
<-- game/server                                         : done
--> gameui                                              : in progress
<-- gameui                                              : done
--> inputsystem                                         : in progress
<-- inputsystem                                         : done
--> ivp/havana                                          : in progress
<-- ivp/havana                                          : done
--> ivp/havana/havok/hk_base                            : in progress
<-- ivp/havana/havok/hk_base                            : done
--> ivp/havana/havok/hk_math                            : in progress
<-- ivp/havana/havok/hk_math                            : done
--> ivp/ivp_compact_builder                             : in progress
<-- ivp/ivp_compact_builder                             : done
--> ivp/ivp_physics                                     : in progress
<-- ivp/ivp_physics                                     : done
--> launcher                                            : in progress
<-- launcher                                            : done
--> launcher_main                                       : in progress
<-- launcher_main                                       : done
--> materialsystem                                      : in progress
<-- materialsystem                                      : done
--> materialsystem/shaderapidx9                         : in progress
<-- materialsystem/shaderapidx9                         : done
--> materialsystem/shaderlib                            : in progress
<-- materialsystem/shaderlib                            : done
--> materialsystem/stdshaders                           : in progress
<-- materialsystem/stdshaders                           : done
--> mathlib                                             : in progress
<-- mathlib                                             : done
--> particles                                           : in progress
<-- particles                                           : done
--> scenefilecache                                      : in progress
<-- scenefilecache                                      : done
--> serverbrowser                                       : in progress
<-- serverbrowser                                       : done
--> soundemittersystem                                  : in progress
<-- soundemittersystem                                  : done
--> studiorender                                        : in progress
<-- studiorender                                        : done
--> thirdparty/StubSteamAPI                             : in progress
<-- thirdparty/StubSteamAPI                             : done
--> tier0                                               : in progress
<-- tier0                                               : done
--> tier1                                               : in progress
<-- tier1                                               : done
--> tier2                                               : in progress
<-- tier2                                               : done
--> tier3                                               : in progress
<-- tier3                                               : done
--> vgui2/matsys_controls                               : in progress
<-- vgui2/matsys_controls                               : done
--> vgui2/src                                           : in progress
<-- vgui2/src                                           : done
--> vgui2/vgui_controls                                 : in progress
<-- vgui2/vgui_controls                                 : done
--> vgui2/vgui_surfacelib                               : in progress
<-- vgui2/vgui_surfacelib                               : done
--> vguimatsurface                                      : in progress
<-- vguimatsurface                                      : done
--> video                                               : in progress
<-- video                                               : done
--> vphysics                                            : in progress
<-- vphysics                                            : done
--> vpklib                                              : in progress
<-- vpklib                                              : done
--> vstdlib                                             : in progress
<-- vstdlib                                             : done
--> vtf                                                 : in progress
<-- vtf                                                 : done
--> utils/bzip2                                         : in progress
<-- utils/bzip2                                         : done
'configure' finished successfully (9.909s)
```

**Comment by WitherOrNot** [comment]
MSVC seems to not be viable for compiling this, there are too many errors even on the most updated commits. It confuses me especially cause the code should be perfectly valid.

![image](https://user-images.githubusercontent.com/26913821/181151694-776dc5a6-e732-4030-b983-5fa0c399f767.png)

Let's see if we can build with GCC on Cygwin?

**Comment by WitherOrNot** [comment]
Scratch this, it seems the code changes made for Android/Linux caused too many issues for MSVC.

![image](https://user-images.githubusercontent.com/26913821/181177488-71dbb56e-506f-4978-b768-a6eabf253a57.png)

Maybe Cygwin GCC is the way to go after all.

**Comment by nillerusr** [comment]
> Maybe Cygwin GCC

Clang

**Comment by boris768** [comment]
too much to fix for msvc
1. need to delete from all vpc files adding to project files "pointeroverride.asm" (used to add EncodePointer and DecodePointer exports for WinXP)
2. in tier libs - delete std::auto_ptr
3. fix MSVC macro to _MSC_VER - used to detect msvc compiler 

also, createallprojects.bat doesnt create client (game) project

**Comment by LegendaryGuard** [comment]
I think the highest priority to make Windows compileable is to **fix waf build**. Just like nillerusr said this should be looked. 

Then in the medium priority, *Clang could be added*, if we want to debug the code.

We may need a stable MSVC solution to ease the integration of this project and save headaches, time, and effort, also debugging would become more efficient

If there is too much fix to do for MSVC, leave it until after waf build works and get a tool like Clang to ease Windows build progress.

**Comment by WitherOrNot** [comment]
I just created nillerusr/source-engine#82 for fixing errors with `waf configure` on master.

**Comment by LegendaryGuard** [comment]
Waf build for Windows has been completed. <br/>
On the other hand, I've tried to create a solution using `waf.bat msvs`, but in the build step, fails. I've used VS2022 to do that. https://github.com/nillerusr/source-engine/pull/85#issuecomment-1198410104

Something can't process the build step on MSVC.

**Comment by boris768** [comment]
seems works 
![image](https://user-images.githubusercontent.com/3601110/181618433-fc865ba2-de5c-4411-8419-d1f24ecd58bc.png)

**Comment by LegendaryGuard** [comment]
My bad, MSVC solution only works for VS2015 and can build well and looks linked to waf.

**Comment by nillerusr** [comment]
I think it solved now
