### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by MagicManWithLinux** [nillerusr/source-engine#70]
```
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/../../../libSDL2.so when searching for -lSDL2
/usr/bin/ld: skipping incompatible /usr/lib/libSDL2.so when searching for -lSDL2
/usr/bin/ld: cannot find -lSDL2: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/../../../libSDL2.so when searching for -lSDL2
/usr/bin/ld: skipping incompatible /usr/lib/libSDL2.so when searching for -lSDL2
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/../../../libjpeg.so when searching for -ljpeg
/usr/bin/ld: skipping incompatible /usr/lib/libjpeg.so when searching for -ljpeg
/usr/bin/ld: cannot find -ljpeg: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/../../../libjpeg.so when searching for -ljpeg
/usr/bin/ld: skipping incompatible /usr/lib/libjpeg.so when searching for -ljpeg
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/../../../libopenal.so when searching for -lopenal
/usr/bin/ld: skipping incompatible /usr/lib/libopenal.so when searching for -lopenal
/usr/bin/ld: cannot find -lopenal: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/../../../libopenal.so when searching for -lopenal
/usr/bin/ld: skipping incompatible /usr/lib/libopenal.so when searching for -lopenal
collect2: error: ld returned 1 exit status
```

My system:
```
                   -`                    magicman@magicpc 
                  .o+`                   ---------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: M68MT-S2 
               `+oooooo:                 Kernel: 5.17.8-arch1-1 
               -+oooooo+:                Uptime: 18 mins 
             `/:-:++oooo+:               Packages: 1006 (pacman) 
            `/++++/+++++++:              Shell: bash 5.1.16 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: Xfce 4.16 
         ./ooosssso++osssssso+`          WM: Xfwm4 
        .oossssso-````/ossssss+`         WM Theme: Default 
       -osssssso.      :ssssssso.        Theme: Adwaita [GTK2], Breeze [GTK3] 
      :osssssss/        osssso+++.       Icons: Adwaita [GTK2], breeze-dark [GT 
     /ossssssss/        +ssssooo/-       Terminal: xfce4-terminal 
   `/ossssso+/:-        -:/+osssso+-     Terminal Font: Monospace 12 
  `+sso+:-`                 `.-/+oso:    CPU: AMD FX-6300 (6) @ 3.500GHz 
 `++:.                           `-/+/   GPU: NVIDIA GeForce GT 1030 
 .`                                 `/   Memory: 1220MiB / 11952MiB 

```

Full log
[out.txt](https://github.com/nillerusr/source-engine/files/8823143/out.txt)

**Comment by TheASVigilante** [comment]
Did you get the 32-bit versions of those libraries or the 64-bit ones?

**Comment by nillerusr** [comment]
Install 32bit versions of SDL2, jpeg, openal

**Comment by nEmo-iv** [comment]
build failled (Linux Mint 20.3 Una  x86_64) notebook, nvidia 940m


./waf configure -T debug
Setting top to                                          : /home/homyak/source-engine 
Setting out to                                          : /home/homyak/source-engine/build 
Checking for 'gcc' (C compiler)                         : /usr/bin/gcc 
Target OS                                               : linux 
Target CPU                                              : x86_64 
Target binfmt                                           : elf 
Checking for 'g++' (C++ compiler)                       : /usr/bin/g++ 
Target OS                                               : linux 
Target CPU                                              : x86_64 
Target binfmt                                           : elf 
Checking for program 'git'                              : /usr/bin/git 
Checking git hash                                       : 977db93 
Checking for program 'strip'                            : /usr/bin/strip 
Checking for program 'objcopy'                          : /usr/bin/objcopy 
WARNING: will build engine for 32-bit target
Checking if 'gcc' can target 32-bit                     : no 
...trying with additional flags                         : yes 
Checking for required C flags                           : yes 
Checking for required C++ flags                         : yes 
Checking supported flags for g++ in parallel            : started 
... -Wno-reorder                                        : yes 
... -Wno-unused-but-set-variable                        : yes 
... -Wall                                               : yes 
... -Wuninitialized                                     : yes 
... -Wno-unused-function                                : yes 
... -Winit-self                                         : yes 
... -Wno-unused-value                                   : yes 
... -Wno-unknown-pragmas                                : yes 
... -fdiagnostics-color=always                          : yes 
... -Wno-unused-variable                                : yes 
... -Wcast-align                                        : yes 
... -faligned-new                                       : yes 
... -Wstrict-aliasing                                   : yes 
-> processing test results                              : all ok 
Checking supported flags for gcc in parallel            : started 
... -fnonconst-initializers                             : no 
... -Wall                                               : yes 
... -Wno-unknown-pragmas                                : yes 
... -Wcast-align                                        : yes 
... -Wno-unused-function                                : yes 
... -Wuninitialized                                     : yes 
... -fdiagnostics-color=always                          : yes 
... -Wno-unused-value                                   : yes 
... -Winit-self                                         : yes 
... -Wno-unused-variable                                : yes 
... -Wno-unused-but-set-variable                        : yes 
... -faligned-new                                       : no 
... -Wno-reorder                                        : yes 
... -Wstrict-aliasing                                   : yes 
-> processing test results                              : 2 test failed 
Checking for program 'pkg-config'                       : /usr/bin/pkg-config 
Checking for 'sdl2'                                     : yes 
Checking for 'freetype2'                                : yes 
Checking for 'freetype2' sanity                         : yes 
Checking for 'fontconfig'                               : yes 
Checking for 'fontconfig' sanity                        : yes 
Checking for 'openal'                                   : yes 
Checking for 'libjpeg'                                  : yes 
Checking for 'libpng'                                   : yes 
Checking for 'libcurl'                                  : yes 
Checking for 'zlib'                                     : yes 
Checking for 'opus'                                     : yes 
Checking for library dl                                 : yes 
Checking for library bz2                                : yes 
Checking for library rt                                 : yes 
Checking for library m                                  : yes 
--> appframework                                        : in progress 
<-- appframework                                        : done 
--> bitmap                                              : in progress 
<-- bitmap                                              : done 
--> choreoobjects                                       : in progress 
<-- choreoobjects                                       : done 
--> datacache                                           : in progress 
<-- datacache                                           : done 
--> datamodel                                           : in progress 
<-- datamodel                                           : done 
--> dmxloader                                           : in progress 
<-- dmxloader                                           : done 
--> engine                                              : in progress 
<-- engine                                              : done 
--> engine/voice_codecs/minimp3                         : in progress 
<-- engine/voice_codecs/minimp3                         : done 
--> engine/voice_codecs/opus                            : in progress 
<-- engine/voice_codecs/opus                            : done 
--> filesystem                                          : in progress 
<-- filesystem                                          : done 
--> game/client                                         : in progress 
<-- game/client                                         : done 
--> game/server                                         : in progress 
<-- game/server                                         : done 
--> gameui                                              : in progress 
<-- gameui                                              : done 
--> inputsystem                                         : in progress 
<-- inputsystem                                         : done 
--> ivp/havana                                          : in progress 
<-- ivp/havana                                          : done 
--> ivp/havana/havok/hk_base                            : in progress 
<-- ivp/havana/havok/hk_base                            : done 
--> ivp/havana/havok/hk_math                            : in progress 
<-- ivp/havana/havok/hk_math                            : done 
--> ivp/ivp_compact_builder                             : in progress 
<-- ivp/ivp_compact_builder                             : done 
--> ivp/ivp_physics                                     : in progress 
<-- ivp/ivp_physics                                     : done 
--> launcher                                            : in progress 
<-- launcher                                            : done 
--> launcher_main                                       : in progress 
<-- launcher_main                                       : done 
--> materialsystem                                      : in progress 
<-- materialsystem                                      : done 
--> materialsystem/shaderapidx9                         : in progress 
<-- materialsystem/shaderapidx9                         : done 
--> materialsystem/shaderlib                            : in progress 
<-- materialsystem/shaderlib                            : done 
--> materialsystem/stdshaders                           : in progress 
<-- materialsystem/stdshaders                           : done 
--> mathlib                                             : in progress 
<-- mathlib                                             : done 
--> particles                                           : in progress 
<-- particles                                           : done 
--> scenefilecache                                      : in progress 
<-- scenefilecache                                      : done 
--> serverbrowser                                       : in progress 
<-- serverbrowser                                       : done 
--> soundemittersystem                                  : in progress 
<-- soundemittersystem                                  : done 
--> studiorender                                        : in progress 
<-- studiorender                                        : done 
--> thirdparty/StubSteamAPI                             : in progress 
<-- thirdparty/StubSteamAPI                             : done 
--> tier0                                               : in progress 
<-- tier0                                               : done 
--> tier1                                               : in progress 
<-- tier1                                               : done 
--> tier2                                               : in progress 
<-- tier2                                               : done 
--> tier3                                               : in progress 
<-- tier3                                               : done 
--> vgui2/matsys_controls                               : in progress 
<-- vgui2/matsys_controls                               : done 
--> vgui2/src                                           : in progress 
<-- vgui2/src                                           : done 
--> vgui2/vgui_controls                                 : in progress 
<-- vgui2/vgui_controls                                 : done 
--> vgui2/vgui_surfacelib                               : in progress 
<-- vgui2/vgui_surfacelib                               : done 
--> vguimatsurface                                      : in progress 
<-- vguimatsurface                                      : done 
--> video                                               : in progress 
<-- video                                               : done 
--> vphysics                                            : in progress 
<-- vphysics                                            : done 
--> vpklib                                              : in progress 
<-- vpklib                                              : done 
--> vstdlib                                             : in progress 
<-- vstdlib                                             : done 
--> vtf                                                 : in progress 
<-- vtf                                                 : done 
--> togl                                                : in progress 
<-- togl                                                : done 
'configure' finished successfully (0.926s)

============================================

./waf build
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f65f60a8590>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f65f60a8590>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f65f60a8590>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f65f60a8590>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f65f60a8590>
<waflib.extras.clang_compilation_database.ClangDbContext object at 0x7f65f60a8590>
Build commands will be stored in build/compile_commands.json
Waf: Entering directory `/home/homyak/source-engine/build'
<waflib.Build.BuildContext object at 0x7f65f6374250>
<waflib.Build.BuildContext object at 0x7f65f6374250>
<waflib.Build.BuildContext object at 0x7f65f6374250>
<waflib.Build.BuildContext object at 0x7f65f6374250>
<waflib.Build.BuildContext object at 0x7f65f6374250>
<waflib.Build.BuildContext object at 0x7f65f6374250>
[ 366/2186] Compiling ivp/ivp_compact_builder/qhull_user.cxx
[ 371/2186] Compiling ivp/ivp_compact_builder/qhull_merge.cxx
[ 372/2186] Compiling ivp/ivp_compact_builder/qhull_mem.cxx
[ 373/2186] Compiling ivp/ivp_compact_builder/qhull_io.cxx
[ 379/2186] Compiling ivp/ivp_compact_builder/ivp_tetra_intrude.cxx
[ 380/2186] Compiling ivp/ivp_compact_builder/ivp_templates_intern.cxx
[ 385/2186] Compiling ivp/ivp_compact_builder/ivp_surbuild_polyhdrn_cncv.cxx
[ 388/2186] Compiling ivp/ivp_compact_builder/ivp_surbuild_halfspacesoup.cxx
In file included from ../ivp/ivp_compact_builder/ivp_surbuild_polyhdrn_cncv.cxx:4:
../ivp/ivp_surface_manager/ivp_compact_surface.hxx: In member function ‘const IVP_Compact_Ledgetree_Node* IVP_Compact_Surface::get_compact_ledge_tree_root() const’:
../ivp/ivp_surface_manager/ivp_compact_surface.hxx:55:26: error: ‘intptr_t’ was not declared in this scope
   55 |  char *base = (char *)(((intptr_t)this) + this->offset_ledgetree_root);
      |                          ^~~~~~~~
../ivp/ivp_surface_manager/ivp_compact_surface.hxx:55:35: error: expected ‘)’ before ‘this’
   55 |  char *base = (char *)(((intptr_t)this) + this->offset_ledgetree_root);
      |                        ~          ^~~~
      |                                   )
../ivp/ivp_surface_manager/ivp_compact_surface.hxx:55:71: error: expected ‘)’ before ‘;’ token
   55 |  char *base = (char *)(((intptr_t)this) + this->offset_ledgetree_root);
      |                       ~                                               ^
      |                                                                       )

In file included from ../ivp/ivp_compact_builder/qhull_a.hxx:39,
                 from ../ivp/ivp_compact_builder/qhull_io.cxx:20:
../ivp/ivp_compact_builder/qhull_io.cxx: In function ‘void qh_printfacetridges(FILE*, facetT*)’:
../ivp/ivp_compact_builder/qhull_qset.hxx:132:38: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
  132 |         if (((variable= NULL), set)) for(\
      |                                      ^~~
../ivp/ivp_compact_builder/qhull.hxx:834:34: note: in expansion of macro ‘FOREACHsetelement_’
  834 | #define FOREACHridge_(ridges)    FOREACHsetelement_(ridgeT, ridges, ridge)
      |                                  ^~~~~~~~~~~~~~~~~~
../ivp/ivp_compact_builder/qhull_io.cxx:2519:7: note: in expansion of macro ‘FOREACHridge_’
 2519 |       FOREACHridge_(facet->ridges)
      |       ^~~~~~~~~~~~~
../ivp/ivp_compact_builder/qhull_io.cxx:2521:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
 2521 |         fprintf (fp, "\n");
      |         ^~~~~~~

Waf: Leaving directory `/home/homyak/source-engine/build'
Build failed
 -> task in 'ivp_compactbuilder' failed with exit status 1 (run with -v to display more information)
