### ISSUE TITLE
MUSL libc support?

### ISSUE THREAD

**Issue by sodomon2** [nillerusr/source-engine#72]
Support for musl libc

**Comment by TheASVigilante** [comment]
Doable, but the engine relies on the standard library as little as possible so it wouldn't have too much of an effect on performance

**Comment by Er2ch** [comment]
This issue can be closed, it compiles after a63138347b663a4bfd961627b00ad95ea7f27aef

Dependency installation in Alpine linux: `doas apk add sdl2-dev freetype-dev fontconfig-dev openal-soft-dev libjpeg-turbo-dev libpng-dev curl-dev`
(doas is required for user account)
