### ISSUE TITLE
gcc clang icc : not found 

### ISSUE THREAD

**Issue by David770725** [nillerusr/source-engine#73]
log:

Checking for 'gcc' (C compiler)
find program=['gcc', 'cc'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games', '/snap/bin', '/usr/bin'] var='CC' -> ['/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc']
from /home/bill/source-engine: Program ['/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc'] is not executable
not found

Checking for 'clang' (C compiler)
find program=['clang'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games', '/snap/bin', '/usr/bin'] var='CC' -> ['/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc']
from /home/bill/source-engine: Program ['/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc'] is not executable
not found
-------------------------------------------------------
Checking for 'icc' (C compiler)
find program=['icc', 'ICL'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games', '/snap/bin', '/usr/bin'] var='CC' -> ['/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc']
from /home/bill/source-engine: Program ['/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc'] is not executable
not found

what should i do?

**Comment by nillerusr** [comment]
Use correct path for android-ndk

**Comment by WitherOrNot** [comment]
The error suggests that the gcc in android NDK does not have the correct permissions. Did you install it correctly?
