### ISSUE TITLE
Unlock mat_picmip.

### ISSUE THREAD

**Issue by davie504** [nillerusr/source-engine#74]
Valve blocked this cvar at [-1;4] but unlocked it by July 7th. And if you put a value of -10, then it will increase the quality of the texture. Now you have to unlock it in your engine, because good graphics is a key to success. 
Proof:
![800px-Tf2compare1pp2](https://user-images.githubusercontent.com/59658354/178297893-2f2cacbc-f5f5-46b0-9a0e-7212b477d447.jpg)

**Comment by nillerusr** [comment]
Done
