### ISSUE TITLE
VTF 7.5 support

### ISSUE THREAD

**Issue by davie504** [nillerusr/source-engine#83]
It can be useful for recreations of games like Portal 2, CS:GO, Black Mesa, Left4Dead 2 and Alien Swarm. 
Reference: https://github.com/quiverteam/Engine/pull/65/commits/0133ca430907dfd2d4d77e684b256fa7dc126c3f

**Comment by davie504** [comment]
![Uploading Screenshot_2022-07-28-12-36-43-283_com.valvesoftware.source.jpg…]()
You should reopen the issue.

**Comment by LegendaryGuard** [comment]
Does this commit support compatible for older games (HL2, CSS, TF2)? <br/> Looking as the version history says: https://developer.valvesoftware.com/wiki/Valve_Texture_Format#Version_history <br/> Just asking, I still haven't tested the build and idk if I'll have time to test this kind stuff in a game.

**Comment by davie504** [comment]
@LegendaryGuard I converted smg texture to vtf 7.5. 
The engine should support this version of vtf for newer source games.

**Comment by LegendaryGuard** [comment]
> @LegendaryGuard I converted smg texture to vtf 7.5. The engine should support this version of vtf for newer source games.

Ok, so means if we use the engine and put old asset content from a old version of HL2, for example, would work if there are older versions of VTF?

**Comment by davie504** [comment]
> 

It will work by default.

**Comment by LegendaryGuard** [comment]
Thanks for your reply.

We should try it, I hope it doesn't give us a bad feeling. I understand that it isn't just a question of code, but also that the update will have to be experimented with in terms of textures.
I wonder if the artists and modellers are going to complain if the result is the same as what the wiki says: <br/>
_v7.5_<br/>
- _Incompatible with Half-Life 2 Half-Life 2, Counter-Strike: Source Counter-Strike: Source and Team Fortress 2 Team Fortress two._

I hope it doesn't influence. 🙏

**Comment by davie504** [comment]
@LegendaryGuard you misunderstood something. 
Vtf 7.5 doesn't compatible with ORIGINAL engine of tf2, css and hl2. And this commit provide us support of it to this engine.

**Comment by LegendaryGuard** [comment]
Ahh, ok, what a slight relief! 👍 
I thought it could give us texture issues. Ok, I just understand, thanks.

**Comment by davie504** [comment]
Result of https://github.com/nillerusr/source-engine/commit/eb78802b5de8870a9c4a82e280fe024bb072db6c :
![vhwRH81pnTs](https://user-images.githubusercontent.com/59658354/181515067-ebe233bc-e8a4-489f-8f8e-e4e73c7324fa.jpg)
