### ISSUE TITLE
Integer division by zero

### ISSUE THREAD

**Issue by boris768** [nillerusr/source-engine#87]
![devenv_oDcFtsN6PR](https://user-images.githubusercontent.com/3601110/181639742-9704d789-b291-406a-a249-40588b9ee4bf.png)

![chrome_3LSxDdQhmN](https://user-images.githubusercontent.com/3601110/181639195-ec413435-3ce7-4103-81b0-fb982d7fd452.png)

quicksave right before this happens 
[quick.zip](https://github.com/nillerusr/source-engine/files/9214328/quick.zip)

[code line](github.com/nillerusr/source-engine/blob/master/game/shared/baseachievement.cpp#L279
)

tested on windows 10 x64, win32 build from d1ac11a commit

**Comment by LegendaryGuard** [comment]
Good! Could you tell how did you make the MSVC solution work and debug the project? Please? 🙏 
I can open in VS2015 and build successfully, but about debugging and set breakpoints for the launcher program, how?

I would like to write some documentation about debugging solution and it would be nice to know.

**Comment by boris768** [comment]
@LegendaryGuard, i just attached vs to process, i didnt create solution.

**Comment by boris768** [comment]
same bug with "HLX_KILL_ENEMIES_WITHMANHACK"
