### ISSUE TITLE
Couldn't load combo of shader

### ISSUE THREAD

**Issue by loochek** [nillerusr/source-engine#9]
I've successfully built the engine, but it doesn't start:
```
Shader 'shaders\fxc\vertexlit_and_unlit_generic_vs20.vcs' - Couldn't load combo 49152 of shader (dyn=192)
```
How can I fix it?

**Comment by nillerusr** [comment]
It isn't problem, but to run hl2 you sould use shaders from tf2

**Comment by loochek** [comment]
> you sould use shaders from tf2
Funny, but it works

**Comment by sh1rom1k** [comment]
hi , i have same issue , how can i fix that?
[engine.log](https://github.com/user-attachments/files/18026351/engine.log)

**Comment by Kippcase18** [comment]
> > you sould use shaders from tf2
> 
> Funny, but it works

@loochek
I try to launch TF2 but I have same error "Couldn't load combo of shader". How did you resolve this ? I don't know how to "use shaders from tf2".
