### ISSUE TITLE
WorldTwoTextureBlend issue

### ISSUE THREAD

**Issue by garysplay** [nillerusr/source-engine#92]
on windows it has issue with WorldTwoTextureBlend
[engine.log](https://github.com/nillerusr/source-engine/files/9222720/engine.log)

> [4.3216] Warning: using WorldTwoTextureBlend on a non-displacement surface.
> Support for this will go away soon.
>    - Material       : nature/red_grass
>    - Surface center : -5008 -3376 64
> [4.3217] Warning: WorldTwoTextureBlend found on a non-displacement surface (material: nature/red_grass). This wastes perf for no benefit.

**Comment by nillerusr** [comment]
That's normal lol
