### ISSUE TITLE
Termux armhf dedicated build explosion

### ISSUE THREAD

**Issue by SanyaSho** [nillerusr/source-engine#99]
commandbuffer.cpp and datamanager.cpp explodes

> `../public/tier1/utllinkedlist.h:696:10: error: 'this' argument to member function 'GetIndex' has type '__restrict CUtlFixedMemory<UtlLinkedListElem_t<CCommandBuffer::Command_t, int>>', but function is not marked restrict`

and

> `error: restrict requires a pointer or reference ('CUtlLinkedList<CCommandBuffer::Command_t, int, true, int, CUtlFixedMemory<UtlLinkedListElem_t<CCommandBuffer::Command_t, int>>>' is invalid)  error: restrict requires a pointer or reference ('CUtlLinkedList<CCommandBuffer::Command_t, int, true, int, CUtlFixedMemory<UtlLinkedListElem_t<CCommandBuffer::Command_t, int>>>' is invalid)  error: restrict requires a pointer or reference ('CUtlLinkedList<CCommandBuffer::Command_t, int, true, int, CUtlFixedMemory<UtlLinkedListElem_t<CCommandBuffer::Command_t, int>>>' is invalid)  error: restrict requires a pointer or reference ('CUtlLinkedList<CCommandBuffer::Command_t, int, true, int, CUtlFixedMemory<UtlLinkedListElem_t<CCommandBuffer::Command_t, int>>>' is invalid)  6 errors generated.`

configure log:
[configure.log](https://github.com/nillerusr/source-engine/files/9244931/configure.log)

build log:
[build.log](https://github.com/nillerusr/source-engine/files/9244936/build.log)

**Comment by nillerusr** [comment]
clang moment

**Comment by SanyaSho** [comment]
shlang
